import type { Metadata } from "next";
import { GratuityCalc } from "@/components/calculators/gratuity-calc";
import { JsonLd, faqSchema, breadcrumbSchema } from "@/components/json-ld";
import { Breadcrumb, SectionHeading, FAQ } from "@/components/ui";

export const metadata: Metadata = {
  title: "Gratuity Calculator 2026 — Calculate Your Gratuity Amount Online",
  description: "Free online gratuity calculator for 2026. Enter last drawn salary and years of service to calculate gratuity instantly. Covers formula, taxation, eligibility, and the ₹20 lakh tax-free limit.",
  alternates: { canonical: "https://knowledgekendra.com/calculator/gratuity-calculator" },
};

const faqs = [
  { question: "Who is eligible for gratuity in India?", answer: "Any employee who has completed 5 or more years of continuous service with the same employer is eligible. The organization must have had 10+ employees at any point — and once eligible, it remains covered even if headcount drops below 10. In case of death or disability, gratuity is payable regardless of how many years you worked." },
  { question: "How is gratuity calculated?", answer: "The formula is: Gratuity = (Last drawn Basic + DA) × 15 × Completed years of service ÷ 26. Here, 15 represents 15 days of salary for each year of service, and 26 is the number of working days in a month. Only completed years count — 4 years 11 months rounds down to 4 years, not up to 5." },
  { question: "Is gratuity taxable in 2026?", answer: "For private sector employees, gratuity up to ₹20 lakh is completely tax-free under Section 10(10) of the Income Tax Act. This limit was raised from ₹10 lakh to ₹20 lakh in March 2019. For government employees, the entire gratuity amount is tax-free with no upper limit. Any amount above ₹20 lakh for private employees is added to your taxable income and taxed at your slab rate." },
  { question: "Can my employer refuse to pay gratuity?", answer: "No. Gratuity is a statutory right under the Payment of Gratuity Act, 1972. If your employer refuses, you can file a complaint with the Controlling Authority (usually the Labour Commissioner of your state). The employer can only forfeit gratuity if you were terminated for serious misconduct that caused physical or financial damage to the company — and even then, the forfeiture amount is limited to the loss caused." },
  { question: "What salary components are included in gratuity calculation?", answer: "Only Basic Pay + Dearness Allowance (DA) are included. HRA, special allowances, bonuses, overtime, LTA, and other components are excluded. If your salary structure shows a low basic (e.g., 40% of CTC), your gratuity will be calculated on that lower amount — not on your gross or CTC." },
  { question: "Does gratuity apply to contract employees?", answer: "Yes, if you have worked continuously for 5+ years with the same principal employer through a contractor. The Supreme Court has ruled that contract workers are entitled to gratuity. However, if your contract was renewed annually with breaks, the employer may argue the service was not continuous — this is a gray area that often ends up in labour courts." },
  { question: "What happens to gratuity if I resign before 5 years?", answer: "You forfeit gratuity entirely. Even 4 years and 11 months of service means zero gratuity. The only exceptions are death (nominee receives gratuity regardless of tenure) and disability/illness that makes you unable to work. Some companies voluntarily pay pro-rata gratuity for 3+ years, but this is not legally required." },
  { question: "Is gratuity different for government employees?", answer: "Yes, significantly. Government employees get gratuity calculated as: (Basic + DA) × Completed 6-month periods ÷ 4. The formula is slightly more generous, and the maximum limit is ₹25 lakh (higher than private sector). Most importantly, government gratuity is 100% tax-free with no ceiling." },
  { question: "What if I worked in multiple companies?", answer: "Gratuity is calculated separately for each employer. You cannot combine service across companies. If you worked 3 years at Company A and 4 years at Company B, you get gratuity from neither (both below 5-year threshold). This is why the 5-year rule matters — plan your job switches carefully around this milestone." },
  { question: "Does gratuity apply to companies with fewer than 10 employees?", answer: "The Payment of Gratuity Act applies to establishments that have employed 10+ people on any day in the preceding 12 months. Once covered, it remains covered even if headcount drops below 10. Shops, factories, mines, plantations, and IT companies are all covered. Some states have extended coverage to smaller establishments too." },
  { question: "How long does the employer have to pay gratuity?", answer: "The employer must pay gratuity within 30 days of it becoming due (i.e., from your last working day). If the employer delays beyond 30 days, they must pay simple interest at the rate notified by the government (currently 10% per annum) for the delay period. You should submit Form I (application for gratuity) to your employer on your last day." },
  { question: "What is the maximum gratuity amount?", answer: "There is no maximum on the calculated gratuity amount. The ₹20 lakh limit only applies to the tax-free portion. If your gratuity calculates to ₹35 lakh, you receive the full ₹35 lakh — but ₹15 lakh of it is taxable. For government employees, the maximum gratuity payable is ₹25 lakh (this is the actual payment cap, not just tax cap)." },
  { question: "Is gratuity applicable during probation period?", answer: "Probation period counts toward your total years of service for gratuity calculation. If you work 1 year probation + 4 years confirmed = 5 years total, you are eligible for gratuity. The law counts continuous service, not confirmed service." },
  { question: "What happens to gratuity if I am terminated?", answer: "If terminated for any reason other than serious misconduct, you are still entitled to full gratuity (provided 5+ years of service). Even in layoffs or retrenchment, gratuity must be paid. Only termination for willful destruction of employer property or riotous/violent behavior allows forfeiture — and even that is limited to the extent of loss caused." },
  { question: "Can I get gratuity and provident fund both?", answer: "Yes, absolutely. Gratuity and EPF/PPF are separate entitlements. Gratuity is paid by the employer from their own funds. EPF is a joint contribution (employee 12% + employer 12%). Both are payable on resignation/retirement. They serve different purposes — EPF is retirement savings, gratuity is a reward for long service." },
];

export default function Page() {
  return (
    <div className="max-w-[860px] mx-auto px-5 py-6">
      <JsonLd data={breadcrumbSchema([
        { name: "Home", url: "https://knowledgekendra.com" },
        { name: "Calculators", url: "https://knowledgekendra.com/calculator" },
        { name: "Gratuity Calculator 2026", url: "https://knowledgekendra.com/calculator/gratuity-calculator" },
      ])} />
      <JsonLd data={faqSchema(faqs)} />
      <JsonLd data={{ "@context": "https://schema.org", "@type": "WebApplication", name: "Gratuity Calculator 2026", description: "Free online gratuity calculator — enter last drawn salary and years of service to calculate gratuity. Covers formula, taxation, eligibility, and ₹20 lakh tax-free limit.", applicationCategory: "FinanceApplication", operatingSystem: "Web", offers: { "@type": "Offer", price: "0", priceCurrency: "INR" } }} />

      <Breadcrumb items={[{ label: "Home", href: "/" }, { label: "Calculators", href: "/calculator" }, { label: "Gratuity Calculator 2026" }]} />

      <h1 className="text-2xl font-extrabold tracking-tight text-text mb-2">Gratuity Calculator 2026</h1>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-6">Calculate your gratuity amount instantly. Enter your last drawn Basic + DA salary and years of service. Updated with the latest ₹20 lakh tax-free limit (Section 10(10) of Income Tax Act).</p>

      <GratuityCalc />

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #2563EB", backgroundColor: "#DBEAFE" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2">
          <span>💡</span><span>Key fact</span>
        </p>
        <p className="text-sm text-text-secondary leading-relaxed">Gratuity is a <strong>statutory right</strong> under the Payment of Gratuity Act, 1972 — your employer cannot refuse to pay it. The formula is simple: <strong>(Basic + DA) × 15 × Years ÷ 26</strong>. Up to ₹20 lakh is completely tax-free for private employees.</p>
      </div>

      <SectionHeading icon="📖">What is gratuity?</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Gratuity is a lump-sum payment your employer gives you when you leave the company after working for 5 or more years. Think of it as a reward for long and loyal service. The word &apos;gratuity&apos; literally means a gift — but in India, it&apos;s not optional. It&apos;s a legal entitlement under the Payment of Gratuity Act, 1972.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">The law applies to every factory, mine, oilfield, plantation, port, railway, and any establishment with 10 or more employees. Once an establishment is covered, it stays covered even if the employee count drops below 10 later. This means most organized sector employees in India — IT companies, banks, manufacturing, retail chains — are all covered.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Gratuity is paid entirely by the employer, not deducted from your salary. Unlike EPF where both you and your employer contribute, gratuity comes from the employer&apos;s pocket. Some employers set aside a gratuity fund, others pay from their general reserves when an employee leaves.</p>

      <div className="my-6">
        <p className="text-xs text-text-muted mb-2 text-center italic">The standard gratuity formula used across India</p>
        <div className="card p-4 flex justify-center overflow-x-auto" dangerouslySetInnerHTML={{ __html: '<svg viewBox="0 0 700 200" xmlns="http://www.w3.org/2000/svg" style="max-width:100%;height:auto"><text x="350" y="30" text-anchor="middle" font-family="sans-serif" font-size="14" font-weight="700" fill="#111827">Gratuity formula — private sector employees</text><rect x="50" y="55" width="600" height="70" rx="12" fill="#DCFCE7" stroke="#1B6B4A" stroke-width="2"/><text x="350" y="85" text-anchor="middle" font-family="sans-serif" font-size="16" font-weight="700" fill="#145236">Gratuity = (Basic + DA) × 15 × Years of service ÷ 26</text><text x="350" y="112" text-anchor="middle" font-family="sans-serif" font-size="12" fill="#145236">15 = days of salary per year • 26 = working days per month • Only completed years count</text><rect x="50" y="145" width="190" height="45" rx="8" fill="#DBEAFE" stroke="#2563EB" stroke-width="1.5"/><text x="145" y="165" text-anchor="middle" font-family="sans-serif" font-size="11" font-weight="700" fill="#1E40AF">Basic + DA only</text><text x="145" y="180" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#1E40AF">HRA, bonuses excluded</text><rect x="255" y="145" width="190" height="45" rx="8" fill="#FFF7ED" stroke="#EA580C" stroke-width="1.5"/><text x="350" y="165" text-anchor="middle" font-family="sans-serif" font-size="11" font-weight="700" fill="#C2410C">Minimum 5 years</text><text x="350" y="180" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#C2410C">4yr 11mo = 0 gratuity</text><rect x="460" y="145" width="190" height="45" rx="8" fill="#F3E8FF" stroke="#7C3AED" stroke-width="1.5"/><text x="555" y="165" text-anchor="middle" font-family="sans-serif" font-size="11" font-weight="700" fill="#6B21A8">Tax-free up to ₹20L</text><text x="555" y="180" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#6B21A8">Govt employees: no limit</text></svg>' }} />
        <p className="text-sm text-text-secondary mt-3">The 15/26 factor gives you approximately half a month&apos;s salary for each year of service. For someone earning ₹50,000 Basic + DA with 10 years of service, that&apos;s ₹2,88,462 — and it&apos;s entirely tax-free.</p>
      </div>

      <SectionHeading icon="✅">Who is eligible for gratuity?</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">You are eligible for gratuity if you have completed <strong>5 or more years of continuous service</strong> with the same employer. The employer must be covered under the Payment of Gratuity Act (10+ employees at any point).</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">There are two important exceptions where gratuity is payable even without completing 5 years. First, if an employee dies while in service — the nominee receives gratuity regardless of tenure. Second, if an employee becomes disabled due to disease or accident — gratuity is payable immediately.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Contract employees, temporary workers, and fixed-term employees are also eligible if they complete 5 years of continuous service with the same principal employer. The Supreme Court has consistently upheld this interpretation.</p>

      <div className="my-6">
        <p className="text-xs text-text-muted mb-2 text-center italic">Quick eligibility check</p>
        <div className="card p-4 flex justify-center overflow-x-auto" dangerouslySetInnerHTML={{ __html: '<svg viewBox="0 0 700 300" xmlns="http://www.w3.org/2000/svg" style="max-width:100%;height:auto"><defs><marker id="arr-grt" markerWidth="10" markerHeight="10" refX="9" refY="3" orient="auto"><polygon points="0 0, 10 3, 0 6" fill="#1B6B4A"/></marker></defs><text x="350" y="25" text-anchor="middle" font-family="sans-serif" font-size="14" font-weight="700" fill="#111827">Am I eligible for gratuity?</text><rect x="225" y="45" width="250" height="45" rx="8" fill="#FFF7ED" stroke="#EA580C" stroke-width="2"/><text x="350" y="73" text-anchor="middle" font-family="sans-serif" font-size="12" font-weight="700" fill="#C2410C">Worked 5+ years continuously?</text><line x1="350" y1="95" x2="350" y2="125" stroke="#1B6B4A" stroke-width="2" marker-end="url(#arr-grt)"/><text x="380" y="115" font-family="sans-serif" font-size="11" fill="#1B6B4A" font-weight="700">YES</text><rect x="225" y="130" width="250" height="45" rx="8" fill="#FFF7ED" stroke="#EA580C" stroke-width="2"/><text x="350" y="158" text-anchor="middle" font-family="sans-serif" font-size="12" font-weight="700" fill="#C2410C">Employer has/had 10+ employees?</text><line x1="350" y1="180" x2="350" y2="210" stroke="#1B6B4A" stroke-width="2" marker-end="url(#arr-grt)"/><text x="380" y="200" font-family="sans-serif" font-size="11" fill="#1B6B4A" font-weight="700">YES</text><rect x="225" y="215" width="250" height="45" rx="8" fill="#DCFCE7" stroke="#1B6B4A" stroke-width="2"/><text x="350" y="243" text-anchor="middle" font-family="sans-serif" font-size="13" font-weight="700" fill="#145236">✓ You are eligible for gratuity</text><line x1="220" y1="67" x2="100" y2="67" stroke="#DC2626" stroke-width="2"/><text x="90" y="63" text-anchor="end" font-family="sans-serif" font-size="11" font-weight="700" fill="#DC2626">NO</text><rect x="20" y="80" width="160" height="50" rx="8" fill="#FEE2E2" stroke="#DC2626" stroke-width="1.5"/><text x="100" y="103" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#991B1B">Not eligible unless</text><text x="100" y="118" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#991B1B">death or disability</text><line x1="220" y1="152" x2="100" y2="152" stroke="#DC2626" stroke-width="2"/><text x="90" y="148" text-anchor="end" font-family="sans-serif" font-size="11" font-weight="700" fill="#DC2626">NO</text><rect x="20" y="165" width="160" height="50" rx="8" fill="#FEE2E2" stroke="#DC2626" stroke-width="1.5"/><text x="100" y="188" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#991B1B">Act doesn\'t apply</text><text x="100" y="203" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#991B1B">Check state rules</text></svg>' }} />
      </div>

      <blockquote className="my-6 border-l-4 border-accent pl-5 py-2">
        <p className="text-lg font-semibold text-text leading-snug italic">4 years and 11 months of service = <strong>zero gratuity</strong>. The 5-year rule is absolute. Plan your resignations carefully around this milestone — one extra month can mean lakhs of difference.</p>
      </blockquote>

      <SectionHeading icon="🧮">How the gratuity formula works — with examples</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Let&apos;s walk through three real-world examples to understand exactly how much gratuity you&apos;d receive at different salary and tenure levels.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Example 1 — Entry-level IT employee:</strong> Basic + DA = ₹30,000/month, 5 years of service. Gratuity = (30,000 × 15 × 5) ÷ 26 = ₹86,538. Entirely tax-free.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Example 2 — Mid-career manager:</strong> Basic + DA = ₹80,000/month, 15 years. Gratuity = (80,000 × 15 × 15) ÷ 26 = ₹6,92,308. Still entirely tax-free.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Example 3 — Senior executive:</strong> Basic + DA = ₹2,50,000/month, 25 years. Gratuity = (2,50,000 × 15 × 25) ÷ 26 = ₹36,05,769. Here, ₹20 lakh is tax-free and ₹16,05,769 is taxable at your slab rate.</p>

      <div className="my-6">
        <p className="text-xs text-text-muted mb-2 text-center italic">How gratuity grows with tenure (₹50,000 Basic + DA)</p>
        <div className="card p-4 flex justify-center overflow-x-auto" dangerouslySetInnerHTML={{ __html: '<svg viewBox="0 0 700 260" xmlns="http://www.w3.org/2000/svg" style="max-width:100%;height:auto"><text x="350" y="25" text-anchor="middle" font-family="sans-serif" font-size="14" font-weight="700" fill="#111827">Gratuity amount at ₹50,000 Basic + DA — by years</text><line x1="80" y1="210" x2="660" y2="210" stroke="#4B5563" stroke-width="1"/><line x1="80" y1="60" x2="80" y2="210" stroke="#4B5563" stroke-width="1"/><text x="70" y="214" text-anchor="end" font-family="sans-serif" font-size="10" fill="#6B7280">₹0</text><text x="70" y="172" text-anchor="end" font-family="sans-serif" font-size="10" fill="#6B7280">₹3L</text><text x="70" y="134" text-anchor="end" font-family="sans-serif" font-size="10" fill="#6B7280">₹6L</text><text x="70" y="96" text-anchor="end" font-family="sans-serif" font-size="10" fill="#6B7280">₹9L</text><rect x="110" y="196" width="55" height="14" fill="#DBEAFE" stroke="#2563EB" stroke-width="1.5"/><text x="138" y="235" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#4B5563">5yr</text><text x="138" y="192" text-anchor="middle" font-family="sans-serif" font-size="10" font-weight="700" fill="#1E40AF">₹1.4L</text><rect x="200" y="175" width="55" height="35" fill="#DCFCE7" stroke="#1B6B4A" stroke-width="1.5"/><text x="228" y="235" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#4B5563">10yr</text><text x="228" y="171" text-anchor="middle" font-family="sans-serif" font-size="10" font-weight="700" fill="#145236">₹2.9L</text><rect x="290" y="148" width="55" height="62" fill="#DCFCE7" stroke="#1B6B4A" stroke-width="1.5"/><text x="318" y="235" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#4B5563">15yr</text><text x="318" y="144" text-anchor="middle" font-family="sans-serif" font-size="10" font-weight="700" fill="#145236">₹4.3L</text><rect x="380" y="118" width="55" height="92" fill="#FFF7ED" stroke="#EA580C" stroke-width="1.5"/><text x="408" y="235" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#4B5563">20yr</text><text x="408" y="114" text-anchor="middle" font-family="sans-serif" font-size="10" font-weight="700" fill="#C2410C">₹5.8L</text><rect x="470" y="88" width="55" height="122" fill="#F3E8FF" stroke="#7C3AED" stroke-width="1.5"/><text x="498" y="235" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#4B5563">25yr</text><text x="498" y="84" text-anchor="middle" font-family="sans-serif" font-size="10" font-weight="700" fill="#6B21A8">₹7.2L</text><rect x="560" y="60" width="55" height="150" fill="#1B6B4A"/><text x="588" y="235" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#4B5563">30yr</text><text x="588" y="56" text-anchor="middle" font-family="sans-serif" font-size="10" font-weight="700" fill="#1B6B4A">₹8.7L</text></svg>' }} />
        <p className="text-sm text-text-secondary mt-3">At ₹50,000 Basic + DA, gratuity grows linearly — ₹28,846 for each additional year. The relationship is perfectly proportional because the formula has no compounding.</p>
      </div>

      <SectionHeading icon="💰">Gratuity taxation rules 2026</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Gratuity taxation differs based on whether you&apos;re a government employee, private sector employee covered by the Act, or a private employee not covered by the Act.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Government employees</strong> — gratuity is fully exempt from income tax. No limit. Whether you receive ₹5 lakh or ₹25 lakh, it&apos;s 100% tax-free.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Private employees covered under the Act</strong> — the least of three amounts is tax-free: (a) ₹20 lakh, (b) actual gratuity received, (c) 15 days&apos; salary × completed years of service. Any excess is taxed at your slab rate.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Private employees NOT covered under the Act</strong> — the least of three amounts is exempt: (a) ₹20 lakh, (b) actual gratuity received, (c) half-month salary × completed years. The key difference is that &apos;salary&apos; here includes Basic + DA + commissions.</p>

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #DC2626", backgroundColor: "#FEE2E2" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2">
          <span>⚠️</span><span>Common mistake</span>
        </p>
        <p className="text-sm text-text-secondary leading-relaxed">If you receive gratuity from <strong>multiple employers</strong> during your lifetime, the ₹20 lakh tax-free limit is <strong>cumulative, not per employer</strong>. If you got ₹12 lakh from Employer A, you can only claim ₹8 lakh tax-free from Employer B. Many people miss this and face unexpected tax demands.</p>
      </div>

      <div className="my-6">
        <p className="text-xs text-text-muted mb-2 text-center italic">Tax treatment: Government vs Private employees</p>
        <div className="card p-4 flex justify-center overflow-x-auto" dangerouslySetInnerHTML={{ __html: '<svg viewBox="0 0 700 200" xmlns="http://www.w3.org/2000/svg" style="max-width:100%;height:auto"><text x="350" y="25" text-anchor="middle" font-family="sans-serif" font-size="14" font-weight="700" fill="#111827">Gratuity tax rules — who pays what</text><rect x="40" y="55" width="300" height="120" rx="12" fill="#DCFCE7" stroke="#1B6B4A" stroke-width="2"/><text x="190" y="85" text-anchor="middle" font-family="sans-serif" font-size="14" font-weight="700" fill="#145236">Government employee</text><line x1="55" y1="98" x2="325" y2="98" stroke="#1B6B4A" stroke-width="1" opacity="0.3"/><text x="190" y="125" text-anchor="middle" font-family="sans-serif" font-size="20" font-weight="800" fill="#1B6B4A">100% TAX FREE</text><text x="190" y="150" text-anchor="middle" font-family="sans-serif" font-size="12" fill="#145236">Max payable: ₹25 lakh</text><rect x="360" y="55" width="300" height="120" rx="12" fill="#DBEAFE" stroke="#2563EB" stroke-width="2"/><text x="510" y="85" text-anchor="middle" font-family="sans-serif" font-size="14" font-weight="700" fill="#1E40AF">Private employee</text><line x1="375" y1="98" x2="645" y2="98" stroke="#2563EB" stroke-width="1" opacity="0.3"/><text x="510" y="125" text-anchor="middle" font-family="sans-serif" font-size="20" font-weight="800" fill="#2563EB">₹20L TAX FREE</text><text x="510" y="150" text-anchor="middle" font-family="sans-serif" font-size="12" fill="#1E40AF">Above ₹20L taxed at slab rate</text></svg>' }} />
      </div>

      <SectionHeading icon="⚖️">Private sector vs government — key differences</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">The calculation formula itself differs. Private sector uses 15/26 (15 days&apos; salary ÷ 26 working days). Government uses: (Basic + DA) × qualifying service (in half-years) ÷ 4. The government formula is slightly more generous for the same salary and tenure.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">The maximum payable also differs. Private sector has no cap on the calculated amount (only the tax-free portion is capped at ₹20 lakh). Government caps the total payable at ₹25 lakh — but it&apos;s fully tax-free.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">One important difference: government uses &apos;qualifying service&apos; counted in completed 6-month periods. So 10 years and 7 months = 21 half-year periods. Private sector simply counts completed years (10 years and 7 months = 10 years).</p>

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #EA580C", backgroundColor: "#FFF7ED" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2">
          <span>🎯</span><span>Pro tip for IT employees</span>
        </p>
        <p className="text-sm text-text-secondary leading-relaxed">Many IT companies structure your CTC with a low Basic (30-40% of CTC). This drastically reduces your gratuity. If your CTC is ₹12 lakh but Basic + DA is only ₹3.6 lakh (₹30,000/month), your gratuity after 10 years is just ₹1.73 lakh. At a company with ₹50,000 Basic + DA for the same CTC, it would be ₹2.88 lakh — <strong>66% more</strong>.</p>
      </div>

      <SectionHeading icon="🏢">Edge cases most calculators miss</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Seasonal employees:</strong> If you work 6 months per year (e.g., in tourism, agriculture), you become eligible after completing 5 seasons of work, even though calendar time may be 8-10 years.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Merger or acquisition:</strong> If Company A is acquired by Company B, and you continue working, your service is treated as continuous from the original join date at Company A. You don&apos;t restart the 5-year clock.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Gratuity during notice period:</strong> Your notice period counts as part of your service. If you&apos;ve completed 4 years and 10 months and serve a 2-month notice, you&apos;ve completed 5 years and are eligible for gratuity.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Garden leave:</strong> If your employer puts you on paid garden leave, that period also counts toward your total service for gratuity purposes.</p>

      <div className="my-6">
        <p className="text-xs text-text-muted mb-2 text-center italic">Key milestones in your gratuity journey</p>
        <div className="card p-4 flex justify-center overflow-x-auto" dangerouslySetInnerHTML={{ __html: '<svg viewBox="0 0 700 160" xmlns="http://www.w3.org/2000/svg" style="max-width:100%;height:auto"><text x="350" y="22" text-anchor="middle" font-family="sans-serif" font-size="14" font-weight="700" fill="#111827">Your gratuity milestones</text><line x1="60" y1="70" x2="650" y2="70" stroke="#E5E7EB" stroke-width="3"/><circle cx="100" cy="70" r="12" fill="#DC2626"/><text x="100" y="50" text-anchor="middle" font-family="sans-serif" font-size="11" font-weight="700" fill="#DC2626">Year 0-4</text><text x="100" y="100" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#991B1B">No gratuity</text><text x="100" y="113" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#991B1B">if you leave</text><circle cx="250" cy="70" r="15" fill="#1B6B4A"/><text x="250" y="50" text-anchor="middle" font-family="sans-serif" font-size="11" font-weight="700" fill="#1B6B4A">Year 5</text><text x="250" y="100" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#145236">Eligible! First</text><text x="250" y="113" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#145236">gratuity payable</text><circle cx="400" cy="70" r="12" fill="#2563EB"/><text x="400" y="50" text-anchor="middle" font-family="sans-serif" font-size="11" font-weight="700" fill="#2563EB">Year 10-15</text><text x="400" y="100" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#1E40AF">Grows linearly</text><text x="400" y="113" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#1E40AF">each year</text><circle cx="550" cy="70" r="12" fill="#7C3AED"/><text x="550" y="50" text-anchor="middle" font-family="sans-serif" font-size="11" font-weight="700" fill="#7C3AED">Year 20+</text><text x="550" y="100" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#6B21A8">May cross ₹20L</text><text x="550" y="113" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#6B21A8">tax-free limit</text><rect x="100" y="130" width="500" height="22" rx="6" fill="#DCFCE7" stroke="#1B6B4A" stroke-width="1"/><text x="350" y="145" text-anchor="middle" font-family="sans-serif" font-size="10" font-weight="700" fill="#145236">Submit Form I to your employer on your last working day to claim gratuity</text></svg>' }} />
      </div>

      <SectionHeading icon="📋">How to claim gratuity — step by step</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Step 1:</strong> On your last working day, submit <strong>Form I</strong> (Application for Gratuity) to your employer. The form requires your name, address, department, date of joining, date of leaving, and reason for leaving.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Step 2:</strong> The employer must issue <strong>Form L</strong> (Notice of determination of gratuity) within 15 days, stating the gratuity amount. If you disagree with the amount, you can file an objection with the Controlling Authority.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Step 3:</strong> The employer must pay gratuity within <strong>30 days</strong> of it becoming due. If delayed beyond 30 days, interest is payable at 10% per annum.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>If employer refuses:</strong> File a complaint with the Labour Commissioner (Controlling Authority) of your district. You can also approach the labour court if the Authority&apos;s order is unsatisfactory.</p>

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #1B6B4A", backgroundColor: "#DCFCE7" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2">
          <span>📌</span><span>Important for nominees</span>
        </p>
        <p className="text-sm text-text-secondary leading-relaxed">In case of death of the employee, the nominee must submit <strong>Form J</strong> (Application for Gratuity by a nominee/legal heir). Gratuity is payable to the nominee regardless of how many years the employee worked — the 5-year rule is waived.</p>
      </div>

      <SectionHeading icon="📚">Official sources and further reading</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Payment of Gratuity Act, 1972</strong> — the primary legislation. Full text available at <a href="https://labour.gov.in" target="_blank" rel="noopener" className="text-accent hover:underline">labour.gov.in</a>.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Section 10(10) of Income Tax Act</strong> — governs gratuity taxation. Refer to <a href="https://incometaxindia.gov.in" target="_blank" rel="noopener" className="text-accent hover:underline">incometaxindia.gov.in</a> for the latest amendments.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Notification S.O. 1420(E) dated 29 March 2019</strong> — increased the tax-free limit from ₹10 lakh to ₹20 lakh for private sector employees.</p>

      <p className="text-xs text-text-muted mt-6 mb-8 italic">Last reviewed: April 2026 • This page is for informational purposes only and does not constitute legal or tax advice. Consult a qualified professional for your specific situation.</p>

      <SectionHeading icon="📊">Gratuity under the new Labour Code 2025</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">The new Labour Code on Social Security proposes significant changes to gratuity. The most impactful: the 5-year requirement may be reduced to just 1 year for fixed-term contract employees. This would make millions of gig workers, contract staff, and short-tenure employees eligible for gratuity for the first time.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Another proposed change is the definition of wages for gratuity calculation. Under the new code, wages must be at least 50% of CTC. Companies can no longer structure salary with a very low basic (20-30% of CTC) to reduce gratuity liability. If Basic + DA is forced to be 50% of CTC, your gratuity automatically doubles compared to current low-basic structures common in IT companies.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">The new code also proposes a universal social security fund covering gratuity for unorganized workers, platform workers (delivery, ride-hailing), and gig workers. However, implementation remains uncertain — the codes were passed in Parliament in 2020 but states are still notifying rules. Until implemented, the Payment of Gratuity Act 1972 continues to apply.</p>

      <SectionHeading icon="💡">Common gratuity mistakes to avoid</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Mistake 1 — Including HRA in the calculation:</strong> Gratuity is calculated only on Basic + DA. Many employees assume their gross salary or CTC is the base. If your CTC is ₹15 lakh but Basic + DA is only ₹5 lakh, gratuity is calculated on ₹5 lakh — not ₹15 lakh. Always check your payslip for the exact Basic + DA figure.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Mistake 2 — Counting partial years:</strong> If you worked 7 years and 4 months, gratuity is calculated for 7 years only. However, if you worked 7 years and 6 months or more, it rounds up to 8 years — the Act says &quot;for every completed year of service or part thereof in excess of six months.&quot;</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Mistake 3 — Not claiming on time:</strong> You must apply for gratuity within 30 days of it becoming due. While late claims are accepted, delays beyond 5 years can be rejected. File Form I on your last day to protect your rights.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Mistake 4 — Forgetting the cumulative limit:</strong> The ₹20 lakh tax-free limit is cumulative across your entire career, not per employer. If you received ₹8 lakh tax-free from your first job, only ₹12 lakh remains tax-free from future employers.</p>

      <SectionHeading icon="🔢">Gratuity for different scenarios</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Private school teacher:</strong> Teachers in private schools with 10+ staff are covered. A teacher with ₹45,000 Basic + DA retiring after 30 years gets: (45,000 × 15 × 30) ÷ 26 = ₹7,78,846. Fully tax-free.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Employee death in service:</strong> An employee with ₹60,000 Basic + DA dies after 3 years. Despite not completing 5 years, the nominee is eligible. Gratuity = (60,000 × 15 × 3) ÷ 26 = ₹1,03,846. Full amount goes to nominee tax-free. Additionally, EDLI insurance benefit of up to ₹7 lakh may apply.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Termination for misconduct:</strong> An employee with 12 years of service is terminated for damaging company property worth ₹2 lakh. Employer can forfeit gratuity only to the extent of damage — ₹2 lakh. If calculated gratuity is ₹5 lakh, employee still receives ₹3 lakh.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Freelancer/consultant:</strong> Independent contractors are NOT covered under the Gratuity Act, even if they work exclusively for one client for 10+ years. The Act covers only employees — defined as persons employed for wages. If your engagement letter says &quot;contract for services&quot; (not &quot;contract of service&quot;), you are likely not covered.</p>

      <SectionHeading icon="❓">Frequently asked questions</SectionHeading>
      {faqs.map((f: any) => <FAQ key={f.question} question={f.question} answer={f.answer} />)}

      <div className="mt-10 flex flex-wrap gap-2">
        <a href="/calculator/hra-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">HRA Calculator →</a>
        <a href="/calculator/income-tax-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">Income Tax Calculator →</a>
        <a href="/calculator/ppf-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">PPF Calculator →</a>
        <a href="/calculator/fd-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">FD Calculator →</a>
        <a href="/paisa/gratuity-guide" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">Gratuity Complete Guide →</a>
      </div>
    </div>
  );
}
