import type { Metadata } from "next";
import { HraCalc } from "@/components/calculators/hra-calc";
import { JsonLd, faqSchema, breadcrumbSchema } from "@/components/json-ld";
import { Breadcrumb, SectionHeading, FAQ } from "@/components/ui";

export const metadata: Metadata = {
  title: "HRA Calculator 2026 — Calculate HRA Tax Exemption Online",
  description: "Free HRA exemption calculator for 2026. Enter basic salary, HRA received, and rent paid to calculate tax-exempt HRA under Section 10(13A). Metro and non-metro calculation with tax savings estimate.",
  alternates: { canonical: "https://knowledgekendra.com/calculator/hra-calculator" },
};

const faqs = [
  { question: "What is HRA exemption?", answer: "HRA (House Rent Allowance) exemption is a tax benefit under Section 10(13A) of the Income Tax Act. If you receive HRA as part of your salary and actually pay rent for your accommodation, a portion of HRA is exempt from income tax. The exemption reduces your taxable income and thereby your tax liability. It is available only under the old tax regime — the new regime does not allow HRA exemption." },
  { question: "How is HRA exemption calculated?", answer: "HRA exemption is the MINIMUM of three amounts: (1) Actual HRA received from employer, (2) 50% of Basic salary for metro cities (Delhi, Mumbai, Kolkata, Chennai) or 40% for non-metro cities, (3) Rent paid minus 10% of Basic salary. The lowest of these three is your exempt HRA. The remaining HRA (if any) is added to your taxable income." },
  { question: "Which cities are considered metro for HRA?", answer: "Only 4 cities are classified as metro for HRA purposes: Delhi (including NCR areas under Delhi municipal limits), Mumbai (including Navi Mumbai and Thane under BMC), Kolkata, and Chennai. Bangalore, Hyderabad, Pune, Ahmedabad — despite being large cities — are classified as non-metro and get only 40% basic as the HRA ceiling." },
  { question: "Can I claim HRA if I pay rent to parents?", answer: "Yes, you can pay rent to your parents and claim HRA exemption — this is a perfectly legal tax-saving strategy. Your parents must declare the rental income in their tax return. You need a rent agreement and proof of payment (bank transfer preferred over cash). However, you cannot claim HRA if you pay rent to your spouse — this is not allowed." },
  { question: "Can I claim HRA and home loan deduction together?", answer: "Yes, if you live in a rented house in one city (for work) and own a house in another city (where your family lives or as investment). You can claim HRA exemption for the rented house AND home loan interest deduction (Section 24b, up to ₹2 lakh) plus principal repayment (Section 80C, up to ₹1.5 lakh) for the owned house simultaneously. This is a common and legal arrangement." },
  { question: "What if my rent exceeds ₹1 lakh per month?", answer: "If your annual rent exceeds ₹1 lakh (i.e., ₹8,333+ per month), you must deduct TDS at 5% before paying rent to the landlord (if the landlord is a resident). You need the landlord's PAN to deduct TDS. You must file Form 26QC (TDS return) and issue Form 16C to the landlord. Failure to deduct TDS can lead to disallowance of HRA exemption." },
  { question: "Is HRA available in the new tax regime?", answer: "No. The new tax regime (Section 115BAC) does not allow HRA exemption. If you opt for the new regime, HRA received is fully taxable as salary income. This is one of the key factors when choosing between old and new regimes — if your HRA exemption is substantial (₹3-5 lakh annually), the old regime may save more tax despite higher slab rates." },
  { question: "What documents do I need to claim HRA?", answer: "For rent up to ₹1 lakh/year: rent receipts with revenue stamps are sufficient. For rent above ₹1 lakh/year: landlord's PAN is mandatory. Keep a rent agreement (even an 11-month agreement on stamp paper), monthly rent receipts signed by landlord, bank transfer proof, and landlord's PAN card copy. Your employer will ask for these during tax declaration." },
  { question: "Can I claim HRA if I don't receive HRA in salary?", answer: "If your employer doesn't pay HRA as a separate component, you cannot claim Section 10(13A) exemption. However, you can still claim deduction under Section 80GG — up to ₹5,000/month or 25% of total income, whichever is less. Section 80GG is for those who don't receive HRA at all, including self-employed individuals. Available in old regime only." },
  { question: "How does HRA work for shared accommodation?", answer: "If you share a rented apartment with a roommate, you can claim HRA exemption only for YOUR share of the rent. If total rent is ₹20,000 and you split equally, your eligible rent is ₹10,000. Your rent receipt should show only your share. Both roommates can claim HRA for their respective shares if both receive HRA from their employers." },
  { question: "What happens if I own a house in the same city?", answer: "If you own a house in the same city where you work but still pay rent (maybe because the owned house is far from office), you CAN claim HRA — but the tax department may question it. You'll need to justify why you're paying rent despite owning a house (e.g., long commute, owned house is rented out to someone else). If the owned house is in a different city, there's no issue." },
  { question: "Is HRA exemption applicable for house on company lease?", answer: "If your company provides accommodation on a lease basis and deducts rent from your salary, you may still be eligible for HRA exemption. The arrangement must be structured such that HRA is part of your salary and actual rent is paid. However, if the company provides rent-free accommodation as a perquisite, HRA exemption doesn't apply — instead, perquisite rules apply." },
  { question: "What is the maximum HRA exemption I can claim?", answer: "There is no absolute maximum. HRA exemption depends on your actual HRA, basic salary, and rent paid. However, it's always limited by the 'minimum of three' rule. In practice, for someone in metro with ₹60,000 basic and ₹30,000 HRA paying ₹25,000 rent: exempt HRA = min(₹30,000, ₹30,000, ₹19,000) = ₹19,000/month or ₹2.28 lakh/year." },
  { question: "Can I claim HRA if I work from home?", answer: "Yes, if you genuinely pay rent for the house from which you work. The HRA exemption doesn't require you to commute to an office — it requires you to pay rent for your residence. Many employees continued claiming HRA during and after COVID-era WFH. Keep your rent agreement, receipts, and payment proofs ready." },
  { question: "How to maximize HRA tax benefit?", answer: "Three strategies: (1) Pay rent to parents — they may be in a lower tax bracket, so the tax arbitrage benefits both of you. (2) Negotiate a higher HRA component in your salary — restructure CTC to increase HRA at the expense of special allowance (which is fully taxable). (3) If in non-metro, consider if relocating HRA claim to a metro rate is possible based on your work location." },
];

export default function Page() {
  return (
    <div className="max-w-[860px] mx-auto px-5 py-6">
      <JsonLd data={breadcrumbSchema([{ name: "Home", url: "https://knowledgekendra.com" }, { name: "Calculators", url: "https://knowledgekendra.com/calculator" }, { name: "HRA Calculator 2026", url: "https://knowledgekendra.com/calculator/hra-calculator" }])} />
      <JsonLd data={faqSchema(faqs)} />
      <JsonLd data={{ "@context": "https://schema.org", "@type": "WebApplication", name: "HRA Calculator 2026", description: "Free HRA exemption calculator — calculate tax-exempt HRA under Section 10(13A).", applicationCategory: "FinanceApplication", operatingSystem: "Web", offers: { "@type": "Offer", price: "0", priceCurrency: "INR" } }} />

      <Breadcrumb items={[{ label: "Home", href: "/" }, { label: "Calculators", href: "/calculator" }, { label: "HRA Calculator 2026" }]} />

      <h1 className="text-2xl font-extrabold tracking-tight text-text mb-2">HRA Exemption Calculator 2026</h1>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-6">Calculate how much of your HRA is tax-exempt under Section 10(13A). Enter your basic salary, HRA received, rent paid, and city type. Available only under the old tax regime.</p>

      <HraCalc />

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #2563EB", backgroundColor: "#DBEAFE" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2"><span>💡</span><span>The golden rule</span></p>
        <p className="text-sm text-text-secondary leading-relaxed">HRA exemption = <strong>minimum of three values</strong>: (1) Actual HRA received, (2) 50% of Basic for metro / 40% for non-metro, (3) Rent paid minus 10% of Basic. Whichever is lowest — that&apos;s your exemption. The rest of your HRA is taxable.</p>
      </div>

      <SectionHeading icon="📖">What is HRA and why it matters for tax</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">House Rent Allowance (HRA) is a component of your salary that your employer pays to help cover your housing costs. If you receive HRA and actually pay rent for a residence, a portion of the HRA is exempt from income tax under Section 10(13A) of the Income Tax Act. This can save you anywhere from ₹10,000 to ₹2 lakh+ in taxes annually, depending on your salary and rent.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">HRA exemption is one of the most widely used tax deductions by salaried employees in India. Unlike Section 80C (which has a fixed ₹1.5 lakh cap), HRA exemption has no absolute ceiling — it scales with your salary and rent. For high-salary employees in metro cities paying significant rent, HRA exemption can be the single largest tax saver.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">However, HRA exemption is <strong>only available under the old tax regime</strong>. If you&apos;ve opted for the new tax regime (which is the default from FY 2024-25), HRA is fully taxable. This is one of the most important factors when deciding between old and new regimes — run the numbers with and without HRA exemption before choosing.</p>

      <div className="my-6">
        <p className="text-xs text-text-muted mb-2 text-center italic">The three-part HRA exemption formula</p>
        <div className="card p-4 flex justify-center overflow-x-auto" dangerouslySetInnerHTML={{ __html: '<svg viewBox="0 0 700 220" xmlns="http://www.w3.org/2000/svg" style="max-width:100%;height:auto"><text x="350" y="25" text-anchor="middle" font-family="sans-serif" font-size="14" font-weight="700" fill="#111827">HRA exemption = MINIMUM of these three</text><rect x="30" y="55" width="200" height="90" rx="12" fill="#DCFCE7" stroke="#1B6B4A" stroke-width="2"/><text x="130" y="82" text-anchor="middle" font-family="sans-serif" font-size="12" font-weight="700" fill="#145236">Part 1</text><text x="130" y="105" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#145236">Actual HRA received</text><text x="130" y="125" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#145236">from your employer</text><rect x="250" y="55" width="200" height="90" rx="12" fill="#DBEAFE" stroke="#2563EB" stroke-width="2"/><text x="350" y="82" text-anchor="middle" font-family="sans-serif" font-size="12" font-weight="700" fill="#1E40AF">Part 2</text><text x="350" y="105" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#1E40AF">50% of Basic (metro)</text><text x="350" y="125" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#1E40AF">40% of Basic (non-metro)</text><rect x="470" y="55" width="200" height="90" rx="12" fill="#FFF7ED" stroke="#EA580C" stroke-width="2"/><text x="570" y="82" text-anchor="middle" font-family="sans-serif" font-size="12" font-weight="700" fill="#C2410C">Part 3</text><text x="570" y="105" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#C2410C">Rent paid minus</text><text x="570" y="125" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#C2410C">10% of Basic salary</text><rect x="175" y="165" width="350" height="45" rx="10" fill="#1B6B4A"/><text x="350" y="185" text-anchor="middle" font-family="sans-serif" font-size="13" font-weight="700" fill="white">Whichever is LOWEST = your exemption</text><text x="350" y="200" text-anchor="middle" font-family="sans-serif" font-size="11" fill="white">Rest of HRA is added to taxable income</text></svg>' }} />
        <p className="text-sm text-text-secondary mt-3">Part 3 (Rent - 10% of Basic) is usually the limiting factor. This is why paying higher rent doesn&apos;t always give proportionally higher exemption — the 10% basic deduction eats into it.</p>
      </div>

      <SectionHeading icon="🧮">HRA calculation — worked example</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Let&apos;s calculate HRA exemption for a typical IT employee in Bangalore (non-metro for HRA purposes).</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Given:</strong> Basic salary = ₹50,000/month. HRA received = ₹25,000/month. Rent paid = ₹22,000/month. City = Bangalore (non-metro).</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Part 1:</strong> Actual HRA = ₹25,000. <strong>Part 2:</strong> 40% of Basic = ₹20,000. <strong>Part 3:</strong> Rent - 10% of Basic = ₹22,000 - ₹5,000 = ₹17,000.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Exemption:</strong> Minimum of (₹25,000, ₹20,000, ₹17,000) = <strong>₹17,000/month</strong> = ₹2,04,000/year. Taxable HRA = ₹25,000 - ₹17,000 = ₹8,000/month. At 30% tax bracket, this saves ₹61,200/year in taxes.</p>

      <blockquote className="my-6 border-l-4 border-accent pl-5 py-2">
        <p className="text-lg font-semibold text-text leading-snug italic">Bangalore, Hyderabad, Pune, and Ahmedabad are classified as <strong>non-metro</strong> for HRA purposes. Despite being expensive cities, you get only 40% of Basic as the ceiling — not 50%. This catches many employees by surprise.</p>
      </blockquote>

      <SectionHeading icon="🏠">Pay rent to parents — the legal tax hack</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">One of the most effective and completely legal tax-saving strategies is paying rent to your parents. Here&apos;s how it works: if you live with your parents, you can pay them rent, claim HRA exemption on your tax return, and they declare the rental income in their return.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">If your parents are in a lower tax bracket (or have no taxable income at all), the tax saved by you far exceeds the tax paid by them on the rental income. For example, if you save ₹60,000 in tax (at 30% bracket) and your parents pay ₹0 tax (income below ₹3L threshold), the family saves ₹60,000 net.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Requirements:</strong> Have a rent agreement with your parents. Pay rent via bank transfer (not cash). Your parents must own the house or be the primary tenants. They must show rental income in their ITR. Keep rent receipts. If rent exceeds ₹1 lakh/year, you need your parent&apos;s PAN on the receipt.</p>

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #DC2626", backgroundColor: "#FEE2E2" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2"><span>⚠️</span><span>Cannot pay rent to spouse</span></p>
        <p className="text-sm text-text-secondary leading-relaxed">While paying rent to parents is allowed, <strong>paying rent to your spouse is not eligible for HRA exemption</strong>. The Income Tax Act specifically excludes payments to a spouse. If caught, the exemption will be disallowed and you may face penalty. Also, don&apos;t pay rent to yourself (if you own the house you live in) — this is considered a sham transaction.</p>
      </div>

      <SectionHeading icon="⚖️">Old regime vs new regime — HRA factor</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">The new tax regime (default from FY 2024-25) offers lower slab rates but does NOT allow HRA exemption. The old regime has higher slab rates but allows HRA and many other deductions. Which is better depends on your specific numbers.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Rule of thumb:</strong> If your total deductions (HRA + 80C + 80D + NPS + home loan interest) exceed ₹3.75 lakh, the old regime usually saves more. If your deductions are under ₹2.5 lakh, the new regime is likely better. Between ₹2.5-3.75 lakh, calculate both to be sure.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">For employees paying ₹15,000-25,000/month rent with ₹40,000-60,000 basic, HRA exemption alone can be ₹1.5-2.5 lakh. Add ₹1.5L from 80C and ₹50K from 80D/NPS, and total deductions easily exceed ₹3.5L — making the old regime the winner.</p>

      <div className="my-6">
        <p className="text-xs text-text-muted mb-2 text-center italic">When old regime beats new regime</p>
        <div className="card p-4 flex justify-center overflow-x-auto" dangerouslySetInnerHTML={{ __html: '<svg viewBox="0 0 700 200" xmlns="http://www.w3.org/2000/svg" style="max-width:100%;height:auto"><text x="350" y="25" text-anchor="middle" font-family="sans-serif" font-size="14" font-weight="700" fill="#111827">Which tax regime saves more? (₹12L income)</text><rect x="50" y="55" width="280" height="120" rx="12" fill="#DCFCE7" stroke="#1B6B4A" stroke-width="2"/><text x="190" y="80" text-anchor="middle" font-family="sans-serif" font-size="13" font-weight="700" fill="#145236">Old regime + deductions</text><text x="190" y="105" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#145236">HRA exempt: ₹2.0L</text><text x="190" y="122" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#145236">80C: ₹1.5L | NPS: ₹0.5L</text><text x="190" y="148" text-anchor="middle" font-family="sans-serif" font-size="18" font-weight="800" fill="#1B6B4A">Tax: ₹78,000</text><text x="190" y="168" text-anchor="middle" font-family="sans-serif" font-size="11" font-weight="700" fill="#145236">✓ SAVES ₹24,700</text><rect x="370" y="55" width="280" height="120" rx="12" fill="#FEE2E2" stroke="#DC2626" stroke-width="2"/><text x="510" y="80" text-anchor="middle" font-family="sans-serif" font-size="13" font-weight="700" fill="#991B1B">New regime (no deductions)</text><text x="510" y="105" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#991B1B">Standard deduction: ₹75,000</text><text x="510" y="122" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#991B1B">No HRA, no 80C, no NPS</text><text x="510" y="148" text-anchor="middle" font-family="sans-serif" font-size="18" font-weight="800" fill="#DC2626">Tax: ₹1,02,700</text><text x="510" y="168" text-anchor="middle" font-family="sans-serif" font-size="11" font-weight="700" fill="#991B1B">Higher tax</text></svg>' }} />
        <p className="text-sm text-text-secondary mt-3">This example assumes ₹12L income with ₹4L total deductions. The breakeven point varies — use the income tax calculator to compare both regimes for your exact numbers.</p>
      </div>

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #EA580C", backgroundColor: "#FFF7ED" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2"><span>🎯</span><span>Maximize HRA with salary restructuring</span></p>
        <p className="text-sm text-text-secondary leading-relaxed">Ask your HR to restructure your CTC: increase HRA component and decrease Special Allowance. Special Allowance is fully taxable, but HRA gets partial exemption. If your CTC is ₹12L, restructuring to have ₹2.5L HRA (instead of ₹1.5L) with ₹1L less Special Allowance can save ₹20,000-30,000 in tax. Many companies allow this during annual appraisal or on request.</p>
      </div>

      <SectionHeading icon="📋">How to claim HRA — process</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>With employer (most common):</strong> Submit rent receipts to your employer during the tax declaration window (usually January-March). Your employer calculates the HRA exemption and adjusts TDS accordingly. You&apos;ll see reduced HRA in taxable income on your Form 16.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Self-claim in ITR:</strong> If you didn&apos;t submit receipts to your employer, you can claim HRA exemption directly while filing your ITR. Choose the old regime, fill in HRA details under &quot;Salary Income,&quot; and the exemption will be calculated. You may get a refund if excess TDS was deducted.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Rent receipts format:</strong> Each receipt must have: landlord&apos;s name, landlord&apos;s address, tenant&apos;s name, property address, rent amount, period, landlord&apos;s signature, and revenue stamp (for receipts above ₹5,000). If annual rent exceeds ₹1 lakh, landlord&apos;s PAN is mandatory.</p>

      <SectionHeading icon="📚">Official sources</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Section 10(13A)</strong> — HRA exemption rules. <strong>Rule 2A</strong> — calculation method. Both available at <a href="https://incometaxindia.gov.in" target="_blank" rel="noopener" className="text-accent hover:underline">incometaxindia.gov.in</a>. For Section 80GG (HRA for those without HRA component), see <a href="https://incometaxindia.gov.in/pages/acts/income-tax-act.aspx" target="_blank" rel="noopener" className="text-accent hover:underline">Income Tax Act</a>.</p>

      <p className="text-xs text-text-muted mt-6 mb-8 italic">Last reviewed: April 2026 • Sources: Income Tax Act Section 10(13A), Rule 2A. Old tax regime only. This is for informational purposes — consult a CA for your specific situation.</p>

      <SectionHeading icon="📊">HRA exemption — common scenarios</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Scenario 1 — High rent, low basic (common in startups):</strong> Basic = ₹25,000, HRA = ₹15,000, Rent = ₹20,000 in Bangalore (non-metro). Part 1: ₹15,000. Part 2: 40% × ₹25,000 = ₹10,000. Part 3: ₹20,000 - ₹2,500 = ₹17,500. Exemption = ₹10,000 (Part 2 is the bottleneck). Annual saving at 30% = ₹36,000. The low basic is killing your exemption.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Scenario 2 — High basic, moderate rent (typical govt employee):</strong> Basic = ₹80,000, HRA = ₹40,000, Rent = ₹25,000 in Delhi (metro). Part 1: ₹40,000. Part 2: 50% × ₹80,000 = ₹40,000. Part 3: ₹25,000 - ₹8,000 = ₹17,000. Exemption = ₹17,000. Despite high HRA, you only save on ₹17,000 because rent minus 10% basic is the bottleneck. To maximize, increase rent (or move to a better house).</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Scenario 3 — Paying rent to parents:</strong> Basic = ₹60,000, HRA = ₹30,000, Rent to parents = ₹18,000 in Pune (non-metro). Part 1: ₹30,000. Part 2: 40% × ₹60,000 = ₹24,000. Part 3: ₹18,000 - ₹6,000 = ₹12,000. Exemption = ₹12,000. Annual tax saving at 30% = ₹43,200. Parents declare ₹2,16,000 rental income — if below taxable limit, family net saving = ₹43,200.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Scenario 4 — No HRA in salary (Section 80GG):</strong> Self-employed professional with ₹10,00,000 income, paying ₹15,000/month rent. Under 80GG: deduction = least of (a) ₹5,000/month, (b) 25% of total income/12 = ₹20,833, (c) Rent - 10% of income/12 = ₹6,667. Deduction = ₹5,000/month = ₹60,000/year. Much less generous than HRA exemption.</p>

      <SectionHeading icon="⚡">Advanced HRA strategies</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Strategy 1 — Split rent with spouse:</strong> If both spouses work, receive HRA, and live together, only one can claim HRA for the same residence. However, if both genuinely pay separate rents (e.g., one for home, one for a room near office), both can claim independently. The key test: each claim must be for a different property with separate rent agreements.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Strategy 2 — Own house in different city:</strong> This is one of the most powerful tax strategies for salaried employees. Own a house via home loan in your hometown (claim ₹2L interest deduction under Section 24b + ₹1.5L principal under 80C). Simultaneously rent a house in your work city (claim HRA exemption). Three deductions from two properties — all completely legal.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Strategy 3 — Restructure salary for higher HRA:</strong> If your CTC is ₹15 lakh with ₹2 lakh HRA and ₹5 lakh Special Allowance, ask HR to restructure: ₹4 lakh HRA and ₹3 lakh Special Allowance. Same CTC, but HRA exemption doubles. Special Allowance is fully taxable anyway. Most companies allow this restructuring during appraisal cycles.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Strategy 4 — Maintain proper documentation:</strong> The IT department increasingly scrutinizes HRA claims. Keep: (1) registered rent agreement (not just receipts), (2) bank transfer records (avoid cash payments above ₹5,000), (3) landlord PAN copy (if rent exceeds ₹1L/year), (4) landlord&apos;s signed receipts with revenue stamps. If audited, complete documentation means instant acceptance; missing documents mean disallowance and penalty.</p>

      <SectionHeading icon="🔍">HRA during work from home</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">The shift to remote work since 2020 raised questions about HRA eligibility. The answer is straightforward: HRA exemption depends on whether you pay rent for your residence — not whether you commute to an office. If you work from home and pay rent for the house you work from, you can claim HRA exemption fully. Your employer&apos;s WFH policy doesn&apos;t affect your HRA entitlement.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">However, if you moved to a cheaper city during WFH (say from Mumbai to your hometown in a non-metro area), your HRA calculation changes. If your employer still classifies your location as Mumbai (metro, 50%), but you&apos;re actually in a non-metro city (40%), technically you should be claiming at 40%. In practice, most employers continue to use the office location classification unless officially updated.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">If you&apos;re working from home in a house you own (no rent paid), you cannot claim HRA exemption at all. The HRA becomes fully taxable. Some employees in this situation ask their employer to restructure salary — reduce HRA component and increase basic or other allowances. Alternatively, if you have a home loan on the same property, you can claim home loan interest deduction (Section 24b) instead.</p>

      <SectionHeading icon="📱">HRA for different employment types</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Salaried employees with HRA component:</strong> Standard Section 10(13A) exemption as described above. This is the most common scenario. Submit rent receipts to employer during tax declaration, or claim while filing ITR.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Self-employed/freelancers (no HRA):</strong> Claim Section 80GG deduction — least of ₹5,000/month, 25% of total income, or rent minus 10% of income. Maximum annual deduction: ₹60,000. Much less generous than HRA. Available only if you, your spouse, or minor child don&apos;t own residential property in the city where you work.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Government employees:</strong> HRA is part of the 7th CPC allowance structure. Rates are fixed: X cities 24-27%, Y cities 16-18%, Z cities 8-9% of basic (depending on DA level). Government HRA exemption follows the same 10(13A) rules as private sector. The advantage: government HRA rates are standardized, leaving less room for salary restructuring games.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Contract/temporary workers:</strong> If your employer provides HRA as part of your compensation and deducts TDS, you can claim HRA exemption exactly like permanent employees. The key is that HRA must appear as a separate component in your salary slip. If you receive a lumpsum &quot;contract fee&quot; without breakdown, you cannot claim HRA — use Section 80GG instead.</p>

      <SectionHeading icon="❓">Frequently asked questions</SectionHeading>
      {faqs.map((f: any) => <FAQ key={f.question} question={f.question} answer={f.answer} />)}

      <div className="mt-10 flex flex-wrap gap-2">
        <a href="/calculator/income-tax-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">Income Tax Calculator →</a>
        <a href="/calculator/gratuity-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">Gratuity Calculator →</a>
        <a href="/calculator/epf-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">EPF Calculator →</a>
        <a href="/calculator/nps-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">NPS Calculator →</a>
      </div>
    </div>
  );
}
