import type { Metadata } from "next";
import { EmiCalc } from "@/components/calculators/emi-calc";
import { JsonLd, faqSchema, breadcrumbSchema } from "@/components/json-ld";
import { Breadcrumb, SectionHeading, FAQ } from "@/components/ui";

export const metadata: Metadata = {
  title: "EMI Calculator 2026 — Home Loan, Car Loan, Personal Loan EMI",
  description: "Free EMI calculator for 2026. Calculate monthly EMI for home loan, car loan, or personal loan. Enter loan amount, interest rate, and tenure. Shows total interest, payment schedule, and prepayment savings.",
  alternates: { canonical: "https://knowledgekendra.com/calculator/emi-calculator" },
};

const faqs = [
  { question: "What is EMI?", answer: "EMI (Equated Monthly Installment) is a fixed monthly payment you make to repay a loan. Each EMI has two components: principal repayment and interest. In the early years, most of the EMI goes toward interest. In later years, the principal component increases. The EMI formula is: EMI = P × r × (1+r)^n / ((1+r)^n - 1), where P = principal, r = monthly interest rate, n = number of months." },
  { question: "How is home loan EMI calculated?", answer: "Home loan EMI depends on: loan amount, interest rate, and tenure. For ₹50 lakh loan at 8.5% for 20 years: EMI = ₹43,391. Total payment = ₹1.04 crore. Total interest = ₹54 lakh — more than the loan amount itself! Increasing tenure from 20 to 30 years reduces EMI (₹38,446) but increases total interest to ₹88 lakh. Shorter tenure = higher EMI but much less interest." },
  { question: "What is the current home loan interest rate?", answer: "As of April 2026: SBI 8.25-9.25% (based on CIBIL score and loan amount), HDFC 8.35-9.40%, ICICI 8.35-9.35%, Bank of Baroda 8.20-10.30%, Kotak 8.70-9.40%. Rates are linked to repo rate (currently 6.0%) and vary by borrower profile. A CIBIL score above 750 typically gets you the lowest rate at any bank." },
  { question: "How to reduce home loan EMI?", answer: "Five strategies: (1) Improve CIBIL score above 750 for lowest rate. (2) Transfer loan to a bank offering lower rate (balance transfer — saves ₹2-5 lakh over tenure). (3) Make part-prepayments whenever you have surplus (even ₹50,000 reduces tenure by months). (4) Choose longer tenure initially but prepay aggressively. (5) Negotiate with your bank — they often reduce rates for existing customers to prevent balance transfer." },
  { question: "Should I prepay my home loan or invest?", answer: "Compare your loan rate with investment returns after tax. Home loan at 8.5%: prepaying saves 8.5% guaranteed (tax-adjusted ~6% since you lose Section 24b benefit). Equity SIP at 12%: post-tax ~10.5% return. Mathematically, investing wins. But emotionally, being debt-free has value. Balanced approach: use 80% of surplus for SIP, 20% for prepayment. Prioritize prepaying personal loans (16-24% interest) over home loans." },
  { question: "What is the difference between flat rate and reducing balance?", answer: "Flat rate calculates interest on the original loan amount throughout the tenure — even as you repay principal. Reducing balance calculates interest on the outstanding balance — which decreases with each EMI. A 10% flat rate is equivalent to roughly 17-18% reducing balance rate. Always check if the quoted rate is flat or reducing. Banks use reducing balance; NBFCs and car dealers sometimes quote flat rates." },
  { question: "Can I get tax benefit on EMI?", answer: "Home loan: Interest component is deductible under Section 24(b) up to ₹2 lakh/year for self-occupied property. Principal component under 80C up to ₹1.5 lakh. Education loan: Entire interest paid is deductible under Section 80E for 8 years from first repayment year. Car loan and personal loan: No tax benefit on EMI. These benefits are under the old tax regime only." },
  { question: "What happens if I miss an EMI?", answer: "First missed EMI: late payment fee (₹500-2000) + interest on the overdue amount. Also reported to CIBIL — drops your credit score by 50-100 points. 3+ missed EMIs: bank sends legal notice. 6+ missed EMIs: loan classified as NPA (Non-Performing Asset). Bank can initiate recovery proceedings including property auction (home loans) or vehicle repossession (car loans). Always communicate with the bank if you're facing difficulty — they prefer restructuring over recovery." },
  { question: "What is a good CIBIL score for loan approval?", answer: "750+ = Excellent (lowest interest rates, instant approval). 700-749 = Good (approved at slightly higher rates). 650-699 = Fair (approval possible but at premium rates, higher scrutiny). Below 650 = Poor (likely rejected by major banks, may get loans from NBFCs at very high rates). Check your CIBIL score free at cibil.com. Major factors: payment history (35%), credit utilization (30%), credit age (15%)." },
  { question: "EMI for ₹30 lakh home loan — how much?", answer: "At 8.5% interest: 15 years = ₹29,542/month (total interest: ₹23.2L). 20 years = ₹26,035 (interest: ₹32.5L). 25 years = ₹24,157 (interest: ₹42.5L). 30 years = ₹23,067 (interest: ₹53L). Going from 20 to 30 years saves only ₹3,000/month in EMI but costs ₹20.5 lakh more in interest. Choose the shortest tenure your budget allows." },
  { question: "What is the 50-30-20 rule for EMIs?", answer: "Financial advisors recommend: allocate no more than 50% of take-home salary to needs (including all EMIs), 30% to wants, and 20% to savings/investments. Within the 50%, total EMIs (home + car + personal) should not exceed 40% of take-home salary. If your take-home is ₹1 lakh, total EMIs should stay under ₹40,000. Banks typically approve loans if EMI doesn't exceed 50% of net income." },
  { question: "How does loan tenure affect total cost?", answer: "Longer tenure = lower EMI but dramatically higher total interest. ₹50L home loan at 8.5%: 15yr tenure: EMI ₹49,237, total interest ₹38.6L. 20yr: EMI ₹43,391, interest ₹54.1L. 30yr: EMI ₹38,446, interest ₹88.4L. The 30-year option costs ₹50 lakh more in interest than 15-year — that's the entire loan amount extra! Always choose shortest affordable tenure." },
  { question: "What is a floating vs fixed interest rate?", answer: "Floating rate changes with RBI repo rate and bank's MCLR/EBLR. When repo rate rises, your EMI increases (or tenure extends). When it falls, EMI decreases. Fixed rate stays the same throughout the tenure — no surprises, but usually 1-2% higher than floating at the start. Most home loans in India are floating (95%+). Fixed rates are rare and usually 'fixed' only for 2-5 years, then convert to floating." },
  { question: "Can I convert personal loan EMI to a lower rate?", answer: "Yes, through balance transfer — take a new personal loan at lower rate from another bank and close the existing one. Works if your CIBIL score has improved since the original loan. Also consider: top-up on existing home loan (8-9% rate) to pay off personal loan (16-22%). Home loan top-up gives much lower interest than personal loan — but your property is additional collateral." },
  { question: "What is the EMI bounce charge?", answer: "If your bank account doesn't have sufficient balance on EMI date, the auto-debit bounces. Banks charge ₹300-1,000 per bounce + GST. More importantly, it's reported to CIBIL as a missed payment. Set up auto-debit from your salary account and ensure balance covers EMI by 2 days before the debit date. Some banks allow you to choose your EMI date — pick the date right after salary credit." },
];

export default function Page() {
  return (
    <div className="max-w-[860px] mx-auto px-5 py-6">
      <JsonLd data={breadcrumbSchema([{ name: "Home", url: "https://knowledgekendra.com" }, { name: "Calculators", url: "https://knowledgekendra.com/calculator" }, { name: "EMI Calculator 2026", url: "https://knowledgekendra.com/calculator/emi-calculator" }])} />
      <JsonLd data={faqSchema(faqs)} />
      <JsonLd data={{ "@context": "https://schema.org", "@type": "WebApplication", name: "EMI Calculator 2026", description: "Free EMI calculator — calculate monthly EMI for home, car, personal loans.", applicationCategory: "FinanceApplication", operatingSystem: "Web", offers: { "@type": "Offer", price: "0", priceCurrency: "INR" } }} />
      <Breadcrumb items={[{ label: "Home", href: "/" }, { label: "Calculators", href: "/calculator" }, { label: "EMI Calculator 2026" }]} />
      <h1 className="text-2xl font-extrabold tracking-tight text-text mb-2">EMI Calculator 2026</h1>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-6">Calculate your monthly EMI for home loan, car loan, or personal loan. Enter loan amount, interest rate, and tenure. See total interest paid, monthly breakdown, and how prepayments can save you lakhs.</p>
      <EmiCalc />

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #2563EB", backgroundColor: "#DBEAFE" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2"><span>💡</span><span>The hidden cost of long tenure</span></p>
        <p className="text-sm text-text-secondary leading-relaxed">₹50 lakh home loan at 8.5%: <strong>20 years = ₹54L interest</strong>. <strong>30 years = ₹88L interest</strong>. The extra 10 years costs ₹34 lakh — for just ₹5,000 less monthly EMI. Always choose the shortest tenure your budget allows and prepay whenever possible.</p>
      </div>

      <SectionHeading icon="📖">How EMI works — understanding the math</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Every EMI has two parts: interest and principal. In the early months, 70-80% of your EMI goes toward interest and only 20-30% reduces the actual loan. As you keep paying, this ratio gradually reverses — by the final years, most of your EMI reduces the principal. This is why prepaying in the early years has the biggest impact on total interest savings.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">For a ₹50 lakh home loan at 8.5% for 20 years (EMI: ₹43,391): Month 1 interest = ₹35,417 and principal = ₹7,974. Month 120 (year 10): interest = ₹24,234 and principal = ₹19,157. Month 240 (final): interest = ₹305 and principal = ₹43,086. Your EMI stays the same, but where it goes changes dramatically over time.</p>

      <SectionHeading icon="💡">EMI comparison across loan types</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Home loan:</strong> Lowest rate (8-9.5%), longest tenure (up to 30 years), highest tax benefits (₹2L interest + ₹1.5L principal). Property is collateral. Best for: wealth building (property appreciates while you repay).</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Car loan:</strong> Medium rate (8-12%), 5-7 year tenure. Vehicle is collateral (hypothecated). No tax benefit. Car depreciates while you pay — a ₹10L car may be worth ₹4L by loan end. Consider: buy a car you can afford without a loan, or limit EMI to 10% of salary.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Personal loan:</strong> Highest rate (10.5-24%), short tenure (1-5 years), no collateral needed. No tax benefit. Use only for genuine emergencies. Never take personal loans for vacations, gadgets, or weddings — the 16-24% interest compounds against you brutally.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Education loan:</strong> Medium rate (8-12%), repayment starts 1 year after course completion. Full interest deduction under 80E for 8 years. Government schemes like Vidyalakshmi offer subsidized rates for economically weaker students. Best loan to take — education increases earning capacity.</p>

      <blockquote className="my-6 border-l-4 border-accent pl-5 py-2">
        <p className="text-lg font-semibold text-text leading-snug italic">A single ₹5 lakh prepayment in year 3 of a ₹50L, 20-year home loan saves <strong>₹8.2 lakh in interest</strong> and reduces tenure by 2 years. Early prepayment is the most powerful financial move for loan holders.</p>
      </blockquote>

      <SectionHeading icon="🏦">How to get the lowest interest rate</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>1. Build CIBIL score above 750:</strong> Pay all credit card bills in full before due date. Keep credit utilization below 30%. Don&apos;t apply for multiple loans/cards simultaneously. A 750+ score vs 650 score can mean 1-2% lower rate — saving ₹5-10 lakh over a home loan tenure.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>2. Compare across 5+ banks:</strong> Don&apos;t accept the first offer. Use loan aggregator sites (BankBazaar, PaisaBazaar) to compare. Negotiate — banks have flexibility to reduce rates by 0.1-0.3% for good profiles. Every 0.25% rate reduction on a ₹50L loan saves ₹2-3 lakh over 20 years.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>3. Consider balance transfer:</strong> If your existing loan rate is 0.5%+ higher than current market rates, transfer to a new bank. Cost: ₹10,000-25,000 processing fee. Savings: ₹2-10 lakh over remaining tenure. Most banks offer easy balance transfer with minimal documentation. Do this every 2-3 years as rates change.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>4. Choose EBLR-linked loans:</strong> External Benchmark Lending Rate (linked to RBI repo rate) adjusts faster when RBI cuts rates compared to MCLR-based loans. When repo rate decreases, your EBLR loan EMI drops within 3 months. MCLR loans may take 6-12 months to reflect rate cuts. Always ask which benchmark your loan is linked to.</p>

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #DC2626", backgroundColor: "#FEE2E2" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2"><span>⚠️</span><span>Beware of flat rate traps</span></p>
        <p className="text-sm text-text-secondary leading-relaxed">Car dealers and some NBFCs quote &quot;flat rate&quot; interest — e.g., &quot;7% flat.&quot; This sounds lower than a bank&apos;s 9% reducing balance. But flat rate calculates interest on the ORIGINAL loan amount throughout, while reducing balance calculates on the OUTSTANDING amount. <strong>7% flat ≈ 12.5% reducing balance</strong>. Always convert to reducing balance rate before comparing. Ask: &quot;What is the reducing balance equivalent?&quot;</p>
      </div>

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #EA580C", backgroundColor: "#FFF7ED" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2"><span>🎯</span><span>Prepayment strategy</span></p>
        <p className="text-sm text-text-secondary leading-relaxed"><strong>Rule:</strong> Prepay the loan with the highest interest rate first (personal loan before car loan before home loan). Home loans have tax benefits that effectively reduce the rate — prepay those last. <strong>When:</strong> Any surplus — bonus, tax refund, side income — put at least 50% toward prepayment. <strong>How much:</strong> Even ₹25,000-50,000/year of extra payment on a home loan saves ₹5-15 lakh over the tenure.</p>
      </div>

      <SectionHeading icon="📚">Official sources</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">RBI repo rate and lending rate guidelines: <a href="https://www.rbi.org.in" target="_blank" rel="noopener" className="text-accent hover:underline">rbi.org.in</a>. Check your CIBIL score: <a href="https://www.cibil.com" target="_blank" rel="noopener" className="text-accent hover:underline">cibil.com</a>. Compare loan rates: <a href="https://www.bankbazaar.com" target="_blank" rel="noopener" className="text-accent hover:underline">BankBazaar</a>.</p>
      <p className="text-xs text-text-muted mt-6 mb-8 italic">Last reviewed: April 2026 • Rates are indicative and vary by bank and borrower profile. This is for informational purposes only.</p>

      <SectionHeading icon="📊">EMI for common loan amounts — quick reference</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>₹30 lakh home loan at 8.5%:</strong> 15yr EMI = ₹29,542 (total interest ₹23.2L). 20yr EMI = ₹26,035 (interest ₹32.5L). 25yr EMI = ₹24,157 (interest ₹42.5L). Going from 15 to 25 years saves only ₹5,385/month but costs ₹19.3 lakh more interest. The monthly savings seem attractive until you see the total cost.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>₹50 lakh home loan at 8.5%:</strong> 15yr EMI = ₹49,237 (total interest ₹38.6L). 20yr EMI = ₹43,391 (interest ₹54.1L). 30yr EMI = ₹38,446 (interest ₹88.4L). At 30 years, you pay ₹88 lakh interest on a ₹50 lakh loan — 176% of the loan amount in just interest. This is why short tenure + prepayment is the winning strategy.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>₹8 lakh car loan at 9% for 5 years:</strong> EMI = ₹16,607. Total interest = ₹1.96 lakh. The car depreciates 50-60% in 5 years — an ₹8L car is worth ₹3-4L when the loan ends, but you&apos;ve paid ₹9.96L total. This is why financial advisors suggest buying cars you can afford outright or financing no more than 50% of the value.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>₹5 lakh personal loan at 14% for 3 years:</strong> EMI = ₹17,087. Total interest = ₹1.15 lakh. Personal loans are expensive — ₹1.15L interest on ₹5L in just 3 years. If possible, use alternatives: gold loan (9-12%), loan against FD (1-2% above FD rate), or credit card EMI conversion (12-18% but sometimes with zero-cost offers).</p>

      <SectionHeading icon="🏠">Home loan EMI — deep dive</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Amortization schedule:</strong> Banks provide a month-by-month breakdown showing how much of each EMI goes to principal vs interest. In a ₹50L, 20-year loan at 8.5%: first year interest = ₹4.15L, principal = ₹1.06L. Year 10: interest = ₹2.81L, principal = ₹2.39L. Year 20: interest = ₹35K, principal = ₹4.86L. The shift is dramatic — early prepayments save the most because they reduce the base on which interest compounds.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>EMI vs rent trade-off:</strong> If your EMI is equal to or less than the rent you&apos;d pay for a similar property, buying makes financial sense (you build equity instead of paying a landlord). But remember to add property tax, maintenance, insurance, and opportunity cost of down payment. In many Indian metros, buying is 30-50% more expensive per month than renting the same property — renting + investing the difference can be better financially.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>EMI after rate changes:</strong> With floating rate loans, when RBI increases repo rate, your bank may either increase your EMI or extend your tenure (keeping EMI same). Most banks default to extending tenure — so your 20-year loan might become 23-year without you realizing. Check your loan account annually and request EMI increase instead of tenure extension when rates rise.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Joint home loan advantages:</strong> Joint borrowers (usually husband + wife) get combined income for loan eligibility, which increases the sanctioned amount. Both co-borrowers can claim separate tax deductions: each can claim ₹2L interest under 24(b) and ₹1.5L principal under 80C. A ₹80L loan with both spouses as co-borrowers can save ₹1.5-2L in combined tax annually.</p>

      <SectionHeading icon="📱">EMI management — practical tips</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Set EMI date after salary credit:</strong> Most employers credit salary between 25th-1st. Set your EMI date to 5th-7th of the month. This ensures your account has sufficient balance when auto-debit hits. Never set EMI on salary credit date — processing delays can cause bounces. Leave 3-5 day buffer.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Maintain an EMI buffer fund:</strong> Keep 3 months of total EMI payments in a savings account or liquid fund. If you have ₹35,000 total monthly EMIs (home + car), maintain ₹1,05,000 buffer. This protects you against salary delays, job loss, or temporary income disruption without damaging your CIBIL score from missed payments.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Review loan annually:</strong> Every January, check your loan account statement. Verify: (1) Are extra charges being applied that weren&apos;t agreed? (2) Has the interest rate decreased (for floating loans) — is your EMI reflecting it, or did the bank silently extend tenure instead? (3) Has your CIBIL improved enough to request a rate reduction? (4) Are competing banks offering significantly lower rates for balance transfer?</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Prepayment timing:</strong> Make prepayments at the beginning of the financial year (April-May) rather than at year-end. Earlier prepayment reduces the principal base on which interest is calculated for the entire year. ₹2 lakh prepaid in April saves more interest than the same ₹2 lakh prepaid in March. Some banks charge prepayment penalty on fixed-rate loans — check your loan agreement before prepaying.</p>

      <SectionHeading icon="⚖️">Home loan — rent vs buy analysis</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">The rent vs buy decision isn&apos;t just about EMI vs rent comparison. A proper analysis must include: EMI (principal + interest), property tax, maintenance, insurance, registration/stamp duty (amortized), and the opportunity cost of down payment. The &quot;opportunity cost&quot; is what your down payment would earn if invested in equity instead of locked in a house.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Example — ₹1 crore property in Bangalore:</strong> Down payment ₹20L + loan ₹80L. Monthly EMI = ₹69,000 (8.5%, 20yr). Property tax + maintenance = ₹5,000/month. Total monthly cost = ₹74,000. Rent for similar property = ₹35,000-40,000. Buying costs nearly double the rent. However, EMI builds equity (you own the property) while rent builds nothing. After 20 years, you own a property likely worth ₹3-4 crore.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Price-to-rent ratio rule:</strong> Divide property price by annual rent. If ratio is below 15, buying is favorable. 15-20 is neutral. Above 20, renting is better financially. In most Indian metros (Mumbai, Delhi, Bangalore), this ratio is 25-35 — meaning renting + investing the difference gives better financial returns than buying. But emotional factors (stability, pride of ownership) often override the math.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>When buying clearly wins:</strong> You plan to stay 10+ years in the same city. Property prices in your target area are growing 8%+ annually. You can afford EMI that&apos;s similar to rent. You&apos;re getting below-market rate from employer/govt scheme. You need the forced savings discipline (EMI forces you to build asset, rent doesn&apos;t).</p>

      <SectionHeading icon="🏦">Loan restructuring options</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Balance transfer:</strong> Move your existing loan to a bank offering lower rate. Process: apply to new bank → they sanction and issue cheque to old bank → old loan closed → new loan at lower rate. Cost: processing fee (0.5-1% of outstanding) + documentation. Worth doing if rate difference is 0.5%+ and remaining tenure is 10+ years. Can save ₹2-10 lakh over loan life.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Top-up loan:</strong> Need additional funds? Top-up on existing home loan is cheaper (8-9%) than personal loan (14-22%). Top-up amount can be used for any purpose — renovation, education, medical, even investment. Interest on top-up is deductible under Section 24b if used for home renovation. Ask your existing bank first before applying elsewhere.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>EMI holiday/moratorium:</strong> If facing temporary financial difficulty, request an EMI holiday from your bank. Most banks allow 1-3 month moratorium (as seen during COVID). Interest continues to accrue during the holiday period and is added to the outstanding principal. Use this only as a last resort — it increases your total loan cost. Better option: use your EMI buffer fund to bridge the gap.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Tenure reduction vs EMI reduction:</strong> When you prepay or when rates drop, the bank offers two options: reduce EMI (lower monthly burden) or reduce tenure (pay off faster). Always choose tenure reduction — it saves far more interest. Example: on a ₹50L loan with ₹2L prepayment, tenure reduction saves ₹3.2L interest while EMI reduction saves only ₹1.8L. The monthly comfort of lower EMI costs you ₹1.4 lakh.</p>

      <SectionHeading icon="❓">Frequently asked questions</SectionHeading>
      {faqs.map((f: any) => <FAQ key={f.question} question={f.question} answer={f.answer} />)}
      <div className="mt-10 flex flex-wrap gap-2">
        <a href="/calculator/fd-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">FD Calculator →</a>
        <a href="/calculator/sip-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">SIP Calculator →</a>
        <a href="/calculator/income-tax-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">Income Tax Calculator →</a>
        <a href="/calculator/hra-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">HRA Calculator →</a>
      </div>
    </div>
  );
}
