import type { Metadata } from "next";
import { LumpsumCalc } from "@/components/calculators/lumpsum-calc";
import { JsonLd, faqSchema, breadcrumbSchema } from "@/components/json-ld";
import { Breadcrumb, SectionHeading, FAQ } from "@/components/ui";

export const metadata: Metadata = {
  title: "Lumpsum Calculator 2026 — One-Time Mutual Fund Investment Returns",
  description: "Free lumpsum calculator for 2026. Enter one-time investment amount, expected return, and tenure to calculate future value. Compare lumpsum vs SIP returns. Covers taxation, timing, and best strategies.",
  alternates: { canonical: "https://knowledgekendra.com/calculator/lumpsum-calculator" },
};

const faqs = [
  { question: "What is lumpsum investment?", answer: "Lumpsum investment means investing a large amount of money at once in a mutual fund, stock, or other instrument — as opposed to SIP (monthly installments). For example, investing ₹5 lakh in an equity fund in one shot. Lumpsum works best when markets are undervalued (after a crash) and you have idle cash. The entire amount starts compounding immediately." },
  { question: "Lumpsum vs SIP — which gives better returns?", answer: "Statistically, lumpsum beats SIP about 65-70% of the time in equity markets because markets trend upward long-term — putting all money in early gives more compounding time. However, SIP reduces risk through rupee cost averaging and works with monthly income. If you have ₹10 lakh idle cash AND markets have corrected 15%+, lumpsum is likely better. If markets are at all-time highs, spread via STP." },
  { question: "When is the best time for lumpsum investment?", answer: "The best time is when markets have corrected significantly (15-30% from recent highs). Nifty PE ratio below 18-20 historically indicates undervaluation. However, timing the market perfectly is impossible. A practical approach: invest lumpsum in tranches — 40% immediately, 30% after 1 month, 30% after 2 months. This reduces timing risk while still deploying capital faster than SIP." },
  { question: "How is lumpsum return calculated?", answer: "Future Value = Investment × (1 + annual return)^years. For ₹10 lakh at 12% for 10 years: FV = 10,00,000 × (1.12)^10 = ₹31,05,848. Your money tripled in 10 years. The Rule of 72: divide 72 by the return rate to find how many years it takes to double. At 12%, money doubles in 6 years. At 15%, in 4.8 years." },
  { question: "Is lumpsum taxable?", answer: "Tax applies only on redemption, not on investment. Equity funds held over 12 months: LTCG at 12.5% on gains above ₹1.25 lakh/year. Under 12 months: STCG at 20%. Debt funds: all gains taxed at slab rate regardless of holding period. Strategy: hold equity lumpsum for 12+ months to qualify for LTCG. Redeem up to ₹1.25L gain per year tax-free." },
  { question: "What if the market crashes after my lumpsum?", answer: "If you invested ₹10 lakh and market drops 30%, your value drops to ₹7 lakh. This feels terrible but only matters if you sell. Historical data: every 30%+ crash in India (2008, 2020) was followed by a recovery to new highs within 2-3 years. If your horizon is 7+ years, temporary crashes are opportunities, not threats. If you can't handle seeing ₹10L become ₹7L, use SIP instead." },
  { question: "Which mutual funds are best for lumpsum?", answer: "For conservative lumpsum: large-cap index fund (Nifty 50) — lowest volatility among equity. For moderate: flexi-cap or multi-cap fund — diversified across company sizes. For aggressive: mid-cap or small-cap fund — highest growth potential but also highest volatility. Never put lumpsum in sectoral/thematic funds — too concentrated. For debt lumpsum: liquid fund or short-duration fund." },
  { question: "What is STP and how does it help with lumpsum?", answer: "STP (Systematic Transfer Plan) is a bridge between lumpsum and SIP. You invest the lumpsum in a liquid/debt fund, then set up automatic monthly transfers to an equity fund over 6-12 months. This gives rupee cost averaging (like SIP) while your idle money earns 6-7% in the liquid fund instead of 3-4% in savings account. Best of both worlds for large sums in uncertain markets." },
  { question: "How much can ₹10 lakh grow in 20 years?", answer: "At 10% return: ₹67 lakh. At 12%: ₹96 lakh. At 14%: ₹1.37 crore. At 15%: ₹1.64 crore. The difference between 10% and 15% over 20 years is nearly ₹1 crore — on the same ₹10 lakh investment. This is why choosing the right fund (and keeping costs low via direct plans) matters enormously for lumpsum investing." },
  { question: "Should I invest lumpsum in ELSS for tax saving?", answer: "ELSS lumpsum qualifies for 80C deduction up to ₹1.5 lakh. Lock-in is 3 years (shortest among 80C options). If you have surplus cash and haven't maxed 80C, investing ₹1.5L lumpsum in ELSS before March 31 gives immediate tax saving. Better than ₹12,500/month SIP in ELSS if you have the lumpsum available — earlier investment = more compounding time." },
  { question: "What is the minimum lumpsum for mutual funds?", answer: "Most mutual funds accept minimum ₹5,000 lumpsum (some start at ₹1,000). There's no maximum limit. For liquid funds, minimum is usually ₹500. You can invest through AMC websites (direct plans), apps like Groww or Zerodha Coin, or through distributors. Always choose direct plans for lower expense ratio — saves 0.5-1.5% annually." },
  { question: "Can I withdraw lumpsum investment anytime?", answer: "Open-ended mutual funds: yes, withdraw anytime (except ELSS which has 3-year lock-in). Exit load of 1% may apply if redeemed within 12 months for equity funds (varies by fund). Liquid funds: no exit load after 7 days. Closed-ended funds: cannot be redeemed before maturity (but can be sold on stock exchange at a discount). Always check exit load before investing." },
  { question: "Is it better to invest lumpsum in stock or mutual fund?", answer: "Mutual funds provide diversification across 50-100 stocks, professional management, and no need for stock analysis. Individual stocks can give higher returns but with much higher risk — one wrong pick can wipe out capital. For most investors, lumpsum in a diversified equity mutual fund is better. Only invest lumpsum in individual stocks if you can analyze financial statements and valuations yourself." },
];

export default function Page() {
  return (
    <div className="max-w-[860px] mx-auto px-5 py-6">
      <JsonLd data={breadcrumbSchema([{ name: "Home", url: "https://knowledgekendra.com" }, { name: "Calculators", url: "https://knowledgekendra.com/calculator" }, { name: "Lumpsum Calculator 2026", url: "https://knowledgekendra.com/calculator/lumpsum-calculator" }])} />
      <JsonLd data={faqSchema(faqs)} />
      <JsonLd data={{ "@context": "https://schema.org", "@type": "WebApplication", name: "Lumpsum Calculator 2026", description: "Free lumpsum calculator — calculate one-time mutual fund investment returns.", applicationCategory: "FinanceApplication", operatingSystem: "Web", offers: { "@type": "Offer", price: "0", priceCurrency: "INR" } }} />
      <Breadcrumb items={[{ label: "Home", href: "/" }, { label: "Calculators", href: "/calculator" }, { label: "Lumpsum Calculator 2026" }]} />
      <h1 className="text-2xl font-extrabold tracking-tight text-text mb-2">Lumpsum Calculator 2026</h1>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-6">Calculate how a one-time investment grows over time. Enter your lumpsum amount, expected annual return, and investment period. See the power of compounding on a single investment.</p>
      <LumpsumCalc />

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #2563EB", backgroundColor: "#DBEAFE" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2"><span>💡</span><span>Rule of 72</span></p>
        <p className="text-sm text-text-secondary leading-relaxed">Quick mental math: <strong>72 ÷ return rate = years to double</strong>. At 12%, money doubles in 6 years. ₹10 lakh becomes ₹20L in 6 years, ₹40L in 12 years, ₹80L in 18 years, ₹1.6 crore in 24 years. Four doublings from one investment — that&apos;s compounding.</p>
      </div>

      <SectionHeading icon="📖">How lumpsum investment works</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">When you invest a lumpsum, the entire amount starts working for you immediately. Unlike SIP where money enters the market gradually over months/years, lumpsum puts everything to work on day one. This is both the advantage (maximum compounding time) and the risk (full exposure to day-one market price).</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">The formula is simple: Future Value = Present Value × (1 + r)^n. For ₹10 lakh at 12% for 15 years: FV = 10,00,000 × (1.12)^15 = ₹54,73,566. Your investment grew by ₹44.7 lakh — more than 4× the original amount. The key variable is time: the same ₹10 lakh at 12% for 25 years becomes ₹1.7 crore. Doubling the time more than tripled the gain.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Lumpsum investing is ideal when you receive a large sum — annual bonus, property sale proceeds, inheritance, retirement benefits, or matured FD. Instead of letting it sit in a savings account earning 3-4%, deploying it in a diversified equity fund at 12%+ makes a massive difference over the long term.</p>

      <SectionHeading icon="📊">Lumpsum growth — the numbers</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>₹5 lakh lumpsum:</strong> At 10%: 10yr = ₹12.97L, 20yr = ₹33.64L, 30yr = ₹87.25L. At 12%: 10yr = ₹15.53L, 20yr = ₹48.23L, 30yr = ₹1.50Cr. At 15%: 10yr = ₹20.23L, 20yr = ₹81.83L, 30yr = ₹3.31Cr.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>₹10 lakh lumpsum:</strong> At 12% for 10yr = ₹31.06L. For 20yr = ₹96.46L. For 30yr = ₹2.99Cr. At 15% for 20yr = ₹1.64Cr. For 30yr = ₹6.62Cr. The difference between 12% and 15% return over 30 years on ₹10 lakh is ₹3.63 crore — fund selection matters enormously for lumpsum investing.</p>

      <blockquote className="my-6 border-l-4 border-accent pl-5 py-2">
        <p className="text-lg font-semibold text-text leading-snug italic">₹10 lakh invested at age 25 at 12% return = <strong>₹2.99 crore at age 55</strong>. The same ₹10 lakh invested at age 35 = ₹96 lakh at age 55. Starting 10 years earlier gives <strong>3× more wealth</strong> from the same one-time investment.</p>
      </blockquote>

      <SectionHeading icon="🎯">When to invest lumpsum vs SIP</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Use lumpsum when:</strong> Markets have corrected 15-30% from highs (Nifty PE below 18-20). You have idle cash earning low returns. You&apos;re investing in debt/liquid funds (timing doesn&apos;t matter for debt). You received a windfall (bonus, inheritance) and have a 7+ year horizon.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Use SIP when:</strong> Markets are at all-time highs or you&apos;re uncertain about direction. Your income is monthly (salary). You&apos;re investing for the first time (SIP builds discipline). You&apos;re emotionally averse to seeing a large sum drop in value during corrections.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Use STP when:</strong> You have a lumpsum but markets seem expensive. Park in liquid fund, transfer to equity over 6-12 months. Best of both — idle money earns ~6% while you get rupee cost averaging into equity. Cost: zero (no exit load on liquid funds after 7 days).</p>

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #DC2626", backgroundColor: "#FEE2E2" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2"><span>⚠️</span><span>Lumpsum mistakes to avoid</span></p>
        <p className="text-sm text-text-secondary leading-relaxed"><strong>1.</strong> Investing lumpsum in small-cap/sectoral funds — too volatile for single-entry point. Stick to diversified large-cap or flexi-cap. <strong>2.</strong> Panicking and redeeming during a 20% dip — if your horizon is 7+ years, sit tight. <strong>3.</strong> Putting all savings in one fund — spread across 2-3 funds for diversification. <strong>4.</strong> Not checking exit load — redeeming within 12 months may cost 1% of NAV.</p>
      </div>

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #EA580C", backgroundColor: "#FFF7ED" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2"><span>🎯</span><span>Optimal lumpsum strategy</span></p>
        <p className="text-sm text-text-secondary leading-relaxed"><strong>Step 1:</strong> Keep 6 months expenses in liquid fund (emergency). <strong>Step 2:</strong> Invest lumpsum in Nifty 50 index fund (direct plan) for the core. <strong>Step 3:</strong> If amount exceeds ₹10 lakh, split: 60% large-cap index + 25% mid-cap index + 15% debt/liquid. <strong>Step 4:</strong> Hold for 7+ years minimum. <strong>Step 5:</strong> Harvest ₹1.25L LTCG exemption annually if needed.</p>
      </div>

      <SectionHeading icon="📚">Official source</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">AMFI mutual fund nav and returns: <a href="https://www.amfiindia.com" target="_blank" rel="noopener" className="text-accent hover:underline">amfiindia.com</a>. Fund comparison: <a href="https://www.valueresearchonline.com" target="_blank" rel="noopener" className="text-accent hover:underline">Value Research</a>. SEBI regulations: <a href="https://www.sebi.gov.in" target="_blank" rel="noopener" className="text-accent hover:underline">sebi.gov.in</a>.</p>
      <p className="text-xs text-text-muted mt-6 mb-8 italic">Last reviewed: April 2026 • Mutual fund investments are subject to market risks. Past performance doesn&apos;t guarantee future returns.</p>

      <SectionHeading icon="📈">Lumpsum investing — real market examples</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>2008 crash investor:</strong> Someone who invested ₹10 lakh in Nifty 50 index fund at the October 2008 bottom (~2,600 level) saw their investment grow to approximately ₹85 lakh by 2024 (Nifty ~22,000). That&apos;s 8.5× return in 16 years — about 14.5% CAGR. Lumpsum during crashes creates life-changing wealth.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>2020 COVID crash investor:</strong> ₹10 lakh invested in Nifty 50 at the March 2020 bottom (~8,000) grew to approximately ₹28 lakh by 2024 (Nifty ~22,000). That&apos;s 2.8× in just 4 years — approximately 29% CAGR. These windows of opportunity are rare (happen once every 5-10 years) but life-changing for those who deploy lumpsum during panic.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>2024 all-time high investor:</strong> Someone who invested ₹10 lakh at the September 2024 Nifty high (~26,000) would have seen the value drop to ~₹8.5L during the October-December 2024 correction, then recover. This illustrates the risk of poorly-timed lumpsum — temporary losses are real and emotionally painful. The key: lumpsum at highs requires 5+ year patience.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>The lesson:</strong> Market timing is impossible to get right consistently. If you must invest lumpsum in equity, spread it over 3-6 months via STP. If you happen to catch a crash, deploy aggressively. The long-term trend is up — so any lumpsum invested for 10+ years has historically been profitable regardless of entry point.</p>

      <SectionHeading icon="💰">Lumpsum taxation — what you need to know</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Equity mutual fund lumpsum:</strong> Held over 12 months → LTCG at 12.5% on gains above ₹1.25 lakh/year exemption. Held under 12 months → STCG at 20%. Example: ₹10L invested, sold at ₹15L after 2 years. Gain = ₹5L. Taxable LTCG = ₹5L - ₹1.25L = ₹3.75L. Tax = ₹3.75L × 12.5% = ₹46,875. Effective tax on total gain: 9.4%.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Debt fund lumpsum:</strong> All gains (regardless of holding period) taxed at your income tax slab rate since April 2023. No indexation benefit. ₹10L invested, sold at ₹12L after 3 years. Gain = ₹2L. Tax at 30% slab = ₹62,400. This makes debt mutual fund lumpsum tax-inefficient for high tax bracket investors — FD gives similar treatment with less risk.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Tax harvesting strategy:</strong> If your lumpsum has grown significantly, redeem ₹1.25 lakh of LTCG each year in March and reinvest immediately. This crystalizes gains within the tax-free limit. Over 10 years, you can harvest ₹12.5 lakh of gains tax-free — saving ₹1.56 lakh in taxes at 12.5% rate. Simple but highly effective for large lumpsum investments.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Timing of sale matters:</strong> If you plan to sell a large lumpsum position, split the redemption across two financial years (sell half in March, half in April). Each year gets its own ₹1.25L LTCG exemption. On ₹5L total gains: selling all in one year → tax on ₹3.75L = ₹46,875. Splitting across 2 years → tax on ₹1.25L + ₹1.25L = ₹31,250. Saved ₹15,625 just by timing the sale across the financial year boundary.</p>

      <SectionHeading icon="📊">Asset allocation for lumpsum — how to split your money</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>₹5-10 lakh lumpsum:</strong> Keep it simple — 100% in a single Nifty 50 index fund (direct plan). At this amount, over-diversifying across 5 funds creates complexity without benefit. One large-cap index fund gives you exposure to India&apos;s top 50 companies automatically. Hold for 7+ years.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>₹10-25 lakh lumpsum:</strong> Split into two funds — 70% large-cap index (Nifty 50) + 30% mid-cap index (Nifty Midcap 150). This adds growth potential from mid-caps while keeping the core stable. If you&apos;re risk-averse, go 80% large-cap + 20% short-duration debt fund instead.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>₹25-50 lakh lumpsum:</strong> Three-fund portfolio: 50% Nifty 50 + 25% Nifty Midcap 150 + 25% debt (corporate bond or gilt fund). This gives growth + stability. If you&apos;re under 35 and can tolerate volatility, increase equity to 80%. If you&apos;re over 50, increase debt to 40-50%.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>₹50 lakh+ lumpsum:</strong> Add international diversification: 60% Indian equity (Nifty 50 + Midcap) + 15% US equity (Nasdaq 100 or S&amp;P 500 fund) + 25% Indian debt. International exposure protects against India-specific risks (currency, policy changes) and taps into the world&apos;s largest economy&apos;s growth. Motilal Oswal Nasdaq 100 Fund and ICICI S&amp;P 500 Index Fund are popular options.</p>

      <SectionHeading icon="🔄">STP strategy — the smart way to deploy lumpsum</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">If you&apos;re nervous about investing a large sum at once (especially when markets are near highs), STP (Systematic Transfer Plan) is your solution. Here&apos;s how it works step by step:</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Step 1:</strong> Invest the entire lumpsum in a liquid fund (e.g., HDFC Liquid Fund Direct, SBI Liquid Fund Direct). These give ~6-7% annualized with near-zero risk. Your money starts earning from day one.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Step 2:</strong> Set up a monthly STP from the liquid fund to your target equity fund. For ₹12 lakh, transfer ₹2 lakh/month over 6 months or ₹1 lakh/month over 12 months. This gives you rupee cost averaging — you buy at different prices each month, reducing timing risk.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Step 3:</strong> After the STP completes, your money is fully deployed in equity. Continue holding for 7+ years. The liquid fund portion you haven&apos;t transferred yet earns ~6% instead of 3.5% in a savings account — so you&apos;re earning more even during the transfer period.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>When to skip STP and go full lumpsum:</strong> If Nifty PE ratio is below 18 (market is cheap), if Nifty has corrected 20%+ from recent high, or if you&apos;re investing in debt/liquid funds where timing doesn&apos;t matter. In these situations, deploying the full amount immediately captures the undervaluation.</p>

      <SectionHeading icon="💡">Lumpsum for specific goals</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Emergency fund parking:</strong> Got a lumpsum but need emergency access? Split: 3 months&apos; expenses in savings account + rest in a liquid fund. Liquid fund gives 6-7% vs savings account&apos;s 3-4%, and withdrawals hit your bank in 1-2 business days. No exit load after 7 days in most liquid funds.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>House down payment (3-5 years):</strong> Don&apos;t put this in equity — too risky for a 3-5 year goal. Use: 50% in a corporate bond fund (7-8% expected return) + 50% in a short-duration fund (6-7%). Or keep it simple with a bank FD at 7%. Capital preservation matters more than return maximization for down payments.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Child&apos;s education (10-15 years away):</strong> Ideal for aggressive equity lumpsum. ₹10 lakh in a Nifty 50 index fund for 15 years at 12% = ₹54.7 lakh. Add mid-cap allocation for higher growth potential. Start shifting 20% to debt 3 years before the need date. This is long enough for equity to deliver and compound significantly.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Retirement top-up (10+ years to retirement):</strong> If you receive a windfall (property sale, inheritance, bonus) with 10+ years to retirement, deploying as lumpsum in equity is optimal. ₹20 lakh at 12% for 15 years = ₹1.09 crore. This single investment could fund 4-5 years of retirement expenses. Add to your existing NPS and EPF corpus for comprehensive coverage.</p>

      <SectionHeading icon="⚡">Lumpsum in debt instruments — when equity isn&apos;t right</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Liquid funds (for 1-90 days):</strong> Park lumpsum temporarily while deciding where to invest. Returns ~6-7% annualized. No exit load after 7 days. Near-zero volatility. Better than savings account for any amount sitting idle beyond a week. Ideal for emergency fund, bonus parking, or pre-STP staging.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Short-duration debt funds (for 1-3 years):</strong> For goals like car purchase, vacation, or wedding in 1-3 years. Expected return 6.5-8%. Low volatility compared to equity but higher than FD. Post April 2023, gains are taxed at slab rate — so the tax advantage over FD is minimal. Choose based on convenience and liquidity needs.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Gilt funds (for interest rate play):</strong> If you believe RBI will cut rates in the next 1-2 years, lumpsum in a gilt/government bond fund can give 10-12% returns as bond prices rise when rates fall. However, if rates rise instead, you could see 2-4% negative returns. This is a tactical bet, not a core holding. Only for investors who understand the rate cycle.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Arbitrage funds (for tax efficiency):</strong> Arbitrage funds exploit price differences between cash and futures markets. Returns are similar to liquid funds (6-7%) but taxed as equity — LTCG of 12.5% after 12 months vs slab rate for debt funds. For investors in the 30% bracket holding for 12+ months, arbitrage funds give higher post-tax returns than liquid or debt funds on lumpsum investments.</p>

<SectionHeading icon="❓">Frequently asked questions</SectionHeading>
      {faqs.map((f: any) => <FAQ key={f.question} question={f.question} answer={f.answer} />)}
      <div className="mt-10 flex flex-wrap gap-2">
        <a href="/calculator/sip-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">SIP Calculator →</a>
        <a href="/calculator/fd-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">FD Calculator →</a>
        <a href="/calculator/ppf-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">PPF Calculator →</a>
        <a href="/calculator/nps-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">NPS Calculator →</a>
      </div>
    </div>
  );
}
