import type { Metadata } from "next";
import { SipCalc } from "@/components/calculators/sip-calc";
import { JsonLd, faqSchema, breadcrumbSchema } from "@/components/json-ld";
import { Breadcrumb, SectionHeading, FAQ } from "@/components/ui";

export const metadata: Metadata = {
  title: "SIP Calculator 2026 — Calculate Mutual Fund SIP Returns Online",
  description: "Free SIP calculator for 2026. Enter monthly SIP amount, expected returns, and tenure to calculate wealth accumulation. Covers step-up SIP, SIP vs lumpsum, and best SIP strategies for long-term goals.",
  alternates: { canonical: "https://knowledgekendra.com/calculator/sip-calculator" },
};

const faqs = [
  { question: "What is SIP?", answer: "SIP (Systematic Investment Plan) is a method of investing a fixed amount regularly (monthly/quarterly) in mutual funds. Instead of investing a lumpsum, you invest small amounts at regular intervals. SIP benefits from rupee cost averaging — you buy more units when prices are low and fewer when high, reducing the average cost over time. Minimum SIP in most funds is ₹500/month." },
  { question: "What returns can I expect from SIP?", answer: "Historical returns from equity mutual fund SIPs: Large-cap: 10-13% over 10+ years. Multi-cap/Flexi-cap: 12-15%. Small-cap: 14-18% (with higher volatility). Debt fund SIPs: 6-8%. These are historical averages — actual returns vary by market conditions. SIP works best over 7+ years where equity market cycles average out." },
  { question: "Is SIP better than FD?", answer: "For long-term (7+ years): SIP in equity funds has historically beaten FDs by a wide margin. ₹10,000/month SIP for 15 years at 12% = ₹50 lakh. Same in FD at 7% (post-tax ~5%) = ₹27 lakh. However, SIP returns are not guaranteed and can be negative over short periods. For goals under 3 years, FD is safer. For 5+ years, equity SIP has better risk-adjusted returns." },
  { question: "Can I stop or pause SIP?", answer: "Yes. SIP can be paused or stopped anytime without penalty. Most AMCs allow SIP pause for 1-3 months through the app or website. To stop permanently, submit a cancellation request 15 days before the next SIP date. Your existing invested amount stays in the fund — only future installments stop. No exit load if you've held units for 1+ year (in most equity funds)." },
  { question: "What is step-up SIP?", answer: "Step-up (or top-up) SIP increases your monthly amount annually — typically by 10-25%. If you start with ₹10,000/month and step up 10% yearly: Year 1 = ₹10K, Year 2 = ₹11K, Year 3 = ₹12.1K. This aligns SIP growth with your salary growth. Step-up SIP at 10% annual increase gives approximately 45-50% more corpus than flat SIP over 15 years." },
  { question: "When is the best date for SIP?", answer: "There's no statistically significant 'best date' for SIP. Studies show that the date of SIP (1st, 5th, 15th, 25th) makes less than 0.5% difference in long-term returns. Choose a date right after your salary credit for consistency. What matters more: starting early and continuing consistently, not optimizing the date. Regularity beats timing." },
  { question: "What is SIP vs STP vs SWP?", answer: "SIP: Invest fixed amount from bank to mutual fund monthly (accumulation phase). STP: Transfer fixed amount from one mutual fund to another (e.g., debt to equity). SWP: Withdraw fixed amount from mutual fund monthly (distribution phase — used in retirement). Life cycle: SIP for 25 years → build corpus → SWP for retirement income." },
  { question: "How is SIP taxed?", answer: "Equity fund SIP: Each SIP installment starts its own holding period. Units held over 12 months: LTCG at 12.5% above ₹1.25 lakh/year exemption. Units held under 12 months: STCG at 20%. Debt fund SIP: All gains taxed at slab rate regardless of holding period (since April 2023). ELSS SIP: 3-year lock-in, then LTCG rules apply. Tax is only on redemption — unrealized gains are not taxed." },
  { question: "Can I do SIP in direct plans?", answer: "Yes, and you should. Direct plans have 0.5-1.5% lower expense ratio than regular plans because there's no distributor commission. Over 15 years, this fee difference compounds to 15-25% more corpus. Set up direct SIP through AMC websites, Zerodha Coin, Groww, or Kuvera. If using a distributor (bank, advisor), you're in regular plan paying higher fees." },
  { question: "How much SIP should I start with?", answer: "Rule of thumb: invest 20-30% of your take-home salary in SIPs across 2-3 funds. For a ₹50,000 salary: ₹10,000-15,000/month SIP. Start with what you can afford — even ₹500/month — and increase via step-up SIP annually. The most important factor is starting early. ₹5,000/month from age 25 beats ₹15,000/month from age 35 by age 60." },
  { question: "What happens if I miss an SIP installment?", answer: "Nothing serious. If your bank account doesn't have sufficient balance on the SIP date, the installment is skipped. No penalty, no interest, no impact on existing investments. However, if 3 consecutive installments fail, most AMCs automatically cancel the SIP mandate. You'll need to set up a new SIP. Keep sufficient balance on SIP dates." },
  { question: "SIP in ELSS vs PPF — which is better for 80C?", answer: "ELSS: 12-15% expected returns, 3-year lock-in (shortest among 80C), market-linked risk, LTCG taxable above ₹1.25L. PPF: 7.1% guaranteed, 15-year lock-in, zero risk, fully tax-free maturity. Best strategy: Use both. ELSS for equity growth + shorter lock-in, PPF for guaranteed base + tax-free compounding. Allocate 60% to ELSS, 40% to PPF if you're under 40." },
  { question: "What is the power of compounding in SIP?", answer: "₹10,000/month SIP at 12% return: After 10 years = ₹23.2 lakh (invested ₹12 lakh). After 20 years = ₹99.9 lakh (invested ₹24 lakh). After 30 years = ₹3.5 crore (invested ₹36 lakh). The last 10 years added ₹2.5 crore — more than the first 20 years combined. This is why starting early is the single most important investment decision." },
  { question: "Should I stop SIP when markets crash?", answer: "No — this is the worst thing you can do. Market crashes are when SIP works best because you buy more units at lower prices (rupee cost averaging). Investors who continued SIPs during the 2020 crash saw 80-100% gains within 18 months. SIP is designed to work through market cycles. If anything, increase your SIP during crashes — that's when future returns are highest." },
];

export default function Page() {
  return (
    <div className="max-w-[860px] mx-auto px-5 py-6">
      <JsonLd data={breadcrumbSchema([{ name: "Home", url: "https://knowledgekendra.com" }, { name: "Calculators", url: "https://knowledgekendra.com/calculator" }, { name: "SIP Calculator 2026", url: "https://knowledgekendra.com/calculator/sip-calculator" }])} />
      <JsonLd data={faqSchema(faqs)} />
      <JsonLd data={{ "@context": "https://schema.org", "@type": "WebApplication", name: "SIP Calculator 2026", description: "Free SIP calculator — calculate mutual fund SIP returns over time.", applicationCategory: "FinanceApplication", operatingSystem: "Web", offers: { "@type": "Offer", price: "0", priceCurrency: "INR" } }} />
      <Breadcrumb items={[{ label: "Home", href: "/" }, { label: "Calculators", href: "/calculator" }, { label: "SIP Calculator 2026" }]} />
      <h1 className="text-2xl font-extrabold tracking-tight text-text mb-2">SIP Calculator 2026</h1>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-6">Calculate how your monthly SIP grows over time. Enter monthly investment, expected annual return, and tenure. Understand the power of compounding and rupee cost averaging in mutual fund investing.</p>
      <SipCalc />

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #2563EB", backgroundColor: "#DBEAFE" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2"><span>💡</span><span>The power of starting early</span></p>
        <p className="text-sm text-text-secondary leading-relaxed">₹5,000/month SIP from <strong>age 25 to 60 at 12%</strong> = ₹3.2 crore. The same ₹5,000/month from <strong>age 35 to 60</strong> = ₹95 lakh. Starting 10 years earlier with the SAME monthly amount gives you <strong>3.4× more wealth</strong>. The extra decade isn&apos;t 40% more time — it&apos;s 240% more money.</p>
      </div>

      <SectionHeading icon="📖">How SIP works — the basics</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">SIP (Systematic Investment Plan) is not a product — it&apos;s a method. You instruct your mutual fund to debit a fixed amount from your bank account every month and invest it in a chosen mutual fund scheme. Each month, you buy units at whatever the current NAV (Net Asset Value) is. When NAV is high, you get fewer units. When NAV is low, you get more units.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">This automatic buy-low-buy-high mechanism is called <strong>rupee cost averaging</strong>. Over time, your average cost per unit tends to be lower than the average NAV — giving you a built-in advantage. This is why SIP outperforms most investors who try to time the market. You don&apos;t need to predict markets — the SIP structure does the work.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">SIPs work best over long periods (7+ years) in equity mutual funds. Over short periods (1-3 years), equity SIPs can give negative returns due to market volatility. The longer you stay invested, the more likely you are to earn positive, market-beating returns. Historical data shows that no 10-year equity SIP in India has ever given negative returns.</p>

      <SectionHeading icon="📊">SIP growth over time — real numbers</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>₹10,000/month at 12% return:</strong> After 5 years: ₹8.2 lakh (invested ₹6L). After 10 years: ₹23.2 lakh (invested ₹12L). After 15 years: ₹50 lakh (invested ₹18L). After 20 years: ₹1 crore (invested ₹24L). After 25 years: ₹1.89 crore (invested ₹30L). Notice how the last 5 years added ₹89 lakh — almost as much as the first 20 years.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Step-up SIP (₹10K start, 10% annual increase):</strong> After 15 years: ₹79.5 lakh (vs ₹50L flat). After 20 years: ₹1.73 crore (vs ₹1 crore flat). Step-up SIP gives 73% more corpus at year 20 — simply by increasing your SIP by 10% each year along with your salary growth. Most apps (Groww, Zerodha Coin) support automatic step-up.</p>

      <blockquote className="my-6 border-l-4 border-accent pl-5 py-2">
        <p className="text-lg font-semibold text-text leading-snug italic">No 10-year SIP in Indian equity mutual funds has ever given negative returns. Not during 2008 crash, not during COVID. Time in the market beats timing the market — every time.</p>
      </blockquote>

      <SectionHeading icon="🎯">How to choose mutual funds for SIP</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>For beginners:</strong> Start with one large-cap index fund (Nifty 50 or Sensex). Expense ratio below 0.5%. No need to pick active funds — most fail to beat the index over 10 years. UTI Nifty 50 Index Fund Direct, HDFC Nifty 50 Index Fund Direct are popular choices.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>For intermediate investors:</strong> Two-fund portfolio: 70% large-cap index fund + 30% mid-cap index fund (Nifty Midcap 150). This gives broad market exposure with mid-cap growth kicker. Total monthly SIP split across both in 70:30 ratio.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>For aggressive investors:</strong> Three-fund portfolio: 50% Nifty 50 + 25% Nifty Midcap 150 + 25% Nifty Smallcap 250. Higher risk, higher potential returns. Only for investors who can stomach 30-40% drops without panicking. Minimum 10-year horizon.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Always choose Direct plans</strong> (not Regular). Direct plans have 0.5-1.5% lower expense ratio — no distributor commission. Over 20 years, this fee difference adds 15-25% more to your corpus. If your advisor put you in Regular plans, switch to Direct via the AMC website or platforms like Kuvera, Zerodha Coin.</p>

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #DC2626", backgroundColor: "#FEE2E2" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2"><span>⚠️</span><span>SIP common mistakes</span></p>
        <p className="text-sm text-text-secondary leading-relaxed"><strong>1.</strong> Stopping SIP during market crashes (worst time to stop — best time to continue). <strong>2.</strong> Too many funds — 5+ funds creates overlap and complexity with no diversification benefit. <strong>3.</strong> Choosing funds by recent 1-year return (recency bias). <strong>4.</strong> Ignoring expense ratio — 2% expense = 40% less wealth over 25 years. <strong>5.</strong> Not using Direct plans — paying commissions that compound against you for decades.</p>
      </div>

      <SectionHeading icon="💰">SIP taxation explained</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Each SIP installment is treated as a separate purchase for tax purposes. When you redeem units, the FIFO (First In, First Out) method applies — oldest units are sold first.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Equity funds (held over 12 months):</strong> LTCG taxed at 12.5% on gains above ₹1.25 lakh/year. Below ₹1.25L: tax-free. Strategy: redeem ₹1.25L gains every year to harvest the exemption.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Equity funds (held under 12 months):</strong> STCG taxed at 20%. Avoid selling equity fund SIPs within 12 months of each installment to avoid STCG.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Debt funds:</strong> All gains (short and long term) are taxed at your slab rate — no special treatment. This changed in April 2023, making debt funds less tax-efficient than before. For debt allocation, consider PPF or EPF instead.</p>

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #EA580C", backgroundColor: "#FFF7ED" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2"><span>🎯</span><span>The ideal SIP strategy</span></p>
        <p className="text-sm text-text-secondary leading-relaxed"><strong>Step 1:</strong> Start with ₹500-5,000/month in a Nifty 50 index fund (Direct plan). <strong>Step 2:</strong> Set up annual step-up of 10%. <strong>Step 3:</strong> Add mid-cap index fund when SIP exceeds ₹10K/month. <strong>Step 4:</strong> Never stop during crashes. <strong>Step 5:</strong> Harvest ₹1.25L LTCG exemption every March. <strong>Step 6:</strong> Switch to SWP at retirement for monthly income.</p>
      </div>

      <SectionHeading icon="📚">Official source</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">AMFI (Association of Mutual Funds in India): <a href="https://www.amfiindia.com" target="_blank" rel="noopener" className="text-accent hover:underline">amfiindia.com</a>. NAV lookup and fund comparison: <a href="https://www.valueresearchonline.com" target="_blank" rel="noopener" className="text-accent hover:underline">Value Research</a>. SEBI mutual fund regulations: <a href="https://www.sebi.gov.in" target="_blank" rel="noopener" className="text-accent hover:underline">sebi.gov.in</a>.</p>
      <p className="text-xs text-text-muted mt-6 mb-8 italic">Last reviewed: April 2026 • Mutual fund investments are subject to market risks. Past performance doesn&apos;t guarantee future returns. This is for informational purposes only.</p>

      <SectionHeading icon="📈">SIP vs lumpsum — which is better?</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Mathematically, lumpsum investing beats SIP about 65-70% of the time — because markets trend upward over long periods, and putting all money in early gives it more time to compound. However, most people don&apos;t have a lumpsum to invest. SIP works with your monthly salary, requires no market timing, and reduces the psychological stress of seeing a large sum fluctuate.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>When SIP is better:</strong> Regular salary income, volatile or overvalued markets, emotional investors who panic during drops, building the investing habit. <strong>When lumpsum is better:</strong> Received a bonus/inheritance, markets have just crashed 20%+, you have idle cash in a savings account earning 3%. <strong>Optimal:</strong> Do both — regular monthly SIP plus lumpsum top-ups during market dips.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">If you receive a large sum (bonus, property sale, inheritance) and want to invest in equity, consider an STP (Systematic Transfer Plan). Park the lumpsum in a liquid fund and set up automatic monthly transfers to an equity fund over 6-12 months. This gives rupee cost averaging on the lumpsum while earning ~6% in the liquid fund during the transfer period.</p>

      <SectionHeading icon="🔄">SIP for different life goals</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Emergency fund (0-1 year horizon):</strong> Don&apos;t use equity SIP. Keep 6 months&apos; expenses in a liquid fund or sweep-in FD. Zero market risk needed here.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Car/vacation (2-3 years):</strong> Short-duration debt fund SIP or recurring deposit. Too short for equity risk. Expected return: 6-7%.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Home down payment (5-7 years):</strong> Balanced allocation — 60% equity index fund + 40% debt fund. SIP into both. Gradually shift to 100% debt as you approach the target date. Expected return: 8-10%.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Children&apos;s education (10-15 years):</strong> Aggressive equity SIP — 80% equity (index or flexi-cap) + 20% debt. Start shifting to debt 3 years before the goal. Expected return: 11-13%. ₹10,000/month SIP for 15 years at 12% = ₹50 lakh — enough for most engineering/medical college fees.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Retirement (20-30 years):</strong> Maximum equity exposure — 80-100% equity index funds. Time horizon is long enough to ride out any market cycle. Step-up SIP by 10% annually. Target: 25-30× annual expenses as retirement corpus. Use our <a href="/calculator/nps-calculator" className="text-accent hover:underline">NPS Calculator</a> alongside to plan pension component.</p>

      <SectionHeading icon="🏦">Best SIP platforms in India 2026</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Zerodha Coin:</strong> Direct plans only, ₹0 commission, seamless Demat integration, good research tools. Best for existing Zerodha users. Limitation: mutual fund units held in Demat form (some people prefer non-Demat for flexibility).</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Groww:</strong> User-friendly interface, great for beginners, direct plans, ₹0 commission. Non-Demat mode available. Good mobile app with goal-based SIP planning. Largest mutual fund platform by user count in India.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Kuvera:</strong> Free direct plan platform with excellent goal planning tools, family portfolio tracking, and tax harvesting features. No commissions. Fewer users than Groww/Zerodha but superior planning features for serious investors. Also offers US stock investing.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>AMC websites (direct):</strong> You can set up SIP directly on AMC websites (SBI MF, HDFC MF, Axis MF) for the cheapest direct plans with zero platform dependency. Downside: managing SIPs across multiple AMC websites is inconvenient. Best if you invest in only 1-2 AMC&apos;s funds.</p>

      <SectionHeading icon="⚡">SIP red flags — when to exit a fund</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Stop SIP and consider switching fund in these situations: <strong>(1)</strong> Fund consistently underperforms its benchmark index for 2+ years — if Nifty 50 gave 12% and your large-cap fund gave 8%, the fund manager is destroying value. <strong>(2)</strong> Fund manager change — the star manager who built the track record has left. Give the new manager 1-2 quarters, then evaluate. <strong>(3)</strong> Fund category change — your flexi-cap fund is now behaving like a mid-cap fund, changing your risk profile.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>When NOT to stop SIP:</strong> Market has dropped 20% (this is SIP&apos;s best friend — you&apos;re buying cheap units). Your fund dropped but so did the entire market/benchmark (that&apos;s market risk, not fund risk). You heard a scary news headline about the economy — noise is not a reason to exit. You saw a YouTube video saying &quot;this fund is bad&quot; — do your own analysis using 3-5 year rolling returns vs benchmark.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>How to evaluate SIP fund performance:</strong> Compare 3-year and 5-year rolling returns against the fund&apos;s benchmark index. If the fund beats the benchmark in 60%+ of 3-year rolling periods, it&apos;s a good actively managed fund. If it doesn&apos;t, switch to the benchmark index fund instead — you&apos;ll get market returns at a fraction of the fee (0.1% vs 1.5%). Index funds don&apos;t have fund manager risk.</p>

      <SectionHeading icon="🎓">SIP myths debunked</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Myth: &quot;SIP guarantees returns.&quot;</strong> Reality: SIP guarantees discipline, not returns. Equity SIPs can give negative returns over 1-3 year periods. What SIP does guarantee: you invest regularly regardless of market conditions, and rupee cost averaging reduces your average purchase price over time. Over 7+ years, equity SIPs have historically given positive returns — but this is historical, not a guarantee.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Myth: &quot;More funds = more diversification.&quot;</strong> Reality: 5 large-cap funds invest in the same Nifty 50 stocks. Having 5 funds means you own the same 50 companies through 5 different vehicles — zero additional diversification, but 5× the complexity. Two-three funds (large-cap index + mid-cap index + maybe international) gives you true diversification across company sizes and geographies.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Myth: &quot;Stop SIP when markets are high.&quot;</strong> Reality: Nobody can consistently identify market tops. The Nifty has hit &quot;all-time high&quot; over 200 times since 2014 — and it&apos;s still gone up. Stopping SIP at perceived highs means missing out on further upside. The cost of being wrong (missing a rally) far exceeds the benefit of being right (avoiding a dip). Continue SIP regardless of market level.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Myth: &quot;1-year top returns = best fund.&quot;</strong> Reality: Last year&apos;s winner is often this year&apos;s underperformer. Choosing funds by 1-year return is like driving by looking in the rearview mirror. Look at 5-year and 10-year rolling returns vs benchmark instead. Consistency matters more than peaks. A fund that beats its benchmark in 7 out of 10 years is better than one that tops the charts once and underperforms for 4 years.</p>

      <SectionHeading icon="❓">Frequently asked questions</SectionHeading>
      {faqs.map((f: any) => <FAQ key={f.question} question={f.question} answer={f.answer} />)}
      <div className="mt-10 flex flex-wrap gap-2">
        <a href="/calculator/lumpsum-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">Lumpsum Calculator →</a>
        <a href="/calculator/ppf-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">PPF Calculator →</a>
        <a href="/calculator/fd-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">FD Calculator →</a>
        <a href="/calculator/nps-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">NPS Calculator →</a>
      </div>
    </div>
  );
}
