import type { MetadataRoute } from "next";

export const dynamic = "force-static";

// Old domain URLs — 61 slugs from previous site owner (Sep 2024 – Mar 2025)
// All return 404/308 but Bing keeps crawling them, wasting crawl budget
const OLD_DOMAIN_SLUGS = [
  "/100-heartwarming-diwali-wishes",
  "/9-feb-day-in-valentine-week",
  "/about-us-knowledge-kendra",
  "/basics-of-the-indian-stock-market",
  "/best-books-to-read-in-2025",
  "/best-job-searching-apps",
  "/best-side-hustles-to-earn-money-in-2025",
  "/best-stocks-to-buy-today-for-short-term",
  "/chhath-puja-2024-a-journey-of-devotion-and-gratitude",
  "/contact-us",
  "/diwali-the-festival-of-lights",
  "/every-home-should-have-in-a-first-aid-kit",
  "/exercises-to-improve-concentration",
  "/fastest-ball-in-cricket",
  "/gukesh",
  "/how-to-create-a-study-schedule",
  "/how-to-overcome-masturbation",
  "/how-to-prepare-for-a-job-interview",
  "/how-to-stay-motivated-throughout-school-year",
  "/how-to-stop-hair-fall-in-winter",
  "/human-metapneumovirus-hmpv",
  "/impact-of-social-media-advantage-disadvantage",
  "/india-pakistan-match-2025-the-ultimate-rivalry",
  "/india-vs-new-zealand-champions-trophy-2025-final-showdown",
  "/job-market-trends-for-2025",
  "/kawasaki-disease",
  "/luxurious-beachside-villas-in-goa",
  "/maharashtra-cabinet-expansion-39-ministers",
  "/most-profitable-business-startups",
  "/mpox-the-viral-disease-symptomstransmission-and-prevention",
  "/nancy-pelosi-hospitalized-what-happened-during-her-trip-to-luxembourg",
  "/new-year-new-goals-how-to-set-resolutions-2025",
  "/new-year-resolutions-2025",
  "/nitish-kumar-reddy-career-stats",
  "/pakistan-gold-reserves",
  "/passive-income-ideas",
  "/rajinikanth-return-in-jailer-2-sequel",
  "/rangoli-design-for-diwali-2024-vibrant-patterns-to-try",
  "/remembering-bhagat-singh-the-rebel-who-dared-to-dream",
  "/sequel-to-pushpa-2-the-rule",
  "/squid-game-season-2",
  "/tabla-maestro-ustad-zakir-hussain-passes-away-at-73-in-the-us",
  "/the-future-of-ai-transforming-our-world",
  "/the-impact-of-social-media-on-students-life",
  "/the-impact-of-social-media-on-students-life-and-studies",
  "/the-journey-of-ratan-tata-tr",
  "/the-life-of-mahatma-gandhi-a-detailed-biography",
  "/the-life-of-mahatma-gandhi-biography",
  "/the-retirement-of-vikrant-massey",
  "/top-10-builders-in-goa-real-estate-developer",
  "/top-10-must-visit-places-in-india-with-travel-guide-description-highlights-location-and-how-to-reach",
  "/top-5-triceps-workouts-how-to-do-benefits-and-tips",
  "/top-earning-ideas-for-students-in-2025",
  "/top-government-jobs-you-must-consider-in-2025",
  "/valentine-week-2025-7-days-of-love",
  "/virat-kohli-goat-of-the-cricket",
  "/what-is-insurance-types-of-insurance",
  "/who-is-priya-saroj",
  "/who-is-zakir-hussain",
  "/who-was-manmohan-singh",
  "/yuzvendra-chahal-and-dhanashree-verma-divorce",
];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: OLD_DOMAIN_SLUGS,
      },
      { userAgent: "GPTBot", allow: "/" },
      { userAgent: "ChatGPT-User", allow: "/" },
      { userAgent: "ClaudeBot", allow: "/" },
      { userAgent: "PerplexityBot", allow: "/" },
      { userAgent: "Applebot-Extended", allow: "/" },
      { userAgent: "Google-Extended", allow: "/" },
    ],
    sitemap: "https://knowledgekendra.com/sitemap.xml",
  };
}
