import type { Metadata } from "next";
import { FdCalc } from "@/components/calculators/fd-calc";
import { JsonLd, faqSchema, breadcrumbSchema } from "@/components/json-ld";
import { Breadcrumb, SectionHeading, FAQ } from "@/components/ui";

export const metadata: Metadata = {
  title: "FD Calculator 2026 — Fixed Deposit Maturity & Interest Calculator",
  description: "Free FD calculator for 2026. Enter deposit amount, interest rate, and tenure to calculate maturity amount. Covers SBI, HDFC, Post Office FD rates, quarterly compounding, and TDS rules on FD interest.",
  alternates: { canonical: "https://knowledgekendra.com/calculator/fd-calculator" },
};

const faqs = [
  { question: "What is the FD interest rate in 2026?", answer: "FD rates vary by bank and tenure. As of April 2026, typical rates for general public: SBI 6.5-7.1%, HDFC 6.6-7.25%, ICICI 6.5-7.2%, Post Office 6.9-7.5%. Senior citizens get 0.25-0.75% extra. Highest rates are usually for 1-2 year tenure. Small finance banks (AU, Equitas) offer 7.5-8.5% but with slightly higher risk. Always compare rates across banks before investing." },
  { question: "How is FD interest calculated?", answer: "Most banks use quarterly compounding. Formula: Maturity = Principal × (1 + r/4)^(4×t), where r = annual rate and t = years. For simple interest FDs (some corporate FDs): Interest = P × r × t. Monthly/quarterly interest payout FDs use simple interest at a slightly lower rate than cumulative FDs. Cumulative FDs (interest reinvested) always give higher returns." },
  { question: "Is FD interest taxable?", answer: "Yes, FD interest is fully taxable at your income tax slab rate. Banks deduct TDS at 10% if interest exceeds ₹40,000/year (₹50,000 for senior citizens). If your total income is below the taxable limit, submit Form 15G (under 60) or Form 15H (60+) to avoid TDS deduction. Interest is taxable in the year it accrues — even if the FD hasn't matured yet." },
  { question: "What is the difference between cumulative and non-cumulative FD?", answer: "Cumulative FD: interest is reinvested and compounded quarterly — you get the principal + all interest at maturity. Best for wealth building. Non-cumulative FD: interest is paid out monthly, quarterly, or annually — you receive regular income but final maturity amount is lower. Non-cumulative rates are slightly lower than cumulative rates at most banks." },
  { question: "Can I break an FD before maturity?", answer: "Yes, premature withdrawal is allowed at most banks with a 0.5-1% penalty on the applicable rate. If your 7% FD is broken after 6 months, you get the 6-month rate (say 5.5%) minus 1% penalty = 4.5%. Some banks offer no-penalty FD break for specific tenures. Tax-saving FDs (5-year lock-in) cannot be broken prematurely under any circumstances." },
  { question: "What is a tax-saving FD?", answer: "A 5-year FD with lock-in that qualifies for Section 80C deduction (up to ₹1.5 lakh/year). You cannot withdraw before 5 years — no premature closure, no loan against it. Interest is still fully taxable (unlike PPF which is tax-free). Tax-saving FD rates are slightly lower than regular FDs. Available at most banks. Consider ELSS mutual funds for 80C — they offer higher returns with shorter 3-year lock-in." },
  { question: "Which is better — FD or PPF?", answer: "PPF wins on: tax-free returns (FD interest is taxable), higher effective return (PPF 7.1% tax-free ≈ 10.2% pre-tax vs FD 7% pre-tax ≈ 4.9% post-tax at 30% slab), EEE tax status. FD wins on: flexibility (break anytime, choose tenure from 7 days to 10 years), higher rates at some small finance banks (8%+), and no minimum lock-in. For long-term: PPF. For short-term: FD." },
  { question: "Are FDs safe? What if the bank fails?", answer: "FDs in scheduled commercial banks are insured by DICGC (Deposit Insurance and Credit Guarantee Corporation) up to ₹5 lakh per depositor per bank. This covers principal + interest. If you have more than ₹5 lakh, spread across multiple banks. Post office FDs are backed by the government — effectively zero risk. Small finance bank FDs carry slightly more risk but still have DICGC coverage." },
  { question: "What is a sweep-in FD?", answer: "Sweep-in (or flexi) FD automatically converts surplus savings account balance into FD and breaks it in reverse order when you need cash. You earn FD rates on idle money without manual FD creation. Most banks offer this with a minimum threshold (e.g., sweep anything above ₹25,000 into FD). Interest earned is taxable like regular FD. Good for maintaining emergency fund with higher returns." },
  { question: "Should senior citizens choose FD or SCSS?", answer: "Senior Citizens Savings Scheme (SCSS) offers 8.2% — higher than most bank FDs. SCSS is limited to ₹30 lakh, has a 5-year lock-in, and interest is taxable. But senior citizens get TDS exemption up to ₹50,000/year on SCSS/FD interest combined. Optimal: Put ₹30L in SCSS (8.2%), remaining in senior citizen FD (7.5%+ with 0.5% extra for seniors)." },
  { question: "How often is FD interest compounded?", answer: "Most banks compound quarterly (4 times/year). SBI, HDFC, ICICI, Axis — all use quarterly compounding. Some small finance banks compound monthly, giving slightly higher effective yield. Post office FDs compound annually. For a ₹10 lakh FD at 7%: quarterly compounding gives ₹7,186 more interest over 5 years compared to annual compounding." },
  { question: "Can NRI open FD in India?", answer: "Yes. NRIs can open NRE FD (rupee-denominated, fully repatriable, interest is tax-free in India) or NRO FD (for income earned in India, partially repatriable, interest taxable at 30% + cess with TDS). NRE FD rates are usually lower than domestic FD rates by 0.5-1%. FCNR FD is in foreign currency with no exchange risk." },
  { question: "What is the FD for minors?", answer: "Parents can open FD in the name of a minor child. Interest earned is clubbed with the parent's income (whoever has higher income) until the child turns 18. Section 10(32) provides ₹1,500/year exemption per child for clubbed income. After 18, the child can independently manage the FD and interest is taxed in their own name." },
  { question: "Is it better to have one large FD or multiple small FDs?", answer: "Multiple small FDs are better for two reasons: (1) If you need money, you break only one FD — the rest continue earning interest without penalty. (2) DICGC insurance covers ₹5 lakh per bank — spreading across banks protects larger amounts. Strategy: Create a FD ladder with different maturity dates (1yr, 2yr, 3yr, 5yr) for regular liquidity." },
];

export default function Page() {
  return (
    <div className="max-w-[860px] mx-auto px-5 py-6">
      <JsonLd data={breadcrumbSchema([{ name: "Home", url: "https://knowledgekendra.com" }, { name: "Calculators", url: "https://knowledgekendra.com/calculator" }, { name: "FD Calculator 2026", url: "https://knowledgekendra.com/calculator/fd-calculator" }])} />
      <JsonLd data={faqSchema(faqs)} />
      <JsonLd data={{ "@context": "https://schema.org", "@type": "WebApplication", name: "FD Calculator 2026", description: "Free FD calculator — calculate maturity amount and interest on fixed deposits.", applicationCategory: "FinanceApplication", operatingSystem: "Web", offers: { "@type": "Offer", price: "0", priceCurrency: "INR" } }} />
      <Breadcrumb items={[{ label: "Home", href: "/" }, { label: "Calculators", href: "/calculator" }, { label: "FD Calculator 2026" }]} />
      <h1 className="text-2xl font-extrabold tracking-tight text-text mb-2">FD Calculator 2026</h1>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-6">Calculate your Fixed Deposit maturity amount and interest earned. Enter deposit amount, interest rate, and tenure. Uses quarterly compounding (standard for most Indian banks). Compare FD returns across different tenures and rates.</p>
      <FdCalc />

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #2563EB", backgroundColor: "#DBEAFE" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2"><span>💡</span><span>FD vs PPF — the real comparison</span></p>
        <p className="text-sm text-text-secondary leading-relaxed">A 7% FD gives <strong>~4.9% post-tax return</strong> at the 30% bracket. PPF at 7.1% is fully tax-free — equivalent to <strong>~10.2% pre-tax</strong>. Over 5 years on ₹5 lakh: FD gives ₹2.01L interest (₹1.41L after tax). PPF gives ₹2.10L interest (₹2.10L after tax — zero tax). PPF wins by ₹69,000 on the same deposit.</p>
      </div>

      <SectionHeading icon="📖">How fixed deposits work in India</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">A Fixed Deposit is the simplest investment in India — you lock a sum of money with a bank for a fixed period (7 days to 10 years) and earn a guaranteed interest rate. At maturity, you receive your principal plus accumulated interest. FDs are considered one of the safest investments because they&apos;re backed by banks (insured up to ₹5 lakh by DICGC) and offer guaranteed returns regardless of market conditions.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Most banks compound FD interest quarterly. This means your interest earns interest every 3 months, resulting in a higher effective yield than the stated annual rate. For example, a 7% FD with quarterly compounding effectively yields 7.19% annually. Over longer tenures (5-10 years), this compounding effect adds significantly to your returns.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">The biggest limitation of FDs is taxation. FD interest is added to your income and taxed at your slab rate. For someone in the 30% bracket, a 7% FD effectively returns only 4.9% after tax. This makes FDs less attractive than tax-free instruments like PPF (7.1%, fully tax-free) or tax-advantaged options like ELSS (12-15% returns, 12.5% LTCG tax only above ₹1.25L).</p>

      <SectionHeading icon="🏦">FD rates comparison — April 2026</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>SBI:</strong> 1yr: 6.8%, 2yr: 7.0%, 3yr: 6.75%, 5yr: 6.5%. Senior citizen: +0.50% extra. SBI is the benchmark — most banks price around SBI rates. Tax-saving 5yr FD: 6.5%.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>HDFC Bank:</strong> 1yr: 6.6%, 2yr: 7.0%, 3yr: 7.1%, 5yr: 7.0%. Senior citizen: +0.75% extra (among the most generous senior citizen premiums). HDFC typically offers slightly higher rates for 3-5 year tenures.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Post Office:</strong> 1yr: 6.9%, 2yr: 7.0%, 3yr: 7.1%, 5yr: 7.5%. No senior citizen extra (fixed rate for all). Post office FDs offer the highest rates among government-backed options. Compounding is annual (not quarterly), which slightly reduces effective yield.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Small finance banks:</strong> AU SFB, Equitas, Ujjivan offer 7.5-8.5% for select tenures. Higher rates because they need deposits to fund lending. DICGC insured up to ₹5L like any other bank. Good option if you&apos;re within the insurance limit.</p>

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #DC2626", backgroundColor: "#FEE2E2" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2"><span>⚠️</span><span>TDS on FD interest</span></p>
        <p className="text-sm text-text-secondary leading-relaxed">Banks deduct 10% TDS if your FD interest exceeds <strong>₹40,000/year</strong> (₹50,000 for senior citizens) across all FDs with that bank. If you don&apos;t provide PAN, TDS is 20%. If your total income is below the taxable limit, submit <strong>Form 15G</strong> (under 60) or <strong>Form 15H</strong> (over 60) at the beginning of each financial year to avoid TDS. You can still claim refund while filing ITR if excess TDS was deducted.</p>
      </div>

      <SectionHeading icon="📊">FD laddering strategy</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Instead of one large FD, create multiple FDs with staggered maturity dates. For example, divide ₹10 lakh into 5 FDs of ₹2 lakh each with 1-year, 2-year, 3-year, 4-year, and 5-year tenures. Every year, one FD matures — giving you annual liquidity. Reinvest the matured FD into a new 5-year FD. After 5 years, all FDs are at the highest 5-year rate with annual access to ₹2 lakh.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Laddering solves FD&apos;s biggest problem — the liquidity vs rate trade-off. Short-term FDs give liquidity but lower rates. Long-term FDs give higher rates but lock your money. A ladder gives you both — highest rates with regular access. Banks never tell you about this strategy because it&apos;s more work for them to manage multiple FDs.</p>

      <blockquote className="my-6 border-l-4 border-accent pl-5 py-2">
        <p className="text-lg font-semibold text-text leading-snug italic">₹10 lakh in FD at 7% for 5 years gives ₹4.15 lakh interest. After 30% tax: <strong>₹2.90 lakh net</strong>. The same ₹10 lakh in PPF at 7.1% for 5 years: ₹4.24 lakh interest — <strong>100% tax-free</strong>. PPF gives ₹1.34 lakh more after tax.</p>
      </blockquote>

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #EA580C", backgroundColor: "#FFF7ED" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2"><span>🎯</span><span>When FD makes sense</span></p>
        <p className="text-sm text-text-secondary leading-relaxed">FDs are ideal for: <strong>(1)</strong> Emergency fund parking (3-6 months expenses in sweep-in FD), <strong>(2)</strong> Short-term goals (1-3 years — too short for equity), <strong>(3)</strong> Senior citizens needing regular income (non-cumulative monthly payout), <strong>(4)</strong> Capital protection when markets are volatile. For goals beyond 5 years, PPF or equity mutual funds offer significantly better post-tax returns.</p>
      </div>

      <SectionHeading icon="📚">Official source</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Compare FD rates across banks at <a href="https://www.rbi.org.in" target="_blank" rel="noopener" className="text-accent hover:underline">RBI</a>. DICGC insurance details at <a href="https://www.dicgc.org.in" target="_blank" rel="noopener" className="text-accent hover:underline">dicgc.org.in</a>. Post office FD rates at <a href="https://www.indiapost.gov.in" target="_blank" rel="noopener" className="text-accent hover:underline">indiapost.gov.in</a>.</p>
      <p className="text-xs text-text-muted mt-6 mb-8 italic">Last reviewed: April 2026 • Rates are indicative and may change. Check the bank website for current rates.</p>

      <SectionHeading icon="💡">Smart FD strategies</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>FD laddering — the essential strategy:</strong> Instead of one ₹10 lakh FD, create 5 FDs of ₹2 lakh each with 1-year, 2-year, 3-year, 4-year, and 5-year maturity. Every year, one FD matures — giving you access to ₹2 lakh. Reinvest the matured amount into a new 5-year FD. After 5 years, all FDs earn the highest 5-year rate but you have annual liquidity. This solves the rate vs. flexibility trade-off.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Spread across banks for DICGC protection:</strong> DICGC insurance covers ₹5 lakh per depositor per bank (principal + interest combined). If you have ₹20 lakh, keep ₹5 lakh each in 4 different banks. All ₹20 lakh is fully insured. Putting it all in one bank means only ₹5 lakh is protected if the bank fails. This is especially important for small finance bank FDs where risk is slightly higher.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Submit Form 15G/15H early:</strong> If your total income is below the taxable limit, submit Form 15G (under 60) or Form 15H (senior citizen) to your bank at the START of each financial year — April itself. This prevents TDS deduction on FD interest. If you submit late, TDS may already be deducted and you&apos;ll have to wait for ITR refund. Each bank requires a separate form.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Consider sweep-in FD:</strong> Link your savings account to an FD with auto-sweep. Surplus above a threshold (say ₹25,000) automatically creates an FD. When you need cash, the FD is broken in reverse order (LIFO). You earn FD rates on idle money without any manual effort. Most banks offer this with ₹0 setup cost. Only downside: interest is taxable like regular FD.</p>

      <SectionHeading icon="📊">FD for different life stages</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Young professionals (22-30):</strong> FD is NOT ideal as primary investment — equity SIP gives much higher long-term returns. Use FD only for: emergency fund (3-6 months expenses), short-term goals (1-2 years), and parking bonus money temporarily before investing in equity. Maximum 20% of savings in FD.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Middle-aged (30-50):</strong> FD has a role in the debt allocation of your portfolio. Keep 20-30% of total portfolio in FDs/debt for stability. Use FD laddering for systematic maturity. Consider tax-saving FD if 80C room is available (though ELSS or PPF are usually better). FD for children&apos;s near-term education expenses (2-3 years away).</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Senior citizens (60+):</strong> FD becomes a core holding. Senior citizen extra rate (0.25-0.75%) makes FDs more attractive. Non-cumulative monthly payout FD provides regular income. Combine with SCSS (8.2%, up to ₹30L), PMVVY (if still available), and senior citizen savings for a diversified income portfolio. TDS exemption up to ₹50,000/year (submit Form 15H).</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>NRIs:</strong> NRE FDs offer tax-free interest in India (fully repatriable). NRO FDs have Indian tax at 30% but can be from Indian-source income. FCNR FDs are in foreign currency with no exchange risk. NRE FD is the best option for NRIs parking funds in India — tax-free returns of 6-7% with full repatriation rights.</p>

      <SectionHeading icon="🔄">FD alternatives worth considering</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Debt mutual funds:</strong> Post April 2023, debt MF gains are taxed at slab rate (same as FD). But debt MFs offer better liquidity (no break penalty), professional management, and potentially higher returns (7-9% in corporate bond funds). Main advantage over FD: no TDS on debt MFs — you pay tax only on redemption, not annually.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Post Office Monthly Income Scheme (POMIS):</strong> 7.4% with monthly interest payout, ₹9 lakh limit (₹15L joint). Government-backed. Better rate than most bank FDs for regular income. 5-year lock-in. No TDS if interest is collected at post office counter (but interest is taxable).</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Corporate FDs:</strong> Companies like HDFC Ltd, Bajaj Finance, Mahindra Finance offer 7.5-8.5% — 0.5-1.5% higher than bank FDs. However, corporate FDs are NOT covered by DICGC insurance. Risk is limited to the company&apos;s financial health. Stick to AAA-rated companies and keep exposure below 10% of total fixed-income portfolio.</p>

      <SectionHeading icon="📋">FD interest calculation — understanding quarterly compounding</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Most banks use quarterly compounding for FDs. This means interest is calculated every 3 months and added to your principal. The next quarter&apos;s interest is calculated on the increased amount. For a ₹10 lakh FD at 7%: Quarterly rate = 7%/4 = 1.75%. After Q1: ₹10,17,500. After Q2: ₹10,35,306. After Q3: ₹10,53,424. After Q4: ₹10,71,859. Effective annual yield = 7.19% (not 7%).</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Post office FDs compound annually (not quarterly), so the effective yield equals the stated rate. For the same 7% rate: bank FD gives ₹71,859 interest vs post office gives ₹70,000 — a ₹1,859 difference per ₹10 lakh per year. Over 5 years on ₹10 lakh, quarterly compounding gives approximately ₹9,300 more than annual. This small difference matters for large deposits.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Some banks offer <strong>monthly compounding</strong> for specific products. Monthly rate = 7%/12 = 0.583%. This gives even higher effective yield: 7.23% vs 7.19% (quarterly) vs 7.00% (annual). The difference is marginal — about ₹400 more per ₹10 lakh per year compared to quarterly. Don&apos;t choose a bank solely for monthly compounding — overall rate matters more.</p>

      <SectionHeading icon="⚡">Tax-efficient FD strategies</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Split FDs across family members:</strong> Instead of one ₹20 lakh FD in your name (interest fully taxable at 30%), split: ₹10L in your name + ₹5L in spouse&apos;s name (if spouse has low income) + ₹5L in parents&apos; name (if retired/low income). Each person uses their own ₹40,000 TDS-free limit and basic exemption limit. Family pays less total tax on the same interest income.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Note on clubbing:</strong> If you gift money to your spouse and they open an FD, the interest income is &quot;clubbed&quot; with YOUR income and taxed at YOUR slab rate (Section 64). To avoid clubbing: spouse should invest from their OWN earned income (salary, business), not from gifts. Parents are exempt from clubbing — gifting money to parents for FD is tax-efficient if they&apos;re in a lower bracket.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Cumulative vs non-cumulative for tax:</strong> Cumulative FD interest is taxable on accrual basis — meaning the IT department considers interest earned in each year even though you receive it only at maturity. You may owe tax on FD interest you haven&apos;t physically received. Non-cumulative (interest paid out monthly/quarterly) aligns better with cash flow — you receive the interest and pay tax in the same year. For high-value FDs, this matters for cash flow planning.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Senior citizen advantage:</strong> Section 80TTB allows senior citizens (60+) to claim up to ₹50,000 deduction on interest from deposits (FDs, savings accounts, cooperative banks combined). At 30% tax bracket, this saves ₹15,600/year. Plus, the TDS threshold for seniors is ₹50,000 (vs ₹40,000 for others). Combined with Form 15H, seniors can earn up to ₹5 lakh interest without any TDS or tax (if total income is within exemption limit).</p>

      <SectionHeading icon="🔒">FD safety — understanding deposit insurance</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>DICGC coverage:</strong> All deposits (savings, FD, RD, current accounts) in scheduled commercial banks are insured up to ₹5 lakh per depositor per bank by DICGC (a subsidiary of RBI). This covers both principal and interest. If your FD + savings + RD in one bank totals ₹8 lakh, only ₹5 lakh is insured — the remaining ₹3 lakh is at risk if the bank fails.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Practical protection strategy:</strong> Keep no more than ₹4.5 lakh total deposits per bank (leaving room for interest accumulation to stay under ₹5L coverage). If you have ₹25 lakh in FDs, split across 6 banks. Yes, managing 6 bank accounts is inconvenient — but the protection is absolute. In 2020, Yes Bank and PMC Bank depositors learned the hard way why DICGC limits matter.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Post office vs bank safety:</strong> Post office deposits are backed by the Government of India — effectively zero risk, higher than DICGC coverage. If you want ₹10 lakh in one place with maximum safety, post office FD is the answer. Rates are competitive (7-7.5%) and government guarantee means your money is safe even in extreme economic scenarios.</p>

      <SectionHeading icon="❓">Frequently asked questions</SectionHeading>
      {faqs.map((f: any) => <FAQ key={f.question} question={f.question} answer={f.answer} />)}
      <div className="mt-10 flex flex-wrap gap-2">
        <a href="/calculator/ppf-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">PPF Calculator →</a>
        <a href="/calculator/sip-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">SIP Calculator →</a>
        <a href="/calculator/income-tax-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">Income Tax Calculator →</a>
        <a href="/calculator/nps-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">NPS Calculator →</a>
      </div>
    </div>
  );
}
