import type { Metadata } from "next";
import { PayCommissionCalc } from "@/components/calculators/pay-commission-calc";
import { JsonLd, faqSchema, breadcrumbSchema } from "@/components/json-ld";
import { Breadcrumb, SectionHeading, FAQ } from "@/components/ui";

export const metadata: Metadata = {
  title: "8th Pay Commission Calculator 2026 — Estimate New Salary Online",
  description: "Free 8th Pay Commission salary calculator. Enter your current 7th CPC basic pay and expected fitment factor to estimate your new salary under the 8th Pay Commission. Covers fitment factor, HRA, DA, and city-wise in-hand salary.",
  alternates: { canonical: "https://knowledgekendra.com/calculator/8th-pay-commission-calculator" },
};

const faqs = [
  { question: "When will the 8th Pay Commission be implemented?", answer: "The 8th Pay Commission was constituted in January 2026. Based on previous timelines, the commission typically takes 18-24 months to submit its report. Implementation is expected from January 1, 2026, with actual salary disbursement likely from mid-2027 or early 2028. Arrears from January 2026 will be paid separately." },
  { question: "What is the expected fitment factor for the 8th Pay Commission?", answer: "The fitment factor has not been officially announced yet. Historically: 6th CPC used 1.86x, 7th CPC used 2.57x. Estimates for the 8th CPC range from 2.28x to 2.86x. Most analysts expect around 2.57x (same as 7th CPC) or higher. The minimum basic pay is expected to increase from ₹18,000 to approximately ₹46,000-51,000." },
  { question: "What is a fitment factor?", answer: "Fitment factor is the multiplier applied to your current basic pay to calculate your new basic pay under the new pay commission. Fitment factor of 2.57x means: New Basic = Current Basic × 2.57. If your current 7th CPC basic is ₹56,100, your estimated 8th CPC basic would be ₹56,100 × 2.57 = ₹1,44,177. It's the single most impactful number in a pay commission revision." },
  { question: "Will DA reset to 0% under the 8th Pay Commission?", answer: "Yes. DA (Dearness Allowance) always resets to 0% when a new pay commission is implemented. The accumulated DA gets merged into the new basic pay via the fitment factor. After implementation, DA will start accumulating again at ~3-4% per year based on AICPI-IW index. So your initial 8th CPC salary will show 0% DA." },
  { question: "How will HRA change under the 8th Pay Commission?", answer: "HRA rates will be based on new city classifications. Currently under 7th CPC with DA above 50%: X cities (metros) get 27%, Y cities get 18%, Z cities get 9% of basic. Under 8th CPC, these percentages may change depending on the commission's recommendations. Initially, when DA is 0%, HRA will likely start at 24%, 16%, 8% and increase as DA crosses thresholds." },
  { question: "Who will benefit from the 8th Pay Commission?", answer: "All central government employees (approximately 50 lakh serving employees and 65 lakh pensioners) will benefit. State government employees benefit only if their state adopts the central pay commission recommendations — most states do, but with modifications. Defence personnel, PSU employees, and autonomous body staff are also covered." },
  { question: "Will pensioners get the 8th Pay Commission benefit?", answer: "Yes. Pensioners receive revised pension based on the new pay matrix. Pension is typically 50% of the last drawn pay. With the fitment factor, pensions will increase proportionally. Family pension (for dependents of deceased employees) will also be revised. Approximately 65 lakh pensioners stand to benefit." },
  { question: "What is the minimum salary expected under the 8th Pay Commission?", answer: "Current minimum basic pay under 7th CPC is ₹18,000. With an estimated fitment factor of 2.57x, the new minimum would be approximately ₹46,260. Some employee unions are demanding a minimum of ₹51,000-55,000, citing rising cost of living. The final figure depends on the commission's recommendations and government acceptance." },
  { question: "Will the 8th Pay Commission increase the tax burden?", answer: "Higher salary means higher taxable income. However, the government typically adjusts income tax slabs and standard deduction alongside pay commission revisions to offset the increased tax burden. Under the new tax regime, the basic exemption limit is ₹3 lakh with rebate up to ₹7 lakh — these limits may be revised when 8th CPC is implemented." },
  { question: "How is the fitment factor different from DA merger?", answer: "DA merger simply absorbs accumulated DA into basic pay without any real increase in take-home salary. Fitment factor includes DA merger PLUS an actual salary increase. For example, if current basic is ₹56,100 with 50% DA (effective ₹84,150), and fitment is 2.57x, new basic = ₹1,44,177. The ₹60,027 increase over the effective salary is the 'real raise' from the pay commission." },
  { question: "What happened in previous pay commissions?", answer: "1st CPC (1947): Minimum salary ₹55/month. 4th CPC (1986): ₹750. 5th CPC (1996): ₹2,550 (fitment 1.86x). 6th CPC (2006): ₹7,000 (fitment 1.86x). 7th CPC (2016): ₹18,000 (fitment 2.57x). Each commission roughly doubled the minimum salary. If the pattern holds, 8th CPC minimum could be ₹36,000-51,000." },
  { question: "How long does a pay commission take to submit its report?", answer: "Historically: 5th CPC took 3 years (1994-1997), 6th CPC took 2.5 years (2006-2008), 7th CPC took 2 years (2014-2015). The 8th CPC, constituted in 2026, is expected to submit its report by 2027-2028. After submission, the government takes 3-6 months to review and accept (with or without modifications)." },
  { question: "Will contractual and outsourced employees get the 8th CPC benefit?", answer: "No. Pay commissions cover only regular government employees appointed through competitive exams and proper recruitment. Contractual, outsourced, daily-wage, and ad-hoc employees are not covered. However, some states have announced minimum wage revisions linked to pay commission recommendations for contractual staff." },
  { question: "Can I calculate my exact 8th CPC salary now?", answer: "No. The calculator above provides estimates based on assumed fitment factors. The actual salary will depend on: (1) Final fitment factor announced by the commission, (2) Revised HRA/TA rates, (3) New pay matrix structure, (4) Any structural changes in allowances. Use this calculator for planning purposes, not final figures." },
  { question: "Will arrears be paid for the 8th Pay Commission?", answer: "Yes. If the 8th CPC is implemented from January 1, 2026, employees will receive arrears for the months between the implementation date and actual salary disbursement. For 7th CPC, arrears of 18+ months were paid. These arrears are a significant lump-sum — often ₹2-5 lakh depending on pay level — and are taxable as income in the year of receipt." },
];

export default function Page() {
  return (
    <div className="max-w-[860px] mx-auto px-5 py-6">
      <JsonLd data={breadcrumbSchema([{ name: "Home", url: "https://knowledgekendra.com" }, { name: "Calculators", url: "https://knowledgekendra.com/calculator" }, { name: "8th Pay Commission Calculator", url: "https://knowledgekendra.com/calculator/8th-pay-commission-calculator" }])} />
      <JsonLd data={faqSchema(faqs)} />
      <JsonLd data={{ "@context": "https://schema.org", "@type": "WebApplication", name: "8th Pay Commission Calculator 2026", description: "Estimate your new salary under the 8th Pay Commission. Enter current basic pay and fitment factor.", applicationCategory: "FinanceApplication", operatingSystem: "Web", offers: { "@type": "Offer", price: "0", priceCurrency: "INR" } }} />

      <Breadcrumb items={[{ label: "Home", href: "/" }, { label: "Calculators", href: "/calculator" }, { label: "8th Pay Commission Calculator" }]} />

      <h1 className="text-2xl font-extrabold tracking-tight text-text mb-2">8th Pay Commission Calculator 2026</h1>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-6">Estimate your salary under the 8th Pay Commission. Enter your current 7th CPC basic pay, adjust the expected fitment factor, and select your city category to see estimated in-hand salary. Note: these are projections — actual figures will depend on the commission&apos;s final recommendations.</p>

      <PayCommissionCalc />

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #2563EB", backgroundColor: "#DBEAFE" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2"><span>💡</span><span>What is the 8th Pay Commission?</span></p>
        <p className="text-sm text-text-secondary leading-relaxed">The 8th Central Pay Commission was constituted in <strong>January 2026</strong> to review and revise salaries of central government employees. It will recommend a new pay matrix, fitment factor, and revised allowances. Approximately <strong>50 lakh serving employees and 65 lakh pensioners</strong> will be impacted. The minimum basic pay is expected to more than double from the current ₹18,000.</p>
      </div>

      <SectionHeading icon="📊">Fitment factor — the number that decides your salary</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">The fitment factor is the single most important number in any pay commission. It&apos;s the multiplier applied to your current basic pay to determine your new basic. The 7th CPC used 2.57x, meaning every employee&apos;s basic pay was multiplied by 2.57.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">The fitment factor is NOT purely a &quot;raise.&quot; It includes DA merger (absorbing accumulated DA into basic) plus the actual salary increase. With current DA at ~50%, a 2.57x fitment means the real raise over your current effective salary (basic + DA) is approximately 71%. If the fitment factor stays at 2.57x, someone earning ₹56,100 basic (Pay Level 10) would see their basic jump to ₹1,44,177.</p>

      <div className="my-6">
        <p className="text-xs text-text-muted mb-2 text-center italic">Fitment factor history across pay commissions</p>
        <div className="card p-4 flex justify-center overflow-x-auto" dangerouslySetInnerHTML={{ __html: '<svg viewBox="0 0 700 230" xmlns="http://www.w3.org/2000/svg" style="max-width:100%;height:auto"><text x="350" y="25" text-anchor="middle" font-family="sans-serif" font-size="14" font-weight="700" fill="#111827">Pay Commission fitment factors — 5th to 8th</text><rect x="60" y="60" width="130" height="140" rx="12" fill="#DBEAFE" stroke="#2563EB" stroke-width="2"/><text x="125" y="90" text-anchor="middle" font-family="sans-serif" font-size="13" font-weight="700" fill="#1E40AF">5th CPC (1996)</text><text x="125" y="125" text-anchor="middle" font-family="sans-serif" font-size="28" font-weight="800" fill="#2563EB">1.86×</text><text x="125" y="150" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#1E40AF">Min: ₹2,550</text><text x="125" y="170" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#1E40AF">→ ₹4,743</text><rect x="210" y="60" width="130" height="140" rx="12" fill="#DCFCE7" stroke="#1B6B4A" stroke-width="2"/><text x="275" y="90" text-anchor="middle" font-family="sans-serif" font-size="13" font-weight="700" fill="#145236">6th CPC (2006)</text><text x="275" y="125" text-anchor="middle" font-family="sans-serif" font-size="28" font-weight="800" fill="#1B6B4A">1.86×</text><text x="275" y="150" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#145236">Min: ₹4,860</text><text x="275" y="170" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#145236">→ ₹7,000</text><rect x="360" y="60" width="130" height="140" rx="12" fill="#FFF7ED" stroke="#EA580C" stroke-width="2"/><text x="425" y="90" text-anchor="middle" font-family="sans-serif" font-size="13" font-weight="700" fill="#C2410C">7th CPC (2016)</text><text x="425" y="125" text-anchor="middle" font-family="sans-serif" font-size="28" font-weight="800" fill="#EA580C">2.57×</text><text x="425" y="150" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#C2410C">Min: ₹7,000</text><text x="425" y="170" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#C2410C">→ ₹18,000</text><rect x="510" y="60" width="150" height="140" rx="12" fill="#F3E8FF" stroke="#7C3AED" stroke-width="2"/><text x="585" y="90" text-anchor="middle" font-family="sans-serif" font-size="13" font-weight="700" fill="#6B21A8">8th CPC (2026)</text><text x="585" y="125" text-anchor="middle" font-family="sans-serif" font-size="28" font-weight="800" fill="#7C3AED">2.57×?</text><text x="585" y="150" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#6B21A8">Min: ₹18,000</text><text x="585" y="170" text-anchor="middle" font-family="sans-serif" font-size="11" fill="#6B21A8">→ ₹46,260?</text><text x="585" y="188" text-anchor="middle" font-family="sans-serif" font-size="10" font-style="italic" fill="#6B21A8">(estimated)</text></svg>' }} />
        <p className="text-sm text-text-secondary mt-3">The jump from 1.86x (5th/6th CPC) to 2.57x (7th CPC) was historic. Employee unions are pushing for 2.86x or higher for the 8th CPC. The final factor will depend on fiscal capacity and inflation trajectory.</p>
      </div>

      <blockquote className="my-6 border-l-4 border-accent pl-5 py-2">
        <p className="text-lg font-semibold text-text leading-snug italic">At 2.57x fitment, a Level 7 officer (current basic ₹44,900) would see their basic jump to <strong>₹1,15,393</strong>. With DA at 0% and X-city HRA (27%), estimated in-hand would be approximately <strong>₹1,35,000/month</strong>.</p>
      </blockquote>

      <SectionHeading icon="🏙️">How city category affects your salary</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">HRA (House Rent Allowance) varies dramatically by city classification. Under the 7th CPC with DA above 50%: X cities (Delhi, Mumbai, Kolkata, Chennai, Bangalore, Hyderabad, Ahmedabad, Pune) get 27% HRA. Y cities (state capitals, cities with 5L+ population) get 18%. Z cities (all others) get 9%.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Transport Allowance also differs: ₹7,200/month + DA for X/Y cities, ₹3,600/month + DA for Z cities (for Pay Levels 3-8). This means an officer in Delhi can earn ₹15,000-25,000 more per month than the same officer in a Z-city posting — purely from HRA and TA differences.</p>

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #DC2626", backgroundColor: "#FEE2E2" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2"><span>⚠️</span><span>These are estimates, not final figures</span></p>
        <p className="text-sm text-text-secondary leading-relaxed">The 8th Pay Commission has been constituted but has <strong>not yet submitted its report</strong>. All salary figures shown by this calculator are projections based on assumed fitment factors and current allowance structures. Actual figures may differ significantly. Do not make financial commitments (loans, purchases) based on estimated 8th CPC salary.</p>
      </div>

      <SectionHeading icon="📈">Impact on pensioners</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Approximately 65 lakh central government pensioners will receive revised pension under the 8th CPC. Pension is typically 50% of the last drawn basic pay. With the fitment factor, pensions will increase proportionally — a pensioner receiving ₹25,000/month could see it rise to approximately ₹64,000/month at 2.57x fitment.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Family pension (for dependents) is 30% of last drawn pay, with a minimum of 30% of the minimum pay. This will also be revised. Additionally, Dearness Relief (equivalent of DA for pensioners) will reset to 0% and start accumulating again.</p>

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #1B6B4A", backgroundColor: "#DCFCE7" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2"><span>📌</span><span>Official source</span></p>
        <p className="text-sm text-text-secondary leading-relaxed">The 8th Pay Commission was constituted via <strong>Government of India Gazette Notification, January 2026</strong>. Official updates are published at <a href="https://doe.gov.in" target="_blank" rel="noopener" className="text-accent hover:underline">doe.gov.in</a> (Department of Expenditure) and <a href="https://finmin.nic.in" target="_blank" rel="noopener" className="text-accent hover:underline">finmin.nic.in</a> (Ministry of Finance).</p>
      </div>

      <p className="text-xs text-text-muted mt-6 mb-8 italic">Last reviewed: April 2026 • All 8th CPC figures are estimates based on assumed fitment factors. Final figures will be determined by the Pay Commission&apos;s report and government acceptance.</p>

      
      <SectionHeading icon="💼">Who is covered by the 8th Pay Commission?</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Central government employees:</strong> All Group A, B, C, and erstwhile Group D employees appointed through regular recruitment. This includes IAS, IPS, IFS officers, central secretariat staff, railway employees, postal employees, defence civilian staff, and employees of constitutional bodies (Election Commission, CAG, UPSC).</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Defence personnel:</strong> Army, Navy, and Air Force personnel receive pay commission benefits through a separate Military Pay Matrix. The pay structure is similar but includes Military Service Pay (MSP), field area allowance, and other defence-specific components. Defence pensioners are also covered.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>State government employees:</strong> Not automatically covered. Each state decides independently whether to adopt the central pay commission recommendations. Most large states (UP, Maharashtra, Tamil Nadu, Karnataka) eventually adopt with modifications. Some states (like Kerala, West Bengal) have their own pay commissions with different timelines.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>NOT covered:</strong> Contractual employees, outsourced staff, daily-wage workers, PSU employees (they have separate Board-level pay revisions), autonomous body employees (depends on the body&apos;s rules), and state government employees (unless the state adopts centrally).</p>

      <SectionHeading icon="📊">Pay matrix structure — how levels work</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">The 7th CPC introduced a <strong>Pay Matrix</strong> with 18 pay levels (Level 1 to Level 18). Each level has 40 cells (annual increments). Your salary is determined by your Level and Cell. Level 1 (₹18,000 basic) is for Group C support staff. Level 10 (₹56,100) is for Group A entry-level officers like IAS/IPS. Level 18 (₹2,50,000) is for the Cabinet Secretary — the highest-paid civil servant.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Under the 8th CPC, the pay matrix will be restructured with a new fitment factor applied to every cell. If the fitment is 2.57x, Level 1 Cell 1 moves from ₹18,000 to ~₹46,260. Level 10 Cell 1 moves from ₹56,100 to ~₹1,44,177. The ratio between levels is expected to remain similar, though the commission may adjust compression ratios.</p>

      <div className="my-6">
        <p className="text-xs text-text-muted mb-2 text-center italic">Key pay levels and their 8th CPC estimates (at 2.57x fitment)</p>
        <div className="card p-4 flex justify-center overflow-x-auto" dangerouslySetInnerHTML={{ __html: '<svg viewBox="0 0 700 280" xmlns="http://www.w3.org/2000/svg" style="max-width:100%;height:auto"><text x="350" y="25" text-anchor="middle" font-family="sans-serif" font-size="14" font-weight="700" fill="#111827">7th CPC vs estimated 8th CPC basic pay</text><line x1="80" y1="240" x2="650" y2="240" stroke="#4B5563" stroke-width="1"/><rect x="100" y="200" width="55" height="40" fill="#DBEAFE" stroke="#2563EB" stroke-width="1.5"/><rect x="160" y="170" width="55" height="70" fill="#1B6B4A"/><text x="130" y="260" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#4B5563">Level 1</text><text x="128" y="195" text-anchor="middle" font-family="sans-serif" font-size="9" font-weight="700" fill="#1E40AF">₹18K</text><text x="188" y="166" text-anchor="middle" font-family="sans-serif" font-size="9" font-weight="700" fill="#1B6B4A">₹46K</text><rect x="240" y="175" width="55" height="65" fill="#DBEAFE" stroke="#2563EB" stroke-width="1.5"/><rect x="300" y="115" width="55" height="125" fill="#1B6B4A"/><text x="270" y="260" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#4B5563">Level 7</text><text x="268" y="170" text-anchor="middle" font-family="sans-serif" font-size="9" font-weight="700" fill="#1E40AF">₹44.9K</text><text x="328" y="111" text-anchor="middle" font-family="sans-serif" font-size="9" font-weight="700" fill="#1B6B4A">₹1.15L</text><rect x="380" y="155" width="55" height="85" fill="#DBEAFE" stroke="#2563EB" stroke-width="1.5"/><rect x="440" y="75" width="55" height="165" fill="#1B6B4A"/><text x="410" y="260" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#4B5563">Level 10</text><text x="408" y="150" text-anchor="middle" font-family="sans-serif" font-size="9" font-weight="700" fill="#1E40AF">₹56.1K</text><text x="468" y="71" text-anchor="middle" font-family="sans-serif" font-size="9" font-weight="700" fill="#1B6B4A">₹1.44L</text><rect x="520" y="125" width="55" height="115" fill="#DBEAFE" stroke="#2563EB" stroke-width="1.5"/><rect x="580" y="45" width="55" height="195" fill="#1B6B4A"/><text x="550" y="260" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#4B5563">Level 14</text><text x="548" y="120" text-anchor="middle" font-family="sans-serif" font-size="9" font-weight="700" fill="#1E40AF">₹1.44L</text><text x="608" y="41" text-anchor="middle" font-family="sans-serif" font-size="9" font-weight="700" fill="#1B6B4A">₹3.7L</text><rect x="130" y="270" width="12" height="8" fill="#DBEAFE" stroke="#2563EB" stroke-width="1"/><text x="148" y="278" font-family="sans-serif" font-size="10" fill="#4B5563">7th CPC</text><rect x="250" y="270" width="12" height="8" fill="#1B6B4A"/><text x="268" y="278" font-family="sans-serif" font-size="10" fill="#4B5563">8th CPC (est.)</text></svg>' }} />
      </div>

      <SectionHeading icon="🏠">Allowances beyond basic pay</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Dearness Allowance (DA):</strong> Compensates for inflation. Revised every January 1 and July 1 based on AICPI-IW index. Current DA under 7th CPC is 58%. Under 8th CPC, DA resets to 0% and starts accumulating again. DA is fully taxable as income.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>House Rent Allowance (HRA):</strong> X cities (8 metros) get the highest HRA, Z cities get the lowest. When DA is 0% (start of new CPC): X=24%, Y=16%, Z=8% of basic. As DA crosses 25% and 50%, HRA slabs increase to 27%/18%/9% and then further. HRA is partially exempt from income tax if you actually pay rent.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Transport Allowance:</strong> Fixed amount based on city category and pay level. For Levels 3-8: ₹7,200/month in X/Y cities, ₹3,600 in Z cities. Plus DA on TA. Some employees get TPTA (Transport + Posting + Transfer Allowance) — a consolidated allowance in select cities.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Other allowances:</strong> Children Education Allowance (₹2,250/month per child, max 2 children), Special Duty Allowance (for difficult postings), Risk Allowance (for hazardous work), Uniform Allowance, and City Compensatory Allowance. These vary by department and posting.</p>

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #EA580C", backgroundColor: "#FFF7ED" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2"><span>🎯</span><span>Planning tip for govt employees</span></p>
        <p className="text-sm text-text-secondary leading-relaxed">Don&apos;t take loans or make major financial commitments based on estimated 8th CPC salary. The actual fitment factor, HRA rates, and allowance structure may differ significantly from projections. Wait for the official gazette notification before restructuring your finances. Use this calculator for <strong>planning only</strong>, not for commitment.</p>
      </div>

      <SectionHeading icon="📜">History of pay commissions in India</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">India has had 7 central pay commissions since independence. The 1st CPC (1947) set the minimum salary at ₹55/month. The 4th CPC (1986) raised it to ₹750. The 5th CPC (1996) was the first to use a fitment factor (1.86x), raising minimum to ₹2,550. The 6th CPC (2006) introduced Grade Pay system. The 7th CPC (2016) replaced Grade Pay with the Pay Matrix system and used the highest-ever fitment of 2.57x.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Pay commissions are typically constituted every 10 years, though the gap has varied from 8 to 13 years historically. The 8th CPC was constituted in January 2026, exactly 10 years after the 7th CPC&apos;s implementation. Each commission takes 18-24 months to submit its report, and implementation usually takes another 6-12 months after that.</p>

      <SectionHeading icon="💰">Salary comparison — 7th CPC vs estimated 8th CPC</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Group C (Level 1-5):</strong> A peon/MTS at Level 1 currently earns ₹18,000 basic with ~₹10,440 DA (58%) = ₹28,440. Under 8th CPC at 2.57x: new basic ₹46,260, DA 0%, estimated in-hand with HRA (Z city 8%) = approximately ₹47,000. That&apos;s a significant improvement for the lowest-paid government employees.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Group B (Level 6-8):</strong> An Income Tax Inspector at Level 7 earns ₹44,900 basic + ₹26,042 DA = ₹70,942. Under 8th CPC: new basic ₹1,15,393, estimated in-hand (X city) = approximately ₹1,35,000-1,40,000. The absolute increase is much larger for Group B officers — roughly ₹60,000-70,000 more per month.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Group A (Level 10-14):</strong> An IAS/IPS at Level 10 entry earns ₹56,100 basic + ₹32,538 DA = ₹88,638. Under 8th CPC: new basic ₹1,44,177, estimated in-hand (X city) = approximately ₹1,70,000-1,80,000. Senior IAS officers at Level 14 (₹1,44,200 basic) would see their basic jump to approximately ₹3,70,594.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Cabinet Secretary (Level 18):</strong> Currently the highest-paid civil servant at ₹2,50,000 basic. Under 8th CPC: estimated basic ₹6,42,500. With HRA and other allowances, the total package could exceed ₹8,00,000/month. This will make government service significantly more competitive with private sector executive compensation.</p>

      <SectionHeading icon="📈">Financial planning around the 8th Pay Commission</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Arrears investment:</strong> When 8th CPC is implemented (likely with 12-18 months arrears), you&apos;ll receive a large lumpsum — potentially ₹3-8 lakh depending on your level. Plan NOW how to invest these arrears. Best options: pay off high-interest loans first, then invest in a mix of equity mutual funds (for long-term growth) and PPF (for tax-free guaranteed returns).</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Tax planning:</strong> Higher salary means higher tax bracket. With 8th CPC salaries, many Group B and C employees who were in the 20% bracket will move to 30%. Start planning tax-saving investments now — maximize NPS (₹50K extra deduction), EPF/VPF, PPF, and ELSS. Consider the old regime if your deductions are substantial.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Loan eligibility:</strong> Higher basic pay directly increases your home loan eligibility (banks typically lend 60× monthly salary). An officer moving from ₹56,100 to ₹1,44,177 basic sees loan eligibility jump from ~₹33 lakh to ~₹86 lakh. If planning a home purchase, consider waiting for 8th CPC implementation to qualify for a larger loan.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>NPS impact:</strong> Government NPS contribution is 14% of Basic + DA. With basic doubling under 8th CPC, your monthly NPS contribution also doubles — leading to a significantly larger retirement corpus. An officer whose NPS contribution jumps from ₹7,854/month to ₹20,185/month will accumulate approximately ₹1.5-2 crore more over their remaining service period.</p>

      <SectionHeading icon="🔄">OPS vs NPS — the ongoing debate</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">The Old Pension Scheme (OPS) guaranteed 50% of last drawn salary as pension for life. NPS, which replaced OPS for employees joining after January 2004, provides market-linked returns with no guaranteed pension. Several states (Rajasthan, Chhattisgarh, Jharkhand, Punjab, Himachal Pradesh) have announced reverting to OPS for state employees.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Under the 8th CPC, OPS pensioners will receive revised pension based on the new pay matrix — typically 50% of the revised pay of their equivalent current rank. NPS subscribers don&apos;t get this guaranteed increase — their pension depends on how well their NPS investments have performed. This disparity has fueled the OPS restoration movement among central government employees.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">The Unified Pension Scheme (UPS), announced in 2024 as a middle ground, offers 50% of average basic pay of last 12 months as pension for employees with 25+ years of service. For those with 10-25 years, pension is proportionate. UPS includes a minimum pension of ₹10,000/month and family pension of 60% of employee pension. This may be further revised under the 8th CPC recommendations.</p>

      <SectionHeading icon="❓">Frequently asked questions</SectionHeading>
      {faqs.map((f: any) => <FAQ key={f.question} question={f.question} answer={f.answer} />)}

      <div className="mt-10 flex flex-wrap gap-2">
        <a href="/calculator/gratuity-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">Gratuity Calculator →</a>
        <a href="/calculator/nps-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">NPS Calculator →</a>
        <a href="/calculator/hra-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">HRA Calculator →</a>
        <a href="/calculator/income-tax-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">Income Tax Calculator →</a>
        <a href="/calculator/epf-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">EPF Calculator →</a>
      </div>
    </div>
  );
}
