"use client";

import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { Suspense } from "react";

// All pages data embedded for client-side search
const allPages = [
  {url:"/yojana/agnipath-scheme",title:"Agnipath Scheme",desc:"4-year military service opportunity in Indian Armed Forces with ₹30,000-40,000 monthly salary and ₹11.71 lakh tax-free S",cat:"Yojana",icon:"🎖️",s:"agnipath scheme 4-year military service opportunity in indian armed forces with ₹30,000-40,000 monthly salary and ₹11.71 lakh tax-free seva nidhi on completion defence military army navy air force youth central government"},
  {url:"/yojana/ap-ysr-aarogyasri",title:"YSR Aarogyasri (AP) — ₹25 Lakh Health Insurance",desc:"Andhra Pradesh\'s state health insurance — ₹25 lakh cashless treatment at 2,400+ hospitals for white ration card holders.",cat:"Yojana",icon:"🏥",s:"ysr aarogyasri (ap) — ₹25 lakh health insurance andhra pradesh\'s state health insurance — ₹25 lakh cashless treatment at 2,400+ hospitals for white ration card holders. free for bpl families. health andhra pradesh"},
  {url:"/yojana/atal-pension-yojana",title:"Atal Pension Yojana",desc:"Guaranteed monthly pension of ₹1,000 to ₹5,000 after age 60 — India\'s most affordable pension scheme for workers in the ",cat:"Yojana",icon:"👴",s:"atal pension yojana guaranteed monthly pension of ₹1,000 to ₹5,000 after age 60 — india\'s most affordable pension scheme for workers in the unorganized sector pension retirement unorganized sector pfrda central government"},
  {url:"/yojana/ayushman-bharat",title:"Ayushman Bharat (PMJAY)",desc:"₹5 lakh free health insurance per family per year covering 1,900+ medical procedures at 30,000+ empanelled hospitals",cat:"Yojana",icon:"🏥",s:"ayushman bharat (pmjay) ₹5 lakh free health insurance per family per year covering 1,900+ medical procedures at 30,000+ empanelled hospitals health insurance pmjay hospital central government free"},
  {url:"/yojana/bihar-student-credit-card",title:"Bihar Student Credit Card — Education Loan up to ₹4 Lakh",desc:"Bihar government provides up to ₹4 lakh education loan at zero interest to 12th pass students for higher education — cov",cat:"Yojana",icon:"🎓",s:"bihar student credit card — education loan up to ₹4 lakh bihar government provides up to ₹4 lakh education loan at zero interest to 12th pass students for higher education — covering tuition, hostel, books, and laptop bihar education loan student zero interest state scheme credit card"},
  {url:"/yojana/chiranjeevi-yojana",title:"Chiranjeevi Yojana (Rajasthan) — ₹25 Lakh Health Cover",desc:"Rajasthan\'s universal health insurance — ₹25 lakh per family per year for cashless treatment at 1,000+ empanelled hospit",cat:"Yojana",icon:"🏥",s:"chiranjeevi yojana (rajasthan) — ₹25 lakh health cover rajasthan\'s universal health insurance — ₹25 lakh per family per year for cashless treatment at 1,000+ empanelled hospitals across india rajasthan health insurance cashless state scheme chiranjeevi"},
  {url:"/yojana/e-shram-card",title:"e-Shram Card Registration",desc:"Digital identity card for India\'s 30+ crore unorganized workers — free ₹2 lakh accident insurance and gateway to all gov",cat:"Yojana",icon:"👷",s:"e-shram card registration digital identity card for india\'s 30+ crore unorganized workers — free ₹2 lakh accident insurance and gateway to all government welfare schemes labour unorganized sector social security registration central government gig workers"},
  {url:"/yojana/gruha-lakshmi",title:"Gruha Lakshmi Yojana (Karnataka) — ₹2,000/Month",desc:"Karnataka\'s flagship women\'s welfare scheme — ₹2,000 per month to the woman head of every BPL and APL household below th",cat:"Yojana",icon:"👩",s:"gruha lakshmi yojana (karnataka) — ₹2,000/month karnataka\'s flagship women\'s welfare scheme — ₹2,000 per month to the woman head of every bpl and apl household below the income threshold karnataka women cash transfer state scheme gruha lakshmi"},
  {url:"/yojana/jan-samarth",title:"Jan Samarth Portal — All Government Loan Schemes in One Place",desc:"One portal to apply for PM Mudra, education loans, Startup India, PM SVANidhi, PMAY subsidy, and 10+ other government cr",cat:"Yojana",icon:"🏛️",s:"jan samarth portal — all government loan schemes in one place one portal to apply for pm mudra, education loans, startup india, pm svanidhi, pmay subsidy, and 10+ other government credit schemes — no middlemen, no agents. government digital india"},
  {url:"/yojana/kalia-yojana",title:"KALIA Yojana (Odisha) — ₹12,500 for Farmers",desc:"Odisha\'s direct income support for small farmers (₹12,500/year) and landless agricultural households — covering cultivat",cat:"Yojana",icon:"🌾",s:"kalia yojana (odisha) — ₹12,500 for farmers odisha\'s direct income support for small farmers (₹12,500/year) and landless agricultural households — covering cultivation, livestock, and livelihood odisha farmer agriculture state scheme kalia direct benefit"},
  {url:"/yojana/kanya-sumangala-yojana",title:"Kanya Sumangala Yojana (UP) — ₹25,000 for Girl Child",desc:"Uttar Pradesh gives ₹25,000 to every girl child in 6 installments from birth to graduation — promoting girl education an",cat:"Yojana",icon:"👧",s:"kanya sumangala yojana (up) — ₹25,000 for girl child uttar pradesh gives ₹25,000 to every girl child in 6 installments from birth to graduation — promoting girl education and fighting female foeticide uttar pradesh girl child education state scheme mksy"},
  {url:"/yojana/kanya-vivah-yojana",title:"Mukhyamantri Kanya Vivah Yojana — Marriage Assistance",desc:"Government provides ₹28,000 to ₹55,000 financial assistance for the marriage of daughters from BPL and lower-income fami",cat:"Yojana",icon:"💍",s:"mukhyamantri kanya vivah yojana — marriage assistance government provides ₹28,000 to ₹55,000 financial assistance for the marriage of daughters from bpl and lower-income families — available in mp, bihar, up, and other states marriage women bpl state scheme financial assistance"},
  {url:"/yojana/ladli-behna-yojana",title:"Ladli Behna Yojana (MP) — ₹1,250/Month for Women",desc:"Madhya Pradesh\'s flagship women\'s welfare scheme — ₹1,250 per month direct transfer to married women aged 21-60 from low",cat:"Yojana",icon:"👩",s:"ladli behna yojana (mp) — ₹1,250/month for women madhya pradesh\'s flagship women\'s welfare scheme — ₹1,250 per month direct transfer to married women aged 21-60 from lower-income families madhya pradesh women cash transfer state scheme ladli behna"},
  {url:"/yojana/lek-ladki-yojana",title:"Lek Ladki Yojana (Maharashtra) — ₹1,01,000 for Girls",desc:"Maharashtra government provides ₹1,01,000 in 5 installments from birth to age 18 for girls born in economically weaker f",cat:"Yojana",icon:"👧",s:"lek ladki yojana (maharashtra) — ₹1,01,000 for girls maharashtra government provides ₹1,01,000 in 5 installments from birth to age 18 for girls born in economically weaker families maharashtra girl child education state scheme lek ladki"},
  {url:"/yojana/mahtari-vandana",title:"Mahtari Vandana Yojana (Chhattisgarh) — ₹1,000/Month for Women",desc:"Chhattisgarh women welfare — ₹1,000/month direct transfer to married women aged 21-60",cat:"Yojana",icon:"👩",s:"mahtari vandana yojana (chhattisgarh) — ₹1,000/month for women chhattisgarh women welfare — ₹1,000/month direct transfer to married women aged 21-60 chhattisgarh women cash transfer"},
  {url:"/yojana/majhi-ladki-bahin",title:"Majhi Ladki Bahin Yojana (Maharashtra) — ₹1,500/Month",desc:"Maharashtra\'s women empowerment scheme — ₹1,500 per month direct transfer to eligible women aged 21-65 from economically",cat:"Yojana",icon:"👩",s:"majhi ladki bahin yojana (maharashtra) — ₹1,500/month maharashtra\'s women empowerment scheme — ₹1,500 per month direct transfer to eligible women aged 21-65 from economically weaker families maharashtra women cash transfer state scheme majhi ladki bahin"},
  {url:"/yojana/national-pension-scheme",title:"National Pension System (NPS)",desc:"Market-linked retirement savings with additional ₹50,000 tax deduction beyond 80C — build a retirement corpus and receiv",cat:"Yojana",icon:"🏛️",s:"national pension system (nps) market-linked retirement savings with additional ₹50,000 tax deduction beyond 80c — build a retirement corpus and receive monthly pension after 60 nps pension retirement 80ccd tax saving market-linked"},
  {url:"/yojana/pm-awas-yojana",title:"PM Awas Yojana (PMAY)",desc:"Government subsidy of up to ₹2.67 lakh on home loans to make housing affordable for economically weaker sections and mid",cat:"Yojana",icon:"🏠",s:"pm awas yojana (pmay) government subsidy of up to ₹2.67 lakh on home loans to make housing affordable for economically weaker sections and middle-income families housing subsidy home loan urban rural central government"},
  {url:"/yojana/pm-fasal-bima-yojana",title:"PM Fasal Bima Yojana",desc:"Crop insurance at minimal premium — 2% for kharif and 1.5% for rabi crops — protecting farmers against natural calamitie",cat:"Yojana",icon:"🌿",s:"pm fasal bima yojana crop insurance at minimal premium — 2% for kharif and 1.5% for rabi crops — protecting farmers against natural calamities, pests, and crop diseases agriculture crop insurance farmer natural calamity central government"},
  {url:"/yojana/pm-garib-kalyan-anna",title:"PM Garib Kalyan Anna Yojana — Free Ration Scheme",desc:"Free rice and wheat for 80+ crore Indians under the National Food Security Act — 5 kg food grains per person per month a",cat:"Yojana",icon:"🍚",s:"pm garib kalyan anna yojana — free ration scheme free rice and wheat for 80+ crore indians under the national food security act — 5 kg food grains per person per month at zero cost free ration food security nfsa bpl central government"},
  {url:"/yojana/pm-internship-scheme",title:"PM Internship Scheme 2024 — ₹5,000/Month for Youth",desc:"Government-facilitated 12-month internship at India\'s top 500 companies with ₹5,000/month stipend and ₹6,000 one-time gr",cat:"Yojana",icon:"💼",s:"pm internship scheme 2024 — ₹5,000/month for youth government-facilitated 12-month internship at india\'s top 500 companies with ₹5,000/month stipend and ₹6,000 one-time grant — targeting 1 crore youth over 5 years internship youth stipend top 500 central government"},
  {url:"/yojana/pm-jan-dhan-yojana",title:"PM Jan Dhan Yojana",desc:"Zero-balance savings account with free RuPay debit card, ₹2 lakh accident insurance, and overdraft facility — India\'s la",cat:"Yojana",icon:"🏦",s:"pm jan dhan yojana zero-balance savings account with free rupay debit card, ₹2 lakh accident insurance, and overdraft facility — india\'s largest financial inclusion drive banking financial inclusion zero balance rupay dbt central government"},
  {url:"/yojana/pm-jeevan-jyoti-bima",title:"PM Jeevan Jyoti Bima Yojana",desc:"₹2 lakh life insurance covering death from ANY cause — illness, accident, or natural — for just ₹436 per year (₹1.19/day",cat:"Yojana",icon:"💚",s:"pm jeevan jyoti bima yojana ₹2 lakh life insurance covering death from any cause — illness, accident, or natural — for just ₹436 per year (₹1.19/day) life insurance pmjjby ₹436 central government lic"},
  {url:"/yojana/pm-kisan-credit-card",title:"Kisan Credit Card (KCC)",desc:"Short-term agricultural loans at just 4% interest (after government subsidy) — the cheapest borrowing option for Indian ",cat:"Yojana",icon:"💳",s:"kisan credit card (kcc) short-term agricultural loans at just 4% interest (after government subsidy) — the cheapest borrowing option for indian farmers agriculture loan kcc credit card farmer interest subsidy"},
  {url:"/yojana/pm-kisan",title:"PM Kisan Samman Nidhi",desc:"Direct income support of ₹6,000 per year for all landholding farmer families — India\'s largest Direct Benefit Transfer s",cat:"Yojana",icon:"🌾",s:"pm kisan samman nidhi direct income support of ₹6,000 per year for all landholding farmer families — india\'s largest direct benefit transfer scheme agriculture farmers dbt central government income support"},
  {url:"/yojana/pm-kusum-yojana",title:"PM KUSUM Yojana",desc:"Solar energy for farmers — get solar water pumps at 60-90% subsidy and earn money by selling solar power to the grid",cat:"Yojana",icon:"☀️",s:"pm kusum yojana solar energy for farmers — get solar water pumps at 60-90% subsidy and earn money by selling solar power to the grid solar agriculture irrigation subsidy renewable energy central government"},
  {url:"/yojana/pm-mudra-yojana",title:"PM Mudra Yojana",desc:"Collateral-free loans from ₹50,000 to ₹10 lakh for small businesses, street vendors, artisans, and micro-entrepreneurs —",cat:"Yojana",icon:"🏪",s:"pm mudra yojana collateral-free loans from ₹50,000 to ₹10 lakh for small businesses, street vendors, artisans, and micro-entrepreneurs — no guarantor needed business loan msme self-employment collateral-free central government"},
  {url:"/yojana/pm-shram-yogi-maandhan",title:"PM Shram Yogi Maandhan",desc:"Guaranteed ₹3,000/month pension after age 60 for unorganized sector workers — government contributes equally to your mon",cat:"Yojana",icon:"👷",s:"pm shram yogi maandhan guaranteed ₹3,000/month pension after age 60 for unorganized sector workers — government contributes equally to your monthly deposit pension unorganized sector government matching monthly pension central government"},
  {url:"/yojana/pm-suraksha-bima-yojana",title:"PM Suraksha Bima Yojana",desc:"₹2 lakh accidental death and disability insurance for just ₹20 per year — India\'s cheapest accident cover for all bank a",cat:"Yojana",icon:"🛡️",s:"pm suraksha bima yojana ₹2 lakh accidental death and disability insurance for just ₹20 per year — india\'s cheapest accident cover for all bank account holders insurance accident ₹20 central government pmsby"},
  {url:"/yojana/pm-surya-ghar",title:"PM Surya Ghar Yojana — Free Solar Rooftop",desc:"Up to ₹78,000 government subsidy on rooftop solar panels — generate free electricity and reduce your monthly electricity",cat:"Yojana",icon:"☀️",s:"pm surya ghar yojana — free solar rooftop up to ₹78,000 government subsidy on rooftop solar panels — generate free electricity and reduce your monthly electricity bill to near-zero solar rooftop free electricity subsidy green energy central government"},
  {url:"/yojana/pm-svanidhi",title:"PM SVANidhi — Street Vendor Loan Scheme",desc:"Collateral-free working capital loans for street vendors — ₹10,000 first loan, up to ₹50,000 third loan, with 7% interes",cat:"Yojana",icon:"🛒",s:"pm svanidhi — street vendor loan scheme collateral-free working capital loans for street vendors — ₹10,000 first loan, up to ₹50,000 third loan, with 7% interest subsidy street vendor micro credit loan urban poor central government"},
  {url:"/yojana/pm-ujjwala-yojana",title:"PM Ujjwala Yojana",desc:"Free LPG gas connection for women from Below Poverty Line households — eliminating indoor air pollution from traditional",cat:"Yojana",icon:"🔥",s:"pm ujjwala yojana free lpg gas connection for women from below poverty line households — eliminating indoor air pollution from traditional cooking fuels lpg women bpl welfare central government clean cooking"},
  {url:"/yojana/pm-vishwakarma-yojana",title:"PM Vishwakarma Yojana",desc:"Free skill training, modern toolkits, and collateral-free loans up to ₹3 lakh for traditional artisans and craftspeople ",cat:"Yojana",icon:"🔨",s:"pm vishwakarma yojana free skill training, modern toolkits, and collateral-free loans up to ₹3 lakh for traditional artisans and craftspeople across 18 trades artisan craftspeople skill training loan toolkit central government"},
  {url:"/yojana/pmkvy-skill-india",title:"PMKVY — Skill India Free Training & Certification",desc:"Free skill training and certification in 200+ trades — from IT to plumbing to beauty to accounting — with stipend and pl",cat:"Yojana",icon:"🎓",s:"pmkvy — skill india free training & certification free skill training and certification in 200+ trades — from it to plumbing to beauty to accounting — with stipend and placement assistance skill training pmkvy free course certification placement skill india"},
  {url:"/yojana/rythu-bandhu",title:"Rythu Bandhu (Telangana) — ₹10,000/Acre for Farmers",desc:"Telangana\'s farmer investment support — ₹10,000 per acre per year (₹5,000 each for kharif and rabi seasons) for all land",cat:"Yojana",icon:"🌾",s:"rythu bandhu (telangana) — ₹10,000/acre for farmers telangana\'s farmer investment support — ₹10,000 per acre per year (₹5,000 each for kharif and rabi seasons) for all land-owning farmers telangana farmer agriculture state scheme rythu bandhu per acre"},
  {url:"/yojana/senior-citizen-savings-scheme",title:"Senior Citizen Savings Scheme (SCSS)",desc:"8.2% guaranteed interest with quarterly payouts for senior citizens — the safest and highest-return investment option fo",cat:"Yojana",icon:"🏦",s:"senior citizen savings scheme (scss) 8.2% guaranteed interest with quarterly payouts for senior citizens — the safest and highest-return investment option for retirees senior citizens savings retirement quarterly income post office 80c"},
  {url:"/yojana/sikho-kamao-yojana",title:"Mukhyamantri Sikho Kamao Yojana (MP) — Learn & Earn",desc:"Madhya Pradesh\'s learn-and-earn scheme — youth aged 18-29 get placed at companies for on-the-job training with ₹8,000-10",cat:"Yojana",icon:"🎓",s:"mukhyamantri sikho kamao yojana (mp) — learn & earn madhya pradesh\'s learn-and-earn scheme — youth aged 18-29 get placed at companies for on-the-job training with ₹8,000-10,000 monthly stipend from government madhya pradesh skill training stipend youth state scheme employment"},
  {url:"/yojana/stand-up-india",title:"Stand Up India Scheme",desc:"Bank loans from ₹10 lakh to ₹1 crore specifically for SC/ST and women entrepreneurs to start greenfield enterprises",cat:"Yojana",icon:"🚀",s:"stand up india scheme bank loans from ₹10 lakh to ₹1 crore specifically for sc/st and women entrepreneurs to start greenfield enterprises business loan sc/st women entrepreneurship central government"},
  {url:"/yojana/startup-india",title:"Startup India — Registration, Benefits & Tax Exemption",desc:"Get your startup recognized by DPIIT for 3-year income tax exemption, easier compliance, fast-track patents, and access ",cat:"Yojana",icon:"🚀",s:"startup india — registration, benefits & tax exemption get your startup recognized by dpiit for 3-year income tax exemption, easier compliance, fast-track patents, and access to ₹10,000 crore fund of funds startup dpiit tax exemption innovation entrepreneurship central government"},
  {url:"/yojana/sukanya-samriddhi-yojana",title:"Sukanya Samriddhi Yojana",desc:"Government-backed savings scheme for girl child with 8.2% interest — highest among all small savings schemes, with compl",cat:"Yojana",icon:"👧",s:"sukanya samriddhi yojana government-backed savings scheme for girl child with 8.2% interest — highest among all small savings schemes, with complete tax exemption savings girl child tax free post office beti bachao section 80c"},
  {url:"/yojana/up-shramik-card",title:"UP Shramik Card (Labour Card) — Registration & Benefits",desc:"UP Building and Construction Workers Registration — unlocks 15+ welfare benefits including ₹55,000 for daughter\'s marria",cat:"Yojana",icon:"👷",s:"up shramik card (labour card) — registration & benefits up building and construction workers registration — unlocks 15+ welfare benefits including ₹55,000 for daughter\'s marriage, ₹25,000 for housing, and medical aid uttar pradesh labour construction worker shramik card state scheme welfare"},
  {url:"/exam/afcat",title:"AFCAT 2026 — Air Force Common Admission Test",desc:"Officer entry into the Indian Air Force through AFCAT — Flying Branch (pilots), Technical Branch (engineers), and Ground",cat:"Exam",icon:"✈️",s:"afcat 2026 — air force common admission test officer entry into the indian air force through afcat — flying branch (pilots), technical branch (engineers), and ground duty branch (admin/logistics) afcat air force iaf pilot flying defence"},
  {url:"/exam/appsc",title:"APPSC Group 1/2 2026 — Andhra Pradesh State Services",desc:"Andhra Pradesh state civil services — Group 1 for Deputy Collector/DSP, Group 2 for Tehsildar/Municipal Commissioner thr",cat:"Exam",icon:"🏛️",s:"appsc group 1/2 2026 — andhra pradesh state services andhra pradesh state civil services — group 1 for deputy collector/dsp, group 2 for tehsildar/municipal commissioner through appsc appsc andhra pradesh state psc civil services group 1"},
  {url:"/exam/bpsc",title:"BPSC 2026 — Bihar Civil Services Exam",desc:"Bihar\'s state civil services exam — become SDM, DSP, Circle Officer, or District Officer through BPSC Combined Competiti",cat:"Exam",icon:"🏛️",s:"bpsc 2026 — bihar civil services exam bihar\'s state civil services exam — become sdm, dsp, circle officer, or district officer through bpsc combined competitive exam bpsc bihar state psc civil services sdm dsp"},
  {url:"/exam/cat-2026",title:"CAT 2026 — MBA Entrance Exam",desc:"Common Admission Test — the gateway to 20 IIMs and 1,200+ MBA colleges. India\'s most prestigious management entrance exa",cat:"Exam",icon:"🎯",s:"cat 2026 — mba entrance exam common admission test — the gateway to 20 iims and 1,200+ mba colleges. india\'s most prestigious management entrance exam. cat mba iim management nta"},
  {url:"/exam/cgpsc",title:"CGPSC 2026 — Chhattisgarh State Services",desc:"Chhattisgarh state civil services — become Deputy Collector, DSP, or Tehsildar through CGPSC State Services Examination",cat:"Exam",icon:"🏛️",s:"cgpsc 2026 — chhattisgarh state services chhattisgarh state civil services — become deputy collector, dsp, or tehsildar through cgpsc state services examination cgpsc chhattisgarh state psc civil services"},
  {url:"/exam/clat-2026",title:"CLAT 2026 — Law Entrance Exam",desc:"Common Law Admission Test — gateway to 22 National Law Universities including NLSIU Bangalore, NALSAR Hyderabad, and NLU",cat:"Exam",icon:"⚖️",s:"clat 2026 — law entrance exam common law admission test — gateway to 22 national law universities including nlsiu bangalore, nalsar hyderabad, and nlu delhi clat law nlu ba llb legal"},
  {url:"/exam/ctet",title:"CTET 2026",desc:"Mandatory eligibility test for teaching positions in Kendriya Vidyalayas, Navodaya Vidyalayas, and other central governm",cat:"Exam",icon:"📚",s:"ctet 2026 mandatory eligibility test for teaching positions in kendriya vidyalayas, navodaya vidyalayas, and other central government schools ctet teaching kvs nvs cbse primary teacher tgt"},
  {url:"/exam/cuet-ug",title:"CUET UG 2026",desc:"Single entrance exam for admission to 200+ central and participating universities including Delhi University, JNU, BHU, ",cat:"Exam",icon:"🏫",s:"cuet ug 2026 single entrance exam for admission to 200+ central and participating universities including delhi university, jnu, bhu, jamia millia, and amu cuet university du jnu bhu nta undergraduate"},
  {url:"/exam/gate",title:"GATE 2026",desc:"India\'s premier engineering entrance exam — gateway to M.Tech at IITs and direct recruitment to PSUs like ONGC, IOCL, NT",cat:"Exam",icon:"⚙️",s:"gate 2026 india\'s premier engineering entrance exam — gateway to m.tech at iits and direct recruitment to psus like ongc, iocl, ntpc, bhel at ₹40-80k/month gate engineering psu m.tech iit research"},
  {url:"/exam/hpsc",title:"HPSC HCS 2026 — Haryana Civil Services",desc:"Haryana\'s state civil services exam — SDM, DSP, Excise & Taxation Officer through HPSC Combined Competitive Examination",cat:"Exam",icon:"🏛️",s:"hpsc hcs 2026 — haryana civil services haryana\'s state civil services exam — sdm, dsp, excise & taxation officer through hpsc combined competitive examination hpsc hcs haryana state psc civil services"},
  {url:"/exam/ibps-clerk",title:"IBPS Clerk 2026",desc:"Clerical cadre recruitment for 11 public sector banks — one of the easiest banking exams with good salary and promotion ",cat:"Exam",icon:"🏦",s:"ibps clerk 2026 clerical cadre recruitment for 11 public sector banks — one of the easiest banking exams with good salary and promotion to officer grade banking ibps clerk junior associate public sector bank"},
  {url:"/exam/ibps-po",title:"IBPS PO 2026",desc:"Probationary Officer recruitment for 11 public sector banks — one of India\'s most popular banking exams with excellent s",cat:"Exam",icon:"🏦",s:"ibps po 2026 probationary officer recruitment for 11 public sector banks — one of india\'s most popular banking exams with excellent salary and career growth banking ibps probationary officer po public sector bank"},
  {url:"/exam/jee-main",title:"JEE Main 2026",desc:"India\'s largest engineering entrance exam — gateway to 31 NITs, 26 IIITs, and 33 GFTIs, plus eligibility for JEE Advance",cat:"Exam",icon:"🔬",s:"jee main 2026 india\'s largest engineering entrance exam — gateway to 31 nits, 26 iiits, and 33 gftis, plus eligibility for jee advanced (iit admission) jee engineering nit iiit nta b.tech"},
  {url:"/exam/jpsc",title:"JPSC 2026 — Jharkhand Civil Services Exam",desc:"Jharkhand state civil services — Deputy Collector, DSP, BDO positions through JPSC Combined Competitive Examination",cat:"Exam",icon:"🏛️",s:"jpsc 2026 — jharkhand civil services exam jharkhand state civil services — deputy collector, dsp, bdo positions through jpsc combined competitive examination jpsc jharkhand state psc civil services tribal"},
  {url:"/exam/kpsc",title:"KPSC KAS 2026 — Karnataka Administrative Service",desc:"Karnataka\'s state civil services exam — become Deputy Commissioner, Superintendent of Police, or Tahsildar through KPSC ",cat:"Exam",icon:"🏛️",s:"kpsc kas 2026 — karnataka administrative service karnataka\'s state civil services exam — become deputy commissioner, superintendent of police, or tahsildar through kpsc competitive exam kpsc kas karnataka state psc civil services"},
  {url:"/exam/lic-aao",title:"LIC AAO 2026 — Assistant Administrative Officer",desc:"Officer-level entry at India\'s largest insurer — LIC AAO combines the prestige of a government job with insurance sector",cat:"Exam",icon:"🏢",s:"lic aao 2026 — assistant administrative officer officer-level entry at india\'s largest insurer — lic aao combines the prestige of a government job with insurance sector salary and perks lic aao insurance officer government corporation"},
  {url:"/exam/mppsc",title:"MPPSC 2026 — MP State Services Exam",desc:"Madhya Pradesh\'s state civil services exam — gateway to DSP, Naib Tehsildar, BDO, and other Group A/B state administrati",cat:"Exam",icon:"🏛️",s:"mppsc 2026 — mp state services exam madhya pradesh\'s state civil services exam — gateway to dsp, naib tehsildar, bdo, and other group a/b state administration posts mppsc madhya pradesh state psc civil services dsp naib tehsildar"},
  {url:"/exam/nda",title:"NDA Exam 2026",desc:"Gateway to Indian Armed Forces as an officer — join Army, Navy, or Air Force through India\'s premier defence training ac",cat:"Exam",icon:"⭐",s:"nda exam 2026 gateway to indian armed forces as an officer — join army, navy, or air force through india\'s premier defence training academy after 12th nda defence army navy air force upsc officer"},
  {url:"/exam/neet-ug",title:"NEET UG 2026",desc:"India\'s single medical entrance exam — NEET UG is the only gateway to MBBS, BDS, and AYUSH admissions in all government ",cat:"Exam",icon:"⚕️",s:"neet ug 2026 india\'s single medical entrance exam — neet ug is the only gateway to mbbs, bds, and ayush admissions in all government and private medical colleges neet medical mbbs bds nta doctor"},
  {url:"/exam/rbi-grade-b",title:"RBI Grade B 2026 — Officers in Reserve Bank of India",desc:"One of India\'s most elite exams — become an officer at the Reserve Bank of India with ₹1 lakh+ monthly salary, Mumbai po",cat:"Exam",icon:"🏛️",s:"rbi grade b 2026 — officers in reserve bank of india one of india\'s most elite exams — become an officer at the reserve bank of india with ₹1 lakh+ monthly salary, mumbai posting, and unmatched job prestige rbi grade b central bank banking economics elite exam"},
  {url:"/exam/reet",title:"REET 2026 — Rajasthan Teacher Eligibility Test",desc:"Rajasthan\'s teacher eligibility test — mandatory for government school teaching in Rajasthan. Level 1 for primary, Level",cat:"Exam",icon:"📚",s:"reet 2026 — rajasthan teacher eligibility test rajasthan\'s teacher eligibility test — mandatory for government school teaching in rajasthan. level 1 for primary, level 2 for upper primary. reet rajasthan teacher bser primary upper primary"},
  {url:"/exam/rpsc-ras",title:"RPSC RAS 2026 — Rajasthan Administrative Services",desc:"Rajasthan\'s prestigious state civil services exam — become RAS officer (SDM equivalent), RPS (DSP equivalent), or RTS of",cat:"Exam",icon:"🏛️",s:"rpsc ras 2026 — rajasthan administrative services rajasthan\'s prestigious state civil services exam — become ras officer (sdm equivalent), rps (dsp equivalent), or rts officer in state administration rpsc ras rajasthan state psc civil services rps"},
  {url:"/exam/rrb-group-d",title:"RRB Group D 2026",desc:"Level 1 posts in Indian Railways — Track Maintainer, Helper, Porter, and Gateman for 10th pass candidates with ITI prefe",cat:"Exam",icon:"🔧",s:"rrb group d 2026 level 1 posts in indian railways — track maintainer, helper, porter, and gateman for 10th pass candidates with iti preferred railway rrb group d 10th pass track maintainer indian railways"},
  {url:"/exam/rrb-ntpc",title:"RRB NTPC 2026",desc:"Railway recruitment for Non-Technical Popular Categories — Station Master, Goods Guard, Clerk, and other posts across In",cat:"Exam",icon:"🚂",s:"rrb ntpc 2026 railway recruitment for non-technical popular categories — station master, goods guard, clerk, and other posts across indian railways railway rrb ntpc station master goods guard indian railways"},
  {url:"/exam/sbi-po",title:"SBI PO 2026",desc:"Probationary Officer at India\'s largest bank — SBI PO offers the best salary, brand value, and career growth in public s",cat:"Exam",icon:"🏦",s:"sbi po 2026 probationary officer at india\'s largest bank — sbi po offers the best salary, brand value, and career growth in public sector banking banking sbi probationary officer po state bank of india"},
  {url:"/exam/ssc-cgl-2026",title:"SSC CGL 2026",desc:"Combined Graduate Level Examination 2026 — India\'s most popular exam for Group B and Group C government posts across cen",cat:"Exam",icon:"🎯",s:"ssc cgl 2026 combined graduate level examination 2026 — india\'s most popular exam for group b and group c government posts across central ministries ssc cgl graduate level central government group b group c"},
  {url:"/exam/ssc-chsl",title:"SSC CHSL 2026",desc:"Government jobs for 12th pass candidates — LDC, Postal Assistant, Data Entry Operator, and Sorting Assistant in central ",cat:"Exam",icon:"📬",s:"ssc chsl 2026 government jobs for 12th pass candidates — ldc, postal assistant, data entry operator, and sorting assistant in central government departments ssc chsl 12th pass ldc postal assistant deo group c"},
  {url:"/exam/ssc-cpo",title:"SSC CPO 2026 — Sub Inspector Exam",desc:"Sub Inspector recruitment in Delhi Police, Central Armed Police Forces (BSF, CRPF, ITBP, CISF, SSB) and Assistant Sub In",cat:"Exam",icon:"🚔",s:"ssc cpo 2026 — sub inspector exam sub inspector recruitment in delhi police, central armed police forces (bsf, crpf, itbp, cisf, ssb) and assistant sub inspector in cisf ssc cpo sub inspector delhi police capf"},
  {url:"/exam/ssc-gd-constable",title:"SSC GD Constable 2026",desc:"Constable (GD) recruitment in Central Armed Police Forces — BSF, CRPF, CISF, ITBP, SSB, NIA, SSF, and Assam Rifles",cat:"Exam",icon:"🛡️",s:"ssc gd constable 2026 constable (gd) recruitment in central armed police forces — bsf, crpf, cisf, itbp, ssb, nia, ssf, and assam rifles ssc gd constable capf bsf crpf cisf defence 10th pass"},
  {url:"/exam/ssc-mts",title:"SSC MTS 2026",desc:"Government jobs for 10th pass — Multi Tasking Staff (Group C) posts in central government ministries, offices, and depar",cat:"Exam",icon:"🏢",s:"ssc mts 2026 government jobs for 10th pass — multi tasking staff (group c) posts in central government ministries, offices, and departments across india ssc mts 10th pass group c central government multi tasking staff"},
  {url:"/exam/tnpsc",title:"TNPSC Group 1/2/2A 2026 — Tamil Nadu State Services",desc:"Tamil Nadu\'s state civil services exams — Group 1 for Deputy Collector/DSP, Group 2 for Sub-Registrar/Municipal Commissi",cat:"Exam",icon:"🏛️",s:"tnpsc group 1/2/2a 2026 — tamil nadu state services tamil nadu\'s state civil services exams — group 1 for deputy collector/dsp, group 2 for sub-registrar/municipal commissioner, group 2a for other state posts tnpsc tamil nadu state psc group 1 group 2 civil services"},
  {url:"/exam/ugc-net",title:"UGC NET 2026",desc:"National Eligibility Test for Assistant Professor positions in Indian universities and colleges + Junior Research Fellow",cat:"Exam",icon:"🎓",s:"ugc net 2026 national eligibility test for assistant professor positions in indian universities and colleges + junior research fellowship for phd scholars ugc net assistant professor jrf research nta university"},
  {url:"/exam/ukpsc",title:"UKPSC 2026 — Uttarakhand PCS Exam",desc:"Uttarakhand\'s state civil services exam — become SDM, Naib Tehsildar, or BDO in the Dev Bhoomi through UKPSC Combined Co",cat:"Exam",icon:"🏔️",s:"ukpsc 2026 — uttarakhand pcs exam uttarakhand\'s state civil services exam — become sdm, naib tehsildar, or bdo in the dev bhoomi through ukpsc combined competitive exam ukpsc uttarakhand state psc civil services naib tehsildar bdo"},
  {url:"/exam/uppsc-pcs",title:"UPPSC PCS 2026 — UP Civil Services Exam",desc:"Uttar Pradesh\'s premier civil services exam — gateway to becoming SDM, DSP, BDO, Treasury Officer, and other state admin",cat:"Exam",icon:"🏛️",s:"uppsc pcs 2026 — up civil services exam uttar pradesh\'s premier civil services exam — gateway to becoming sdm, dsp, bdo, treasury officer, and other state administration posts uppsc pcs up civil services sdm dsp state psc"},
  {url:"/exam/upsc-cse",title:"UPSC Civil Services 2026",desc:"India\'s most prestigious examination — gateway to IAS, IPS, IFS, and 20+ other All India and Central Services",cat:"Exam",icon:"🏆",s:"upsc civil services 2026 india\'s most prestigious examination — gateway to ias, ips, ifs, and 20+ other all india and central services upsc ias ips ifs civil services group a government"},
  {url:"/exam/upsc-nda-na",title:"UPSC CDS 2026",desc:"Officer entry into Indian Armed Forces for graduates — join IMA, Naval Academy, Air Force Academy, or Officers Training ",cat:"Exam",icon:"🎖️",s:"upsc cds 2026 officer entry into indian armed forces for graduates — join ima, naval academy, air force academy, or officers training academy through upsc cds defence army navy air force upsc officer ima ota"},
  {url:"/exam/uptet",title:"UPTET 2026 — UP Teacher Eligibility Test",desc:"Mandatory qualification for teaching in Uttar Pradesh government schools — Paper 1 for Classes 1-5 (Primary), Paper 2 fo",cat:"Exam",icon:"📚",s:"uptet 2026 — up teacher eligibility test mandatory qualification for teaching in uttar pradesh government schools — paper 1 for classes 1-5 (primary), paper 2 for classes 6-8 (upper primary) uptet up teacher teaching primary upper primary uttar pradesh"},
  {url:"/exam/wbpsc",title:"WBPSC 2026 — West Bengal Civil Service Exam",desc:"West Bengal\'s state civil services exam — WBCS Executive for BDO, SDO, Deputy Magistrate and WBCS Judicial for Civil Jud",cat:"Exam",icon:"🏛️",s:"wbpsc 2026 — west bengal civil service exam west bengal\'s state civil services exam — wbcs executive for bdo, sdo, deputy magistrate and wbcs judicial for civil judge positions wbpsc wbcs west bengal state psc civil services"},
  {url:"/paisa/credit-score-guide",title:"Credit Score (CIBIL) — Complete Guide",desc:"Your 3-digit CIBIL score (300-900) determines whether banks approve your loan, what interest rate you get, and which cre",cat:"Paisa",icon:"📊",s:"credit score (cibil) — complete guide your 3-digit cibil score (300-900) determines whether banks approve your loan, what interest rate you get, and which credit cards you\'re eligible for cibil credit score loan credit card banking financial literacy"},
  {url:"/paisa/demat-account-guide",title:"Demat Account — How to Open and Start Investing",desc:"A demat account holds your stocks and securities electronically — your gateway to investing in shares, mutual funds, bon",cat:"Paisa",icon:"📱",s:"demat account — how to open and start investing a demat account holds your stocks and securities electronically — your gateway to investing in shares, mutual funds, bonds, etfs, and ipos on nse and bse demat stock market trading investing zerodha groww nse bse"},
  {url:"/paisa/education-loan-guide",title:"Education Loan Guide — How to Fund Your Studies",desc:"Fund your higher education without burdening family — education loans cover tuition, hostel, books, and laptop with repa",cat:"Paisa",icon:"🎓",s:"education loan guide — how to fund your studies fund your higher education without burdening family — education loans cover tuition, hostel, books, and laptop with repayment starting only after you get a job education loan student loan 80e vidyalakshmi interest subsidy"},
  {url:"/paisa/epf-withdrawal",title:"EPF Withdrawal — Complete Guide",desc:"How to withdraw your Employees\' Provident Fund money — online process, advance withdrawal for specific needs, and rules ",cat:"Paisa",icon:"💼",s:"epf withdrawal — complete guide how to withdraw your employees\' provident fund money — online process, advance withdrawal for specific needs, and rules for full settlement after leaving a job epf provident fund withdrawal epfo employment retirement"},
  {url:"/paisa/gold-investment-guide",title:"Gold Investment Guide — Best Ways to Buy Gold in India",desc:"Sovereign Gold Bonds give you gold returns PLUS 2.5% guaranteed interest — the smartest way to invest in gold in India w",cat:"Paisa",icon:"🪙",s:"gold investment guide — best ways to buy gold in india sovereign gold bonds give you gold returns plus 2.5% guaranteed interest — the smartest way to invest in gold in india with zero storage hassle gold sgb gold etf digital gold investment safe haven"},
  {url:"/paisa/gratuity-guide",title:"Gratuity — Calculation, Eligibility & Tax Rules",desc:"Gratuity is a retirement benefit your employer MUST pay after 5 years of service — calculated as 15 days salary × years ",cat:"Paisa",icon:"💼",s:"gratuity — calculation, eligibility & tax rules gratuity is a retirement benefit your employer must pay after 5 years of service — calculated as 15 days salary × years of service. tax-free up to ₹25 lakh. gratuity employment retirement tax free labour law"},
  {url:"/paisa/health-insurance-guide",title:"Health Insurance Guide — How to Choose the Right Plan",desc:"A ₹10-20 lakh health insurance plan costs ₹8,000-25,000/year and can save you from financial ruin in case of hospitaliza",cat:"Paisa",icon:"🏥",s:"health insurance guide — how to choose the right plan a ₹10-20 lakh health insurance plan costs ₹8,000-25,000/year and can save you from financial ruin in case of hospitalization — india\'s most essential insurance after term health insurance mediclaim 80d cashless family floater irdai"},
  {url:"/paisa/home-loan-guide",title:"Home Loan Guide — Eligibility, EMI, and How to Get Lowest Rate",desc:"Everything you need to know before taking a home loan — eligibility, EMI calculation, comparing banks, hidden charges, a",cat:"Paisa",icon:"🏠",s:"home loan guide — eligibility, emi, and how to get lowest rate everything you need to know before taking a home loan — eligibility, emi calculation, comparing banks, hidden charges, and how to save lakhs on interest home loan emi mortgage real estate banking tax benefit"},
  {url:"/paisa/how-to-file-itr",title:"How to File ITR — Income Tax Return Guide",desc:"Complete step-by-step guide to filing your Income Tax Return online on the e-filing portal — with form selection, deduct",cat:"Paisa",icon:"📄",s:"how to file itr — income tax return guide complete step-by-step guide to filing your income tax return online on the e-filing portal — with form selection, deductions, and deadline reminders income tax itr tax filing 80c e-filing tax return"},
  {url:"/paisa/hra-exemption-guide",title:"HRA Exemption — How to Calculate and Claim",desc:"If you pay rent and receive HRA from your employer, you can claim significant tax exemption — potentially saving ₹50,000",cat:"Paisa",icon:"🏠",s:"hra exemption — how to calculate and claim if you pay rent and receive hra from your employer, you can claim significant tax exemption — potentially saving ₹50,000-1,50,000 in annual tax hra tax exemption rent salary old tax regime"},
  {url:"/paisa/nps-vs-ppf",title:"NPS vs PPF — Which is Better for You?",desc:"NPS gives higher returns (8-12%) + extra ₹50K tax deduction, PPF gives guaranteed 7.1% completely tax-free — the best re",cat:"Paisa",icon:"⚖️",s:"nps vs ppf — which is better for you? nps gives higher returns (8-12%) + extra ₹50k tax deduction, ppf gives guaranteed 7.1% completely tax-free — the best retirement strategy uses both nps ppf comparison retirement tax saving investment"},
  {url:"/paisa/personal-loan-guide",title:"Personal Loan Guide — When to Take and When to Avoid",desc:"Personal loans are the most expensive unsecured debt — 10-24% interest. Know when they make sense, when they don\'t, and ",cat:"Paisa",icon:"💳",s:"personal loan guide — when to take and when to avoid personal loans are the most expensive unsecured debt — 10-24% interest. know when they make sense, when they don\'t, and cheaper alternatives. personal loan interest rate banking unsecured loan emi"},
  {url:"/paisa/ppf-guide",title:"Public Provident Fund (PPF) — Complete Guide",desc:"India\'s safest long-term investment — 7.1% guaranteed tax-free returns with complete EEE tax status and government backi",cat:"Paisa",icon:"🏦",s:"public provident fund (ppf) — complete guide india\'s safest long-term investment — 7.1% guaranteed tax-free returns with complete eee tax status and government backing ppf savings tax free 80c post office government backed"},
  {url:"/paisa/section-80c-guide",title:"Section 80C Guide — Save Up to ₹46,800 Tax",desc:"Save up to ₹46,800 in income tax by investing ₹1.5 lakh under Section 80C — complete guide to every eligible investment ",cat:"Paisa",icon:"💰",s:"section 80c guide — save up to ₹46,800 tax save up to ₹46,800 in income tax by investing ₹1.5 lakh under section 80c — complete guide to every eligible investment and the smartest allocation strategy tax saving 80c investment ppf elss epf income tax"},
  {url:"/paisa/section-80d-guide",title:"Section 80D — Health Insurance Tax Benefit Guide",desc:"Save up to ₹1 lakh in tax deductions by paying health insurance premiums for yourself, family, and parents under Section",cat:"Paisa",icon:"🏥",s:"section 80d — health insurance tax benefit guide save up to ₹1 lakh in tax deductions by paying health insurance premiums for yourself, family, and parents under section 80d 80d health insurance tax deduction senior citizen medical"},
  {url:"/paisa/sip-vs-fd-vs-ppf",title:"SIP vs FD vs PPF — Where to Invest?",desc:"Three pillars of Indian investing compared — SIP for growth, FD for safety, PPF for tax-free guaranteed returns. Which c",cat:"Paisa",icon:"📊",s:"sip vs fd vs ppf — where to invest? three pillars of indian investing compared — sip for growth, fd for safety, ppf for tax-free guaranteed returns. which combination works best for you? sip fd ppf comparison investment beginner"},
  {url:"/paisa/term-insurance-guide",title:"Term Insurance Guide — Cheapest Life Cover",desc:"₹1 crore life insurance for just ₹500-1,500/month — the cheapest way to financially protect your family against the wors",cat:"Paisa",icon:"🛡️",s:"term insurance guide — cheapest life cover ₹1 crore life insurance for just ₹500-1,500/month — the cheapest way to financially protect your family against the worst-case scenario term insurance life insurance protection family premium irdai"},
  {url:"/paisa/upi-guide",title:"UPI — Complete Guide to India\'s Digital Payment System",desc:"Everything about UPI — from setting up to troubleshooting failed transactions. The system that processes 12+ billion tra",cat:"Paisa",icon:"📱",s:"upi — complete guide to india\'s digital payment system everything about upi — from setting up to troubleshooting failed transactions. the system that processes 12+ billion transactions monthly. upi digital payment npci phonepe google pay banking"},
  {url:"/paisa/what-is-elss",title:"What is ELSS? — Tax Saving Mutual Fund Guide",desc:"The smartest Section 80C investment — equity mutual fund that saves tax AND generates 12-15% returns with the shortest l",cat:"Paisa",icon:"📈",s:"what is elss? — tax saving mutual fund guide the smartest section 80c investment — equity mutual fund that saves tax and generates 12-15% returns with the shortest lock-in of just 3 years elss tax saving 80c mutual fund equity sip"},
  {url:"/paisa/what-is-fd",title:"What is a Fixed Deposit (FD)?",desc:"The simplest and safest investment in India — deposit a lump sum for a fixed period and earn guaranteed interest from 6.",cat:"Paisa",icon:"🏦",s:"what is a fixed deposit (fd)? the simplest and safest investment in india — deposit a lump sum for a fixed period and earn guaranteed interest from 6.5% to 7.5% per annum fixed deposit fd savings interest rate bank dicgc"},
  {url:"/paisa/what-is-mutual-fund",title:"What is a Mutual Fund? — Beginner\'s Guide",desc:"Pool your money with lakhs of other investors and let professional fund managers invest it in stocks, bonds, or gold — s",cat:"Paisa",icon:"📈",s:"what is a mutual fund? — beginner\'s guide pool your money with lakhs of other investors and let professional fund managers invest it in stocks, bonds, or gold — starting from just ₹100/month mutual fund sip equity debt investing sebi beginner"},
  {url:"/paisa/what-is-sip",title:"What is SIP?",desc:"Invest a small fixed amount every month in mutual funds — and let compounding build your wealth over time",cat:"Paisa",icon:"📈",s:"what is sip? invest a small fixed amount every month in mutual funds — and let compounding build your wealth over time investing basics sip mutual funds beginner wealth creation"},
  {url:"/guide/aadhaar-update",title:"How to Update Aadhaar Card Online — Step by Step",desc:"Update your Aadhaar details — name, address, date of birth, mobile number, email, or photo — online through the UIDAI po",cat:"Guide",icon:"🆔",s:"how to update aadhaar card online — step by step update your aadhaar details — name, address, date of birth, mobile number, email, or photo — online through the uidai portal in 10 minutes aadhaar uidai identity update address change"},
  {url:"/guide/activate-uan",title:"How to Activate UAN — EPF Universal Account Number",desc:"Your UAN (Universal Account Number) is the key to all EPF online services — balance check, withdrawal, transfer. Here is",cat:"Guide",icon:"🔑",s:"how to activate uan — epf universal account number your uan (universal account number) is the key to all epf online services — balance check, withdrawal, transfer. here is how to activate it in 5 minutes. epf finance"},
  {url:"/guide/apply-caste-certificate",title:"How to Apply for Caste Certificate Online",desc:"Caste certificate (SC/ST/OBC) is required for reservation in government jobs, college admissions, and scheme eligibility",cat:"Guide",icon:"📜",s:"how to apply for caste certificate online caste certificate (sc/st/obc) is required for reservation in government jobs, college admissions, and scheme eligibility — apply online through your state portal caste certificate sc st obc reservation certificate"},
  {url:"/guide/apply-domicile-certificate",title:"How to Apply for Domicile Certificate Online",desc:"Domicile certificate proves your permanent residence in a state — required for state government jobs, college admissions",cat:"Guide",icon:"📃",s:"how to apply for domicile certificate online domicile certificate proves your permanent residence in a state — required for state government jobs, college admissions under state quota, and state scheme eligibility domicile certificate state government residence proof"},
  {url:"/guide/apply-driving-license",title:"How to Apply for Driving License Online",desc:"Apply for Learner\'s License and Permanent Driving License online through the Parivahan portal — book slot, upload docume",cat:"Guide",icon:"🚗",s:"how to apply for driving license online apply for learner\'s license and permanent driving license online through the parivahan portal — book slot, upload documents, and get dl without agent fees driving license rto parivahan transport vehicle"},
  {url:"/guide/apply-ews-certificate",title:"How to Apply for EWS Certificate Online",desc:"EWS certificate enables General category candidates with family income below ₹8 lakh/year to avail 10% reservation in go",cat:"Guide",icon:"📜",s:"how to apply for ews certificate online ews certificate enables general category candidates with family income below ₹8 lakh/year to avail 10% reservation in government jobs and educational institutions ews certificate reservation general category 10 percent"},
  {url:"/guide/apply-income-certificate",title:"How to Apply for Income Certificate Online",desc:"Income certificate proves your annual family income — required for government scheme eligibility, college admissions, an",cat:"Guide",icon:"📃",s:"how to apply for income certificate online income certificate proves your annual family income — required for government scheme eligibility, college admissions, and job applications income certificate revenue sdm tehsildar government"},
  {url:"/guide/apply-obc-certificate",title:"How to Apply for OBC Certificate & Non-Creamy Layer",desc:"OBC certificate + Non-Creamy Layer certificate is required for availing 27% OBC reservation in government jobs and educa",cat:"Guide",icon:"📜",s:"how to apply for obc certificate & non-creamy layer obc certificate + non-creamy layer certificate is required for availing 27% obc reservation in government jobs and education — apply through your state e-district portal obc non-creamy layer certificate reservation 27 percent"},
  {url:"/guide/apply-pan-card",title:"How to Apply for PAN Card Online — New & Reprint",desc:"Get a new PAN card in 7-15 days or an instant e-PAN in 10 minutes using Aadhaar — essential for income tax, bank account",cat:"Guide",icon:"💳",s:"how to apply for pan card online — new & reprint get a new pan card in 7-15 days or an instant e-pan in 10 minutes using aadhaar — essential for income tax, bank accounts, and investments pan card nsdl income tax identity form 49a"},
  {url:"/guide/apply-passport",title:"How to Apply for Passport Online — Fresh & Renewal",desc:"Apply for a fresh or renewed Indian passport online through the Passport Seva portal — normal processing in 30 days, tat",cat:"Guide",icon:"🛂",s:"how to apply for passport online — fresh & renewal apply for a fresh or renewed indian passport online through the passport seva portal — normal processing in 30 days, tatkal in 1-3 days passport travel mea passport seva identity"},
  {url:"/guide/check-cibil-score-free",title:"How to Check CIBIL Score Free — No Charges",desc:"Check your credit score for FREE from all 4 bureaus — CIBIL, Experian, Equifax, CRIF. RBI mandates one free report per y",cat:"Guide",icon:"📊",s:"how to check cibil score free — no charges check your credit score for free from all 4 bureaus — cibil, experian, equifax, crif. rbi mandates one free report per year from each bureau. credit score finance"},
  {url:"/guide/check-epf-balance",title:"How to Check EPF Balance — 4 Easy Methods",desc:"Check your Provident Fund balance in 30 seconds using UMANG app, EPFO portal, SMS, or missed call — no need to visit the",cat:"Guide",icon:"💰",s:"how to check epf balance — 4 easy methods check your provident fund balance in 30 seconds using umang app, epfo portal, sms, or missed call — no need to visit the pf office epf pf balance uan umang epfo"},
  {url:"/guide/check-land-records",title:"How to Check Land Records Online (Bhulekh / Bhu Naksha)",desc:"Check land ownership, khasra/khatauni records, plot maps, and property history online — every state has a free Bhulekh p",cat:"Guide",icon:"🗺️",s:"how to check land records online (bhulekh / bhu naksha) check land ownership, khasra/khatauni records, plot maps, and property history online — every state has a free bhulekh portal with digital land records land records bhulekh property khasra khatauni revenue"},
  {url:"/guide/check-ration-card",title:"How to Check Ration Card Status & Apply Online",desc:"Check your ration card status, apply for a new card, or update member details — all online through your state\'s food dep",cat:"Guide",icon:"🍚",s:"how to check ration card status & apply online check your ration card status, apply for a new card, or update member details — all online through your state\'s food department portal ration card nfsa food bpl fair price shop"},
  {url:"/guide/download-voter-id",title:"How to Download Voter ID Card (EPIC) Online",desc:"Download your digital Voter ID (e-EPIC) in PDF format from the Election Commission portal — or register as a new voter i",cat:"Guide",icon:"🗳️",s:"how to download voter id card (epic) online download your digital voter id (e-epic) in pdf format from the election commission portal — or register as a new voter if you\'ve turned 18 voter id epic elections eci registration"},
  {url:"/guide/file-consumer-complaint",title:"How to File Consumer Complaint Online — National Commission",desc:"Got cheated by a company, hospital, builder, or insurer? File a consumer complaint online at edaakhil.nic.in — the gover",cat:"Guide",icon:"⚖️",s:"how to file consumer complaint online — national commission got cheated by a company, hospital, builder, or insurer? file a consumer complaint online at edaakhil.nic.in — the government consumer court is faster than you think consumer complaint consumer court ncdrc edaakhil consumer rights"},
  {url:"/guide/file-income-tax-complaint",title:"How to File Income Tax Grievance Online",desc:"Got wrong tax demand, delayed refund, or TDS mismatch? File a grievance online at the e-Nivaran portal — response within",cat:"Guide",icon:"📋",s:"how to file income tax grievance online got wrong tax demand, delayed refund, or tds mismatch? file a grievance online at the e-nivaran portal — response within 30 days. tax grievance"},
  {url:"/guide/get-birth-certificate",title:"How to Get Birth Certificate Online",desc:"Apply for birth certificate online, download digital copy, or correct errors — through the CRS portal or your state\'s mu",cat:"Guide",icon:"👶",s:"how to get birth certificate online apply for birth certificate online, download digital copy, or correct errors — through the crs portal or your state\'s municipal corporation website birth certificate registration crs identity municipal"},
  {url:"/guide/get-marriage-certificate",title:"How to Get Marriage Certificate Online",desc:"Register your marriage and get a marriage certificate online — required for joint bank accounts, spouse visa, insurance ",cat:"Guide",icon:"💍",s:"how to get marriage certificate online register your marriage and get a marriage certificate online — required for joint bank accounts, spouse visa, insurance nomination, and property inheritance marriage certificate registration sub-registrar legal certificate"},
  {url:"/guide/link-aadhaar-bank",title:"How to Link Aadhaar with Bank Account",desc:"Link your Aadhaar with bank account for receiving government DBT payments, LPG subsidy, tax refunds, and scheme benefits",cat:"Guide",icon:"🔗",s:"how to link aadhaar with bank account link your aadhaar with bank account for receiving government dbt payments, lpg subsidy, tax refunds, and scheme benefits — 4 easy methods aadhaar bank linking dbt net banking npci"},
  {url:"/guide/link-aadhaar-pan",title:"How to Link Aadhaar with PAN — Online in 2 Minutes",desc:"Link your Aadhaar with PAN in 2 minutes online — mandatory under Section 139AA, unlinked PANs become inoperative and att",cat:"Guide",icon:"🔗",s:"how to link aadhaar with pan — online in 2 minutes link your aadhaar with pan in 2 minutes online — mandatory under section 139aa, unlinked pans become inoperative and attract ₹1,000 penalty aadhaar pan linking income tax mandatory"},
  {url:"/guide/register-digilocker",title:"How to Register on DigiLocker — Digital Document Vault",desc:"Store all your government documents digitally — Aadhaar, PAN, marksheets, driving license, vehicle RC — in one free, gov",cat:"Guide",icon:"📱",s:"how to register on digilocker — digital document vault store all your government documents digitally — aadhaar, pan, marksheets, driving license, vehicle rc — in one free, government-backed vault accessible from your phone digilocker digital india documents meity vault"},
  {url:"/guide/transfer-vehicle-rc",title:"How to Transfer Vehicle RC Online",desc:"Transfer vehicle Registration Certificate (RC) to your name after buying a used car or bike — online process through the",cat:"Guide",icon:"🚗",s:"how to transfer vehicle rc online transfer vehicle registration certificate (rc) to your name after buying a used car or bike — online process through the parivahan portal with rto visit rc transfer vehicle rto parivahan used car"},
  {url:"/compare/atal-pension-vs-nps",title:"Atal Pension Yojana vs NPS — Which Pension Plan to Choose?",desc:"APY gives guaranteed ₹1,000-5,000/month pension. NPS gives higher but uncertain pension based on market returns. Choose ",cat:"Compare",icon:"⚖️",s:"atal pension yojana vs nps — which pension plan to choose? apy gives guaranteed ₹1,000-5,000/month pension. nps gives higher but uncertain pension based on market returns. choose based on income and risk appetite. pension compare"},
  {url:"/compare/axis-vs-hdfc-credit-card",title:"Best Credit Card 2026 — HDFC vs Axis vs SBI vs ICICI",desc:"Comparing India top credit cards across rewards, cashback, lounge access, and annual fees — which card maximizes value f",cat:"Compare",icon:"💳",s:"best credit card 2026 — hdfc vs axis vs sbi vs icici comparing india top credit cards across rewards, cashback, lounge access, and annual fees — which card maximizes value for your spending pattern. credit card compare"},
  {url:"/compare/ayushman-vs-state-health",title:"Ayushman Bharat vs State Health Insurance — How They Work Together",desc:"Ayushman Bharat gives ₹5L cover nationally. State schemes give ₹5-25L within the state. Most families can use BOTH for m",cat:"Compare",icon:"⚖️",s:"ayushman bharat vs state health insurance — how they work together ayushman bharat gives ₹5l cover nationally. state schemes give ₹5-25l within the state. most families can use both for maximum coverage. health compare"},
  {url:"/compare/bank-po-vs-ssc-cgl-vs-state-psc",title:"Bank PO vs SSC CGL vs State PSC — Which Government Career Path?",desc:"Three most popular government exam categories lead to completely different careers — banking operations, central ministr",cat:"Compare",icon:"⚖️",s:"bank po vs ssc cgl vs state psc — which government career path? three most popular government exam categories lead to completely different careers — banking operations, central ministry desk work, or state-level administration. choose wisely. career government job banking ssc state psc"},
  {url:"/compare/credit-card-vs-debit-card",title:"Credit Card vs Debit Card — Which to Use When?",desc:"Debit card spends YOUR money instantly. Credit card gives you a 45-day free loan. Both have their place — here is when t",cat:"Compare",icon:"⚖️",s:"credit card vs debit card — which to use when? debit card spends your money instantly. credit card gives you a 45-day free loan. both have their place — here is when to use each. credit card debit card banking rewards"},
  {url:"/compare/elss-vs-ppf-vs-nps",title:"ELSS vs PPF vs NPS — Tax Saving Under 80C Compared",desc:"3 best 80C investments ranked: ELSS (3yr lock, 12-15%), PPF (15yr lock, 7.1% tax-free), NPS (60yr lock, 9-12% + extra 50",cat:"Compare",icon:"⚖️",s:"elss vs ppf vs nps — tax saving under 80c compared 3 best 80c investments ranked: elss (3yr lock, 12-15%), ppf (15yr lock, 7.1% tax-free), nps (60yr lock, 9-12% + extra 50k deduction). tax saving 80c"},
  {url:"/compare/fd-rates-comparison",title:"FD Interest Rates 2026 — SBI vs HDFC vs Post Office vs Small Finance Banks",desc:"Compare fixed deposit interest rates across major banks, post office, and small finance banks — find who gives the best ",cat:"Compare",icon:"⚖️",s:"fd interest rates 2026 — sbi vs hdfc vs post office vs small finance banks compare fixed deposit interest rates across major banks, post office, and small finance banks — find who gives the best rate for your deposit tenure fd rates bank comparison interest rate savings small finance bank"},
  {url:"/compare/govt-job-vs-private",title:"Government Job vs Private Job — Honest Comparison",desc:"Government jobs offer security and pension, private jobs offer higher ceiling and faster growth — the right choice depen",cat:"Compare",icon:"⚖️",s:"government job vs private job — honest comparison government jobs offer security and pension, private jobs offer higher ceiling and faster growth — the right choice depends on your personality and priorities government job private job career salary comparison"},
  {url:"/compare/health-insurance-compare",title:"Star Health vs HDFC ERGO vs Care Health — Best Health Insurance 2026",desc:"Comparing India\'s top 4 health insurers on what actually matters — claim settlement, cashless hospital network, room ren",cat:"Compare",icon:"⚖️",s:"star health vs hdfc ergo vs care health — best health insurance 2026 comparing india\'s top 4 health insurers on what actually matters — claim settlement, cashless hospital network, room rent limits, and real customer experience health insurance star health care health hdfc ergo comparison"},
  {url:"/compare/home-loan-sbi-vs-hdfc",title:"Home Loan — SBI vs HDFC vs ICICI vs LIC HFL (2026 Rates)",desc:"SBI offers the lowest home loan rate at 8.5%+ while private banks charge 8.75%+. But rate is not everything — processing",cat:"Compare",icon:"🏠",s:"home loan — sbi vs hdfc vs icici vs lic hfl (2026 rates) sbi offers the lowest home loan rate at 8.5%+ while private banks charge 8.75%+. but rate is not everything — processing fees, prepayment flexibility, and service matter too. home loan sbi hdfc interest rate emi"},
  {url:"/compare/ibps-po-vs-sbi-po",title:"IBPS PO vs SBI PO — Which Banking Exam is Better?",desc:"Both are Probationary Officer exams but SBI pays more, has a stronger brand, and gives metro postings more often. IBPS P",cat:"Compare",icon:"⚖️",s:"ibps po vs sbi po — which banking exam is better? both are probationary officer exams but sbi pays more, has a stronger brand, and gives metro postings more often. ibps po has 10× more vacancies across 11 psbs. banking compare"},
  {url:"/compare/itr-1-vs-2-vs-3-vs-4",title:"Which ITR Form to File? ITR-1, ITR-2, ITR-3, ITR-4 Explained",desc:"Salaried with no capital gains? ITR-1. Have stocks or property sold? ITR-2. Business owner? ITR-3. Small business presum",cat:"Compare",icon:"📋",s:"which itr form to file? itr-1, itr-2, itr-3, itr-4 explained salaried with no capital gains? itr-1. have stocks or property sold? itr-2. business owner? itr-3. small business presumptive? itr-4. itr income tax filing itr-1 itr-2 tax return"},
  {url:"/compare/jee-vs-neet",title:"JEE Main vs NEET UG — Engineering vs Medical Comparison",desc:"Both are India\'s toughest UG entrance exams but lead to completely different careers. Here is what nobody tells students",cat:"Compare",icon:"⚖️",s:"jee main vs neet ug — engineering vs medical comparison both are india\'s toughest ug entrance exams but lead to completely different careers. here is what nobody tells students choosing between pcm and pcb. career education"},
  {url:"/compare/lic-vs-private-term",title:"LIC Term Plan vs Private Insurer — Which is Better?",desc:"LIC has 98.6% claim settlement, but private insurers like HDFC (99.1%) and Max Life (99.5%) beat LIC on both claims AND ",cat:"Compare",icon:"⚖️",s:"lic term plan vs private insurer — which is better? lic has 98.6% claim settlement, but private insurers like hdfc (99.1%) and max life (99.5%) beat lic on both claims and premiums — here\'s the data lic private insurance term plan claim ratio comparison"},
  {url:"/compare/mutual-fund-vs-fd",title:"Mutual Fund vs Fixed Deposit — Where to Invest?",desc:"FDs give guaranteed 7% but lose to inflation after tax. Mutual funds give 10-15% with market risk but create real wealth",cat:"Compare",icon:"⚖️",s:"mutual fund vs fixed deposit — where to invest? fds give guaranteed 7% but lose to inflation after tax. mutual funds give 10-15% with market risk but create real wealth over 10+ years. mutual fund fd returns risk comparison"},
  {url:"/compare/neet-pg-vs-gate",title:"NEET PG vs GATE — Postgraduate Entrance Comparison",desc:"NEET PG decides your medical specialization and lifetime earning. GATE decides IIT admission and PSU placement. Both are",cat:"Compare",icon:"⚖️",s:"neet pg vs gate — postgraduate entrance comparison neet pg decides your medical specialization and lifetime earning. gate decides iit admission and psu placement. both are career-defining pg exams. exam compare"},
  {url:"/compare/nps-vs-epf-vs-ppf",title:"NPS vs EPF vs PPF — Which Retirement Savings is Best?",desc:"Three government-backed retirement savings options — EPF for salaried (8.25%), PPF for everyone (7.1%), NPS for market-l",cat:"Compare",icon:"⚖️",s:"nps vs epf vs ppf — which retirement savings is best? three government-backed retirement savings options — epf for salaried (8.25%), ppf for everyone (7.1%), nps for market-linked growth (9-12%) — which mix is right for you? nps epf ppf retirement pension comparison"},
  {url:"/compare/old-vs-new-tax-regime",title:"Old vs New Tax Regime 2026 — Which Saves More Tax?",desc:"New regime has lower slab rates but NO deductions. Old regime has higher rates but allows 80C, HRA, 80D deductions. Your",cat:"Compare",icon:"⚖️",s:"old vs new tax regime 2026 — which saves more tax? new regime has lower slab rates but no deductions. old regime has higher rates but allows 80c, hra, 80d deductions. your choice depends on your deduction profile. tax regime income tax old vs new 80c deductions"},
  {url:"/compare/ppf-vs-elss",title:"PPF vs ELSS — Best Tax-Saving Investment Under 80C",desc:"PPF gives guaranteed 7.1% with 15-year lock-in. ELSS gives market-linked 12-15% with only 3-year lock-in. Your risk appe",cat:"Compare",icon:"⚖️",s:"ppf vs elss — best tax-saving investment under 80c ppf gives guaranteed 7.1% with 15-year lock-in. elss gives market-linked 12-15% with only 3-year lock-in. your risk appetite decides the winner. ppf elss 80c tax saving comparison"},
  {url:"/compare/rd-vs-fd-vs-ppf",title:"RD vs FD vs PPF — Best Monthly Savings Option",desc:"Recurring Deposit for short-term discipline, FD for lump sum safety, PPF for long-term tax-free growth — each serves a d",cat:"Compare",icon:"⚖️",s:"rd vs fd vs ppf — best monthly savings option recurring deposit for short-term discipline, fd for lump sum safety, ppf for long-term tax-free growth — each serves a different purpose. savings compare"},
  {url:"/compare/sbi-vs-hdfc-savings",title:"SBI vs HDFC Savings Account — Which Bank is Better?",desc:"SBI has 50+ crore accounts with government backing, HDFC has better digital experience and customer service — here\'s a d",cat:"Compare",icon:"⚖️",s:"sbi vs hdfc savings account — which bank is better? sbi has 50+ crore accounts with government backing, hdfc has better digital experience and customer service — here\'s a data-driven comparison sbi hdfc savings account bank comparison interest rate"},
  {url:"/compare/sip-vs-lumpsum",title:"SIP vs Lump Sum Investment — Which is Better?",desc:"SIP averages out market volatility with monthly investing while lump sum gives higher returns in rising markets — the ri",cat:"Compare",icon:"⚖️",s:"sip vs lump sum investment — which is better? sip averages out market volatility with monthly investing while lump sum gives higher returns in rising markets — the right choice depends on your situation sip lump sum mutual fund investing"},
  {url:"/compare/ssc-cgl-vs-chsl",title:"SSC CGL vs SSC CHSL — Which Exam to Choose?",desc:"CGL gives ₹44K+ posts (Tax Inspector, Auditor) while CHSL gives ₹25K+ posts (LDC, DEO) — same agency, very different car",cat:"Compare",icon:"⚖️",s:"ssc cgl vs ssc chsl — which exam to choose? cgl gives ₹44k+ posts (tax inspector, auditor) while chsl gives ₹25k+ posts (ldc, deo) — same agency, very different career outcomes ssc cgl chsl salary comparison government job"},
  {url:"/compare/ssc-cgl-vs-ibps-po",title:"SSC CGL vs IBPS PO — Which Government Exam to Choose?",desc:"CGL gives you a desk job in government offices (Tax, Audit, Ministry). Banking gives customer-facing + marketing + rural",cat:"Compare",icon:"⚖️",s:"ssc cgl vs ibps po — which government exam to choose? cgl gives you a desk job in government offices (tax, audit, ministry). banking gives customer-facing + marketing + rural posting. different lifestyles entirely. ssc banking"},
  {url:"/compare/term-vs-endowment",title:"Term Insurance vs Endowment Plan — Which Should You Buy?",desc:"Term insurance gives 10× more coverage at 1/5th the price of endowment plans — here\'s why financial experts unanimously ",cat:"Compare",icon:"⚖️",s:"term insurance vs endowment plan — which should you buy? term insurance gives 10× more coverage at 1/5th the price of endowment plans — here\'s why financial experts unanimously recommend term over endowment insurance term endowment lic comparison"},
  {url:"/compare/upsc-vs-state-psc",title:"UPSC CSE vs State PSC — Which Civil Services to Target?",desc:"UPSC gives IAS/IPS with all-India transfers and national power. State PSC gives similar salary with home state posting a",cat:"Compare",icon:"⚖️",s:"upsc cse vs state psc — which civil services to target? upsc gives ias/ips with all-india transfers and national power. state psc gives similar salary with home state posting and less competition. upsc state psc ias pcs career comparison"},
  {url:"/calculator/sip-calculator",title:"SIP Calculator",desc:"Calculate returns on monthly SIP investments",cat:"Calculator",icon:"📈",s:"sip calculator calculate returns on monthly sip investments calculator finance"},
  {url:"/calculator/emi-calculator",title:"EMI Calculator",desc:"Calculate monthly EMI for home, car, personal loan",cat:"Calculator",icon:"🏠",s:"emi calculator calculate monthly emi for home, car, personal loan calculator finance"},
  {url:"/calculator/fd-calculator",title:"FD Calculator",desc:"Calculate fixed deposit maturity amount and interest",cat:"Calculator",icon:"🏦",s:"fd calculator calculate fixed deposit maturity amount and interest calculator finance"},
  {url:"/calculator/ppf-calculator",title:"PPF Calculator",desc:"Calculate PPF maturity with yearly deposits",cat:"Calculator",icon:"🔒",s:"ppf calculator calculate ppf maturity with yearly deposits calculator finance"},
  {url:"/calculator/income-tax-calculator",title:"Income Tax Calculator",desc:"Compare old vs new tax regime",cat:"Calculator",icon:"📋",s:"income tax calculator compare old vs new tax regime calculator finance"},
  {url:"/calculator/gratuity-calculator",title:"Gratuity Calculator",desc:"Calculate gratuity based on salary and years",cat:"Calculator",icon:"💼",s:"gratuity calculator calculate gratuity based on salary and years calculator finance"},
  {url:"/calculator/hra-calculator",title:"HRA Calculator",desc:"Calculate HRA tax exemption",cat:"Calculator",icon:"🏘️",s:"hra calculator calculate hra tax exemption calculator finance"},
  {url:"/calculator/lumpsum-calculator",title:"Lump Sum Calculator",desc:"Calculate one-time investment returns",cat:"Calculator",icon:"💰",s:"lump sum calculator calculate one-time investment returns calculator finance"},
  {url:"/check-eligibility",title:"Eligibility Checker",desc:"Find which government schemes you qualify for",cat:"Tool",icon:"🔍",s:"eligibility checker schemes qualify"},
];

function SearchResults() {
  const searchParams = useSearchParams();
  const q = searchParams.get("q")?.toLowerCase() || "";

  const results = q.length > 1
    ? allPages.filter((p) => p.s.includes(q)).slice(0, 20)
    : [];

  return (
    <div className="max-w-[860px] mx-auto px-5 py-6">
      <h1 className="text-2xl font-extrabold tracking-tight text-text mb-2">Search Results</h1>
      {q && <p className="text-sm text-text-secondary mb-6">Showing results for &quot;{searchParams.get("q")}&quot;</p>}
      {!q && <p className="text-sm text-text-secondary mb-6">Enter a search term to find pages</p>}

      {results.length > 0 ? (
        <div className="flex flex-col gap-3">
          {results.map((r) => (
            <Link
              key={r.url}
              href={r.url}
              className="bg-card border border-border rounded-2xl p-4 grid grid-cols-[40px_1fr] gap-3 hover:border-accent/40 hover:shadow-sm hover:-translate-y-px transition-all"
            >
              <div className="w-10 h-10 rounded-xl bg-card-alt flex items-center justify-center text-lg">{r.icon}</div>
              <div>
                <div className="flex items-center gap-2 mb-0.5">
                  <span className="text-sm font-bold text-text">{r.title}</span>
                  <span className="px-2 py-0.5 rounded-md text-[10px] font-semibold bg-accent-light text-accent">{r.cat}</span>
                </div>
                <div className="text-xs text-text-secondary leading-relaxed">{r.desc}</div>
              </div>
            </Link>
          ))}
        </div>
      ) : q.length > 1 ? (
        <p className="text-center py-10 text-text-muted">No results found for &quot;{searchParams.get("q")}&quot;</p>
      ) : null}
    </div>
  );
}

export default function SearchPage() {
  return (
    <Suspense fallback={<div className="max-w-[860px] mx-auto px-5 py-6"><p className="text-text-muted">Loading...</p></div>}>
      <SearchResults />
    </Suspense>
  );
}
