import type { Metadata } from "next";
import { PpfCalc } from "@/components/calculators/ppf-calc";
import { JsonLd, faqSchema, breadcrumbSchema } from "@/components/json-ld";
import { Breadcrumb, SectionHeading, FAQ } from "@/components/ui";

export const metadata: Metadata = {
  title: "PPF Calculator 2026 — Calculate Maturity Amount & Interest Online",
  description: "Free PPF calculator for 2026. Enter yearly deposit to calculate maturity amount after 15 years at 7.1% interest. Covers extension rules, partial withdrawal, loan facility, and tax benefits under Section 80C.",
  alternates: { canonical: "https://knowledgekendra.com/calculator/ppf-calculator" },
};

const faqs = [
  { question: "What is the current PPF interest rate?", answer: "The PPF interest rate for Q1 FY 2026-27 (April-June 2026) is 7.1% per annum, compounded annually. The rate is reviewed quarterly by the government but has remained at 7.1% since January 2023. PPF interest is completely tax-free — making the effective pre-tax return approximately 10.2% for someone in the 30% tax bracket." },
  { question: "What is the minimum and maximum PPF deposit?", answer: "Minimum: ₹500 per year (must deposit at least this to keep the account active). Maximum: ₹1,50,000 per year. Deposits can be made in lump sum or up to 12 installments. If you deposit more than ₹1.5 lakh, the excess earns no interest and is not eligible for 80C deduction. It will be returned without interest." },
  { question: "Can I open PPF account online?", answer: "Yes. Most banks (SBI, ICICI, HDFC, Axis) and India Post allow online PPF account opening via net banking. You need PAN, Aadhaar, and a savings account with the bank. The process takes 10-15 minutes. You can also deposit and manage your PPF entirely online. One person can have only ONE PPF account (operating two is illegal and the second will be closed)." },
  { question: "When should I deposit in PPF for maximum interest?", answer: "Deposit before the 5th of every month. PPF interest is calculated on the minimum balance between the 5th and last day of each month. If you deposit ₹1.5 lakh on April 4, you earn interest for the full year. If you deposit on April 6, you lose one month of interest. For lump sum investors, depositing the full ₹1.5 lakh before April 5 maximizes returns." },
  { question: "Can I withdraw from PPF before maturity?", answer: "Partial withdrawal is allowed from the 7th financial year onwards (after completing 6 years). Maximum withdrawal: 50% of the balance at the end of the 4th year or the preceding year, whichever is lower. Only one withdrawal per year. You cannot close PPF before 15 years except in cases of serious medical emergency or higher education (after completing 5 years)." },
  { question: "Can I take a loan against PPF?", answer: "Yes, from the 3rd to 6th financial year. Maximum loan: 25% of the balance at the end of the 2nd preceding year. Interest on PPF loan is 1% above the PPF interest rate (currently 8.1%). Loan must be repaid within 36 months. This facility is useful for short-term needs without breaking the PPF lock-in. After the 6th year, partial withdrawal replaces the loan facility." },
  { question: "What happens after PPF maturity (15 years)?", answer: "Three options: (1) Withdraw the entire maturity amount tax-free. (2) Extend for 5 years WITH fresh contributions (continue depositing ₹500-1.5L/year, continue earning interest). (3) Extend for 5 years WITHOUT contributions (no deposits, but existing balance continues earning interest). You can extend multiple times in 5-year blocks indefinitely." },
  { question: "Is PPF better than FD?", answer: "PPF wins on: tax-free returns (FD interest is fully taxable), higher effective rate (PPF 7.1% tax-free = ~10.2% pre-tax at 30% slab vs FD 7% pre-tax = ~4.9% post-tax), and Section 80C benefit. FD wins on: flexibility (break anytime), shorter lock-in (1-10 years vs 15 years), and availability for any amount. For long-term savings, PPF is clearly superior. For short-term needs, FD is more practical." },
  { question: "Can NRI open or continue PPF?", answer: "NRIs cannot open new PPF accounts. However, if you opened a PPF before becoming NRI, you can continue it until maturity (15 years from opening). You cannot extend beyond maturity. Interest rate may differ for NRI PPF accounts (some banks apply savings account rate instead of PPF rate — check with your bank). The tax treatment follows the India-resident country DTAA." },
  { question: "Is PPF interest compounded monthly or yearly?", answer: "PPF interest is compounded annually, not monthly. Interest is calculated monthly (on balance between 5th and last day) but credited to your account only at the end of the financial year (March 31). This means interest-on-interest happens only yearly. Compare this with FD which can compound quarterly — but PPF still wins due to the tax-free advantage." },
  { question: "Can I transfer PPF between banks?", answer: "Yes. PPF accounts can be transferred from one bank to another, or from post office to bank (and vice versa). Submit a transfer request at your current bank. The process takes 2-4 weeks. Your account number may change but the opening date and maturity date remain the same. No break in lock-in period." },
  { question: "What is PPF EEE status?", answer: "PPF enjoys EEE (Exempt-Exempt-Exempt) status: (1) Contribution is exempt (80C deduction up to ₹1.5 lakh). (2) Interest earned is exempt from tax. (3) Maturity amount is exempt from tax. Very few instruments have full EEE status — EPF (with conditions) and SSY are the other major ones. This makes PPF one of the most tax-efficient instruments in India." },
  { question: "What happens to PPF if the account holder dies?", answer: "The entire PPF balance (including interest up to date of death) is paid to the nominee. If no nominee is designated, it goes to legal heirs. The account cannot be continued by the nominee — it must be closed. The death benefit is completely tax-free. The nominee should submit death certificate, PPF passbook, and nomination form to the bank to claim the amount." },
  { question: "Can I have PPF for my child?", answer: "Yes, parents or guardians can open a PPF account in the name of a minor child. However, the combined deposit limit for parent's own PPF + child's PPF is ₹1.5 lakh per year (not ₹1.5 lakh each). The 80C deduction is also shared. Once the child turns 18, they can operate the account independently. A minor can have only one PPF account." },
];

export default function Page() {
  return (
    <div className="max-w-[860px] mx-auto px-5 py-6">
      <JsonLd data={breadcrumbSchema([{ name: "Home", url: "https://knowledgekendra.com" }, { name: "Calculators", url: "https://knowledgekendra.com/calculator" }, { name: "PPF Calculator 2026", url: "https://knowledgekendra.com/calculator/ppf-calculator" }])} />
      <JsonLd data={faqSchema(faqs)} />
      <JsonLd data={{ "@context": "https://schema.org", "@type": "WebApplication", name: "PPF Calculator 2026", description: "Free PPF calculator — estimate maturity amount at 7.1% interest over 15 years.", applicationCategory: "FinanceApplication", operatingSystem: "Web", offers: { "@type": "Offer", price: "0", priceCurrency: "INR" } }} />
      <Breadcrumb items={[{ label: "Home", href: "/" }, { label: "Calculators", href: "/calculator" }, { label: "PPF Calculator 2026" }]} />
      <h1 className="text-2xl font-extrabold tracking-tight text-text mb-2">PPF Calculator 2026</h1>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-6">Calculate your PPF maturity amount and interest earned. Enter your annual deposit to see how your money grows over the 15-year tenure at the current 7.1% interest rate. PPF offers EEE tax status — contributions, interest, and maturity are all tax-free.</p>
      <PpfCalc />

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #2563EB", backgroundColor: "#DBEAFE" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2"><span>💡</span><span>PPF golden rule</span></p>
        <p className="text-sm text-text-secondary leading-relaxed">Deposit before the <strong>5th of every month</strong>. PPF interest is calculated on the minimum balance between 5th and month-end. Depositing ₹1.5 lakh on April 4th vs April 6th means an entire month of lost interest. Over 15 years, this timing discipline adds approximately ₹30,000-50,000 extra to your maturity.</p>
      </div>

      <SectionHeading icon="📖">What is PPF?</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Public Provident Fund (PPF) is a government-backed savings scheme with a 15-year lock-in period and guaranteed returns. Launched in 1968, it remains one of India&apos;s most popular tax-saving instruments. The current interest rate is 7.1% per annum, compounded annually. Any Indian resident can open a PPF account at post offices or designated banks.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">PPF&apos;s biggest advantage is its <strong>EEE (Exempt-Exempt-Exempt)</strong> tax status. Your contribution gets 80C deduction (up to ₹1.5 lakh). Interest earned during the 15-year tenure is tax-free. And the maturity amount is also completely tax-free. Very few instruments offer all three exemptions — this makes PPF&apos;s effective return significantly higher than its nominal 7.1%.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">For someone in the 30% tax bracket, PPF&apos;s 7.1% tax-free return is equivalent to approximately 10.2% pre-tax. Compare this with a bank FD at 7% which gives only ~4.9% after tax. PPF delivers more than double the post-tax return of an FD — the difference over 15 years is lakhs of rupees.</p>

      <div className="my-6">
        <p className="text-xs text-text-muted mb-2 text-center italic">PPF maturity for different annual deposits</p>
        <div className="card p-4 flex justify-center overflow-x-auto" dangerouslySetInnerHTML={{ __html: '<svg viewBox="0 0 700 230" xmlns="http://www.w3.org/2000/svg" style="max-width:100%;height:auto"><text x="350" y="25" text-anchor="middle" font-family="sans-serif" font-size="14" font-weight="700" fill="#111827">PPF maturity at 7.1% — by annual deposit (15 years)</text><line x1="80" y1="190" x2="650" y2="190" stroke="#4B5563" stroke-width="1"/><rect x="110" y="155" width="80" height="35" fill="#DCFCE7" stroke="#1B6B4A" stroke-width="1.5"/><text x="150" y="210" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#4B5563">₹50K/yr</text><text x="150" y="150" text-anchor="middle" font-family="sans-serif" font-size="10" font-weight="700" fill="#1B6B4A">₹13.6L</text><rect x="230" y="118" width="80" height="72" fill="#DCFCE7" stroke="#1B6B4A" stroke-width="1.5"/><text x="270" y="210" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#4B5563">₹1L/yr</text><text x="270" y="113" text-anchor="middle" font-family="sans-serif" font-size="10" font-weight="700" fill="#1B6B4A">₹27.1L</text><rect x="350" y="70" width="80" height="120" fill="#1B6B4A"/><text x="390" y="210" text-anchor="middle" font-family="sans-serif" font-size="10" fill="#4B5563">₹1.5L/yr</text><text x="390" y="65" text-anchor="middle" font-family="sans-serif" font-size="10" font-weight="700" fill="#1B6B4A">₹40.7L</text><text x="390" y="80" text-anchor="middle" font-family="sans-serif" font-size="9" fill="white">Invested: ₹22.5L</text><text x="390" y="95" text-anchor="middle" font-family="sans-serif" font-size="9" fill="white">Interest: ₹18.2L</text><text x="350" y="225" text-anchor="middle" font-family="sans-serif" font-size="10" font-style="italic" fill="#6B7280">Max ₹1.5L/year deposit. Interest = 81% of your contribution over 15 years.</text></svg>' }} />
      </div>

      <SectionHeading icon="📅">PPF withdrawal and extension rules</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Years 1-6:</strong> No withdrawal allowed. You can take a loan against PPF from year 3-6 (25% of balance at end of 2nd preceding year, at PPF rate + 1%).</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Year 7 onwards:</strong> Partial withdrawal allowed — up to 50% of balance at end of 4th preceding year. One withdrawal per year. No need to give a reason. This is useful for children&apos;s education, medical needs, or any other purpose.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Year 15 (maturity):</strong> Three options: (a) withdraw everything tax-free, (b) extend 5 years with contributions (continue depositing and earning interest), or (c) extend 5 years without contributions (no deposits, but balance keeps earning 7.1%). You can extend indefinitely in 5-year blocks. Many people extend into retirement for steady tax-free income.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Premature closure:</strong> Only allowed after 5 years for medical emergency (self/spouse/children/parents) or higher education. Penalty: 1% reduction from applicable interest rate. Not recommended unless absolutely necessary — the tax-free compounding benefit is too valuable to break.</p>

      <blockquote className="my-6 border-l-4 border-accent pl-5 py-2">
        <p className="text-lg font-semibold text-text leading-snug italic">₹1.5 lakh/year in PPF for 15 years = <strong>₹40.7 lakh maturity</strong>. You invested ₹22.5 lakh. Interest earned: ₹18.2 lakh — completely tax-free. Extend for 5 more years without any deposits? Balance grows to ₹57.5 lakh. Free money from compounding.</p>
      </blockquote>

      <SectionHeading icon="⚖️">PPF vs EPF vs NPS vs ELSS</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>PPF (7.1%, 15yr lock-in):</strong> Best for guaranteed, completely tax-free returns. Zero risk. Self-managed. No employer involvement.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>EPF (8.25%, until 58):</strong> Higher rate but locked until retirement. Employer co-contributes. Auto-deducted from salary. Not available for self-employed. Better rate than PPF but less flexibility.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>NPS (10-12%, until 60):</strong> Highest potential returns (market-linked equity). Extra ₹50K deduction under 80CCD(1B). But 40% mandatory annuity at 60 (pension is taxable). Longest lock-in. Best for equity exposure within tax-saving.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>ELSS (12-15%, 3yr lock-in):</strong> Shortest lock-in among 80C options. Highest return potential (equity mutual funds). But returns are not guaranteed and LTCG above ₹1.25L is taxable at 12.5%. Best for aggressive investors comfortable with market risk.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Recommended mix:</strong> EPF (automatic via salary) + PPF ₹50K-1L/year (guaranteed base) + ELSS for remaining 80C room (equity growth) + NPS ₹50K (extra deduction). This gives diversification across guaranteed and market-linked returns.</p>

      <div className="my-5 rounded-r-lg p-4" style={{ borderLeft: "4px solid #DC2626", backgroundColor: "#FEE2E2" }}>
        <p className="text-sm font-bold mb-1.5 text-text flex items-center gap-2"><span>⚠️</span><span>Common PPF mistakes</span></p>
        <p className="text-sm text-text-secondary leading-relaxed"><strong>1.</strong> Depositing after the 5th — lose that month&apos;s interest. <strong>2.</strong> Not depositing minimum ₹500/year — account becomes inactive (₹50/year penalty to reactivate). <strong>3.</strong> Opening two PPF accounts — illegal, second account earns no interest. <strong>4.</strong> Forgetting to extend at maturity — account stays but earns lower rate. <strong>5.</strong> Using PPF for short-term goals — 15-year lock-in means this money is inaccessible.</p>
      </div>

      <SectionHeading icon="📚">Official source</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">PPF interest rates are notified quarterly by the Ministry of Finance. Current rates at <a href="https://dea.gov.in" target="_blank" rel="noopener" className="text-accent hover:underline">dea.gov.in</a>. Open PPF at <a href="https://www.sbi.co.in" target="_blank" rel="noopener" className="text-accent hover:underline">SBI</a>, <a href="https://www.indiapost.gov.in" target="_blank" rel="noopener" className="text-accent hover:underline">India Post</a>, or any designated bank.</p>
      <p className="text-xs text-text-muted mt-6 mb-8 italic">Last reviewed: April 2026 • Rate: 7.1% (Q1 FY 2026-27). This is for informational purposes only.</p>

      <SectionHeading icon="💡">Smart PPF strategies most people miss</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Strategy 1 — Maximize interest with April 4 deposit:</strong> If you can invest the full ₹1.5 lakh as lumpsum, deposit it on April 4 (before 5th) to earn interest for all 12 months of the financial year. A ₹1.5L deposit on April 4 earns approximately ₹1,400 more interest per year compared to depositing on March 31 of the same year. Over 15 years, this timing discipline adds ₹35,000-50,000 to your maturity.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Strategy 2 — Use PPF extension for retirement income:</strong> After 15 years, extend PPF WITHOUT new contributions. Your ₹40+ lakh corpus continues earning 7.1% tax-free = approximately ₹2.85 lakh/year interest. You can withdraw freely (one withdrawal per year). This creates a tax-free income stream in retirement without touching the principal.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Strategy 3 — Open PPF for your child early:</strong> Open a minor PPF account when your child is born. By age 15, the PPF matures. Extend with contributions until the child is 23 — they have a ₹40+ lakh corpus for higher education or career, all earned tax-free. The combined limit (parent + child) is ₹1.5L/year — so plan your own PPF contribution accordingly.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Strategy 4 — PPF as emergency backup:</strong> After year 7, PPF allows partial withdrawal (50% of year-4 balance). This makes PPF function as a long-term emergency fund with better returns than a savings account. The key: don&apos;t actually withdraw unless truly needed. Let the power of compounding work — but know the safety net exists.</p>

      <SectionHeading icon="📈">PPF interest rate outlook</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">PPF rates are linked to 10-year government bond yields with a 25 basis point spread. As of April 2026, 10-year G-sec yield is approximately 6.8-6.9%, supporting the current 7.1% PPF rate. If bond yields rise (due to RBI tightening or fiscal deficit), PPF rates could increase in future quarters. If yields fall (rate cuts), PPF rates might decrease — though the government has been reluctant to cut PPF rates below 7% due to political sensitivity.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5">Historically, PPF rates were as high as 12% in the 1990s and have been on a declining trend: 9.5% in 2000, 8.7% in 2010, 8% in 2015, 7.1% since 2023. Despite the declining trend, PPF remains attractive because it&apos;s compared against post-tax returns of alternatives. At 7.1% tax-free, PPF is equivalent to a 10%+ pre-tax instrument — few investments offer that with sovereign safety.</p>

      <SectionHeading icon="🏦">Where to open PPF — bank vs post office</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Banks (SBI, HDFC, ICICI, etc.):</strong> Online access, net banking deposits, mobile app management. Transfer between branches is easy. Linked to your existing savings account for seamless deposits. Recommended for most urban investors. ICICI and HDFC offer the best online PPF management interfaces.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Post Office:</strong> Available everywhere including rural areas. Traditional passbook system. Online access has improved but still lags behind banks. Post office PPF can be transferred to a bank (and vice versa). Good if your nearest banking is limited. Interest rate is the same regardless of where you open.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Important:</strong> You can have only ONE PPF account. Operating two is illegal — the second account will be closed with only principal returned (no interest). If you accidentally opened two, consolidate them by transferring the second into the first at the earliest. The oldest account&apos;s opening date is preserved.</p>

      <SectionHeading icon="💰">PPF vs Sukanya Samriddhi vs NSC — government savings compared</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>PPF (7.1%, 15yr lock-in):</strong> Available to all Indian residents. ₹500-1.5L annual deposit. EEE tax status (contribution, interest, maturity all tax-free). Best for long-term guaranteed savings with maximum tax efficiency. Can be extended indefinitely in 5-year blocks.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Sukanya Samriddhi Yojana (8.2%, 21yr):</strong> Only for girl children under 10 years. ₹250-1.5L annual deposit. EEE status. Higher rate than PPF. Deposits required for first 15 years, account matures at 21 or girl&apos;s marriage after 18. If you have a daughter, SSY should be prioritized over PPF due to the 1.1% higher rate — over 15 years that adds approximately ₹2.5 lakh more on ₹1.5L annual deposits.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>National Savings Certificate (6.8%, 5yr):</strong> Fixed 5-year deposit. No premature withdrawal. Interest is taxable annually (accrual basis) but qualifies for 80C reinvestment deduction in years 1-4. Lower rate than PPF but shorter lock-in. Useful if you need 80C deduction and want money back in 5 years instead of 15. Available at any post office.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Kisan Vikas Patra (7.5%, doubles in ~115 months):</strong> No maximum limit. Available at post offices. Interest is taxable at slab rate. No 80C benefit. Lock-in of 30 months (premature closure allowed after that with penalty). Good for risk-averse investors who want a simple &quot;double your money&quot; product without tax considerations.</p>

      <SectionHeading icon="📊">PPF maturity projections — planning your corpus</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Conservative saver (₹50,000/year):</strong> After 15 years at 7.1% = ₹13.56 lakh. After 20 years (5-year extension with deposits) = ₹21.73 lakh. After 25 years = ₹33.26 lakh. Even modest amounts create meaningful wealth over PPF&apos;s long compounding period.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Maximum contributor (₹1,50,000/year):</strong> After 15 years = ₹40.68 lakh (invested ₹22.5L, interest ₹18.2L). After 20 years = ₹65.18 lakh. After 25 years = ₹99.77 lakh — nearly ₹1 crore! If you max out PPF for 25 years, you build a ₹1 crore tax-free corpus with zero risk. No other instrument offers this combination of safety, returns, and tax efficiency.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Late starter (age 40, ₹1,50,000/year):</strong> PPF matures at age 55 with ₹40.68 lakh. Extend without deposits until 60: grows to ₹57.50 lakh (interest alone adds ₹16.82L in those 5 years without any fresh deposits). Extend further to 65 = ₹81.24 lakh. Even starting at 40, PPF creates a strong retirement supplement.</p>

      <SectionHeading icon="⚠️">PPF pitfalls and how to avoid them</SectionHeading>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Inactive account trap:</strong> If you don&apos;t deposit minimum ₹500 in any financial year, the account becomes &quot;discontinued.&quot; To reactivate, pay ₹50 penalty per year of default + ₹500 minimum for each missed year + ₹500 for the current year. On an account inactive for 5 years, that&apos;s ₹250 penalty + ₹2,500 back deposits + ₹500 current = ₹3,250 to reactivate. Set an annual reminder to deposit at least ₹500.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Maturity without extension:</strong> If your PPF matures and you don&apos;t actively choose an extension option within 1 year of maturity, the account continues in &quot;no contribution&quot; mode by default. You can still withdraw, and the balance earns interest, but you cannot make fresh deposits. If you intended to extend WITH deposits, apply within 1 year of maturity — it&apos;s retroactive only within this window.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Nomination oversight:</strong> Many PPF holders forget to update nominee after life changes (marriage, children). If you die without a nominee, the legal heir has to go through probate/succession certificate — delaying access to funds by months. Update nominee whenever your family situation changes. Both banks and post offices allow online nominee updation.</p>
      <p className="text-[15px] text-text-secondary leading-[1.75] mb-5"><strong>Joint account myth:</strong> PPF cannot be held jointly. It&apos;s always a single-holder account. Husband and wife should open separate accounts to maximize the ₹1.5 lakh × 2 = ₹3 lakh annual family contribution (and double the 80C deduction). Each gets their own tax-free compounding trajectory.</p>

      <SectionHeading icon="❓">Frequently asked questions</SectionHeading>
      {faqs.map((f: any) => <FAQ key={f.question} question={f.question} answer={f.answer} />)}
      <div className="mt-10 flex flex-wrap gap-2">
        <a href="/calculator/epf-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">EPF Calculator →</a>
        <a href="/calculator/fd-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">FD Calculator →</a>
        <a href="/calculator/nps-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">NPS Calculator →</a>
        <a href="/calculator/sip-calculator" className="px-4 py-2 rounded-lg text-sm bg-card border border-border hover:border-accent/40 text-text-secondary transition-colors">SIP Calculator →</a>
      </div>
    </div>
  );
}
